Repository Azure/ARO-RP, pull requests merged in 2020-05, with the labels that each got.

#648 Rebase installer
  Gopkg.lock
  cgmanifest.json
  docs/upstream-differences.md
  vendor/github.com/openshift/installer/pkg/asset/tls/tls.go
Labels: next-up, priority-high

#649 Move probes from TCP to HTTPS
  pkg/install/deployresources.go
  pkg/install/loadbalancer.go
Labels: next-up, priority-high

#516 Add brief python az aro howto
  docs/az-aro-python-development.md
Labels: documentation, priority-medium

#629 Enirch vm status
  pkg/frontend/admin_openshiftcluster_resources_list.go
  pkg/frontend/admin_openshiftcluster_resources_list_test.go
  pkg/util/azureclient/mgmt/compute/virtualmachines.go
  pkg/util/mocks/azureclient/mgmt/compute/compute.go
Labels: next-up, priority-medium

#645 Remove preview API swagger generation
  pkg/api/v20191231preview/generate.go
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2019-12-31-preview/examples/OpenShiftClusters_CreateOrUpdate.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2019-12-31-preview/examples/OpenShiftClusters_Delete.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2019-12-31-preview/examples/OpenShiftClusters_Get.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2019-12-31-preview/examples/OpenShiftClusters_List.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2019-12-31-preview/examples/OpenShiftClusters_ListByResourceGroup.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2019-12-31-preview/examples/OpenShiftClusters_ListCredentials.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2019-12-31-preview/examples/OpenShiftClusters_Update.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2019-12-31-preview/examples/Operations_List.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2019-12-31-preview/redhatopenshift.json
Labels: ready-for-review

#624 Add a better message when the groupKind matches multiple
  pkg/frontend/kubeactions/kubeactions.go
  pkg/frontend/kubeactions/kubeactions_test.go
Labels: next-up, priority-medium

#686 handle pull secrets of incorrect type and invalid content on upgrade
  hack/ssh.sh
  pkg/install/fixpullsecret.go
  pkg/install/fixpullsecret_test.go
Labels: next-up, priority-high

#675 Switch uuid5 back to uuid4 in az aro extenstion
  python/az/aro/azext_aro/_rbac.py
  python/az/aro/azext_aro/custom.py
  python/az/aro/azext_aro/tests/latest/test_aro_scenario.py
Labels: next-up

#698 Fixing CI with new GOROOT
  .pipelines/templates/template-setup-golang-env.yml
  .pipelines/vars.yml
Labels: bug, next-up

#631 Add retries to create_service_principal
  python/az/aro/azext_aro/_aad.py
Labels: next-up, priority-high

#632 Guard more against AuthorizationFailed on create (w/ refactoring)
  pkg/api/validate/openshiftcluster_validatedynamic.go
  pkg/api/validate/openshiftcluster_validatedynamic_test.go
  pkg/api/validate/quota.go
  pkg/api/validate/quota_test.go
  pkg/backend/openshiftcluster/create.go
  pkg/backend/openshiftcluster/openshiftcluster.go
  pkg/backend/openshiftcluster/update.go
  pkg/install/deploystorage.go
  pkg/install/install.go
  pkg/util/azureerrors/error.go
  pkg/util/azureerrors/error_test.go
Labels: next-up, priority-high

#717 in admin api, marshal install phase the same as in the internal api, …
  pkg/api/admin/generate.go
  pkg/api/admin/marshal.go
  pkg/api/admin/zz_generated_installphase_enumer.go
Labels: next-up

#719 retry once on DeploymentFailed on full deployments
  pkg/deploy/deploy.go
Labels: next-up

#738 deploy: pull images once at first boot
  deploy/env-development.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources.go
Labels: next-up

#730 Fix location format
  hack/e2e/run-rp-and-e2e.sh
  pkg/backend/openshiftcluster/create.go
Labels: next-up, ready-for-review

#630 adding location to the alert name
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/deploy.go
  pkg/deploy/generator/resources.go
  pkg/util/azureclient/mgmt/insights/generate.go
  pkg/util/azureclient/mgmt/insights/metricalerts.go
  pkg/util/mocks/azureclient/mgmt/insights/insights.go
Labels: priority-high

#571 added isHealthy flag, changed monitor heartbeat
  pkg/monitor/monitor.go
  pkg/monitor/worker.go
Labels: priority-medium

#749 Fixes dev environment
  pkg/env/dev.go
Labels: bug, priority-high, size-small

#748 Switch from random app names to RG naming
  python/az/aro/azext_aro/custom.py
Labels: next-up

#634 Improves token refresh retries
  pkg/util/aad/aad.go
Labels: priority-medium, work-in-progress

#727 Fixes deletion of stopped VMs
  pkg/backend/openshiftcluster/delete.go
  pkg/backend/openshiftcluster/openshiftcluster.go
  pkg/util/azureclient/mgmt/network/generate.go
  pkg/util/azureclient/mgmt/network/securitygroups.go
  pkg/util/azureclient/mgmt/network/securitygroups_addons.go
  pkg/util/mocks/azureclient/mgmt/network/network.go
Labels: next-up
