Repository Azure/ARO-RP, pull requests merged in 2020-08, with the labels that each got.

#860 Move runsteps into its own package
  pkg/api/validate/openshiftcluster_validatedynamic_test.go
  pkg/env/dev.go
  pkg/env/generate.go
  pkg/install/arooperator.go
  pkg/install/condition.go
  pkg/install/condition_test.go
  pkg/install/install.go
  pkg/install/install_test.go
  pkg/util/mocks/env/env.go
  pkg/util/mocks/refreshable/refreshable.go
  pkg/util/refreshable/generate.go
  pkg/util/refreshable/refreshable.go
  pkg/util/steps/action.go
  pkg/util/steps/condition.go
  pkg/util/steps/refreshing.go
  pkg/util/steps/runner.go
  pkg/util/steps/runner_test.go
Labels: needs-rebase, priority-high

#917 Skip operator e2e tests if the cluster CRD does not exist
  test/e2e/operator.go
Labels: priority-high

#886 Add serial console kubeaction and endpoint
  pkg/frontend/admin_openshiftcluster_serialconsole.go
  pkg/frontend/frontend.go
Labels: priority-high

#920 fix python linter
  linter_exclusions.yml
Labels: priority-high

#883 e2e smoke test
  Gopkg.lock
  pkg/util/ready/ready.go
  test/e2e/cluster.go
  test/e2e/setup.go
  test/util/project/project.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/typed/project/v1/doc.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/typed/project/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/typed/project/v1/project.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/typed/project/v1/project_client.go
  vendor/github.com/openshift/client-go/project/clientset/versioned/typed/project/v1/projectrequest.go
Labels: priority-medium

#907 Enable 4.3 to 4.4 upgrade
  pkg/install/upgrade.go
  pkg/install/upgrade_test.go
  pkg/util/status/clusterversionoperator_status.go
  pkg/util/version/stream.go
  pkg/util/version/stream_test.go
  pkg/util/version/version.go
  vendor/github.com/sirupsen/logrus/go.mod
Labels: priority-high

#923 Fix arosvc registry push
  .pipelines/templates/template-push-images-to-acr.yml
  Makefile
Labels: bug, priority-high

#914 Add canary to prod release
  .pipelines/prod-release.yml
Labels: priority-high

#895 env.Interface.IsDevelopment() for telling dev and prod apart in a more obvious way
  cmd/aro/monitor.go
  cmd/aro/rp.go
  pkg/backend/openshiftcluster/create.go
  pkg/backend/openshiftcluster/delete.go
  pkg/backend/openshiftcluster/openshiftcluster.go
  pkg/env/dev.go
  pkg/env/env.go
  pkg/env/env_test.go
  pkg/env/generate.go
  pkg/env/int.go
  pkg/env/prod.go
  pkg/frontend/middleware/headers.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/ready_get.go
  pkg/install/deploystorage.go
  pkg/install/samples.go
  pkg/install/tls.go
  pkg/metrics/statsd/statsd.go
  pkg/util/billing/billing.go
  pkg/util/billing/billing_test.go
  pkg/util/mocks/env/env.go
Labels: priority-medium

#921 Clarify docs for Python review
  docs/az-aro-python-development.md
Labels: documentation, priority-low

#877 Adds RP version storage account
  deploy/config.yaml.example
  deploy/rp-production-global.json
  pkg/deploy/bindata.go
  pkg/deploy/config.go
  pkg/deploy/generator/resources.go
  pkg/deploy/generator/templates.go
Labels: next-up, priority-medium

#916 Add ability to sync from custom build
  .pipelines/mirror-images.yml
Labels: next-up

#929 Change api version in swagger generation
  pkg/swagger/swagger.go
Labels: next-up

#934 Move each controller to it's own sub package
  cmd/aro/operator.go
  pkg/backend/openshiftcluster/create.go
  pkg/bootstraplogging/bootstraplogging.go
  pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
  pkg/operator/controllers/alertwebhook/alertwebhook_controller_test.go
  pkg/operator/controllers/condition.go
  pkg/operator/controllers/genevalogging/const.go
  pkg/operator/controllers/genevalogging/genevalogging.go
  pkg/operator/controllers/genevalogging/genevalogging_controller.go
  pkg/operator/controllers/internetchecker/internetchecker_controller.go
  pkg/operator/controllers/internetchecker/internetchecker_controller_test.go
  pkg/operator/controllers/pullsecret/pullsecret_controller.go
  pkg/operator/controllers/pullsecret/pullsecret_controller_test.go
  pkg/operator/deploy/deploy.go
  pkg/operator/generate.go
Labels: next-up

#936 Wait for operator to be functioning
  pkg/operator/apis/aro.openshift.io/v1alpha1/cluster_types.go
  pkg/operator/controllers/condition.go
  pkg/operator/deploy/deploy.go
Labels: next-up, priority-medium

#848 Change template configuration to pointers
  cmd/aro/deploy.go
  pkg/deploy/config.go
  pkg/deploy/config_test.go
  pkg/deploy/deploy.go
  pkg/deploy/deploy_test.go
  pkg/deploy/predeploy.go
Labels: next-up

#918 Move clients used by admin API to new adminactions
  cmd/aro/rp.go
  pkg/frontend/admin_openshiftcluster_kubernetesobjects.go
  pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go
  pkg/frontend/admin_openshiftcluster_list_test.go
  pkg/frontend/admin_openshiftcluster_mustgather.go
  pkg/frontend/admin_openshiftcluster_redeployvm.go
  pkg/frontend/admin_openshiftcluster_redeployvm_test.go
  pkg/frontend/admin_openshiftcluster_resources_list.go
  pkg/frontend/admin_openshiftcluster_resources_list_test.go
  pkg/frontend/admin_openshiftcluster_serialconsole.go
  pkg/frontend/adminactions/adminactions.go
  pkg/frontend/adminactions/generate.go
  pkg/frontend/adminactions/mustgather.go
  pkg/frontend/adminactions/resources_list.go
  pkg/frontend/adminactions/resources_list_test.go
  pkg/frontend/adminactions/serialtool.go
  pkg/frontend/asyncoperationresult_get_test.go
  pkg/frontend/asyncoperationsstatus_get_test.go
  pkg/frontend/frontend.go
  pkg/frontend/kubeactions/kubeactions.go
  pkg/frontend/openshiftcluster_delete_test.go
  pkg/frontend/openshiftcluster_get_test.go
  pkg/frontend/openshiftcluster_list_test.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/frontend/openshiftclustercredentials_post_test.go
  pkg/frontend/security_test.go
  pkg/frontend/subscriptions_put_test.go
  pkg/util/dynamichelper/dynamichelper.go
  pkg/util/dynamichelper/dynamichelper_test.go
  pkg/util/mocks/adminactions/adminactions.go
  pkg/util/ready/ready.go
Labels: priority-medium
