Repository Azure/ARO-RP, pull requests merged in 2020-12, with the labels that each got.

#1083 Invoke dynamic validator on Update
  pkg/api/validate/openshiftcluster_validatedynamic.go
  pkg/api/validate/openshiftcluster_validatedynamic_test.go
  pkg/backend/openshiftcluster/update.go
  pkg/util/subnet/subnet.go
Labels: next-up

#1196 Improve cluster creation success in Korea
  hack/cluster/cluster.go
  pkg/operator/controllers/checker/checker.go
  pkg/operator/controllers/checker/checker_controller.go
  pkg/operator/controllers/checker/internetchecker.go
  pkg/operator/controllers/checker/internetchecker_test.go
Labels: next-up

#1189 Feat/liveness prob
  cmd/aro/operator.go
  pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
  pkg/operator/deploy/bindata.go
  pkg/operator/deploy/staticresources/master/deployment.yaml
  pkg/operator/deploy/staticresources/worker/deployment.yaml
Labels: next-up

#1199 Add Cluster Service Principal enrich
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/util/clusterdata/cluster_service_principal_task.go
  pkg/util/clusterdata/cluster_service_principal_task_test.go
  pkg/util/clusterdata/clusterdata.go
Labels: next-up

#1211 Fix deployment and mirror
  .pipelines/templates/template-clean-subscription.yml
  cmd/aro/deploy.go
  cmd/aro/mirror.go
  hack/clean/clean.go
  pkg/env/core.go
  pkg/util/instancemetadata/dev.go
  pkg/util/instancemetadata/instancemetadata.go
  pkg/util/purge/purge.go
  test/e2e/setup.go
Labels: bug, next-up, priority-high

#1159 Add rbac validation to aro update
  python/az/aro/azext_aro/_rbac.py
  python/az/aro/azext_aro/custom.py
Labels: next-up

#1129 Move pkg/backend/openshiftclusters/create into cluster installation
  pkg/api/validate/openshiftcluster_validatedynamic.go
  pkg/api/validate/quota.go
  pkg/api/validate/quota_test.go
  pkg/backend/openshiftcluster.go
  pkg/backend/openshiftcluster/adminupdate.go
  pkg/backend/openshiftcluster/delete.go
  pkg/backend/openshiftcluster/generate.go
  pkg/backend/openshiftcluster/openshiftcluster.go
  pkg/backend/openshiftcluster/update.go
  pkg/backend/openshiftcluster_test.go
  pkg/cluster/acrtoken.go
  pkg/cluster/cluster.go
  pkg/cluster/deploystorage.go
  pkg/cluster/generate.go
  pkg/cluster/generateconfig.go
  pkg/cluster/install.go
  pkg/cluster/sshkeys.go
  pkg/cluster/validate.go
  pkg/util/mocks/cluster/cluster.go
Labels: next-up

#1224 Add New Audit Package
  pkg/metrics/statsd/statsd.go
  pkg/metrics/statsd/statsd_test.go
  pkg/util/instancemetadata/dev.go
  pkg/util/instancemetadata/instancemetadata.go
  pkg/util/instancemetadata/prod.go
  pkg/util/log/audit/audit.go
  pkg/util/log/audit/audit_test.go
  pkg/util/log/audit/schema.go
  pkg/util/log/log.go
  pkg/util/mocks/env/env.go
  pkg/util/mocks/instancemetadata/instancemetadata.go
Labels: next-up

#1202 Add metric helping determine cluster action after RP rollout
  pkg/monitor/cluster/clusterversions.go
  pkg/monitor/cluster/clusterversions_test.go
Labels: next-up

#1231 Return arch version to admin
  pkg/api/admin/openshiftcluster.go
Labels: next-up

#1233 Add feature gate to operator
  cmd/aro/operator.go
  pkg/operator/apis/aro.openshift.io/v1alpha1/cluster_types.go
  pkg/operator/apis/aro.openshift.io/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/controllers/checker/checker_controller.go
  pkg/operator/controllers/checker/internetchecker.go
  pkg/operator/controllers/checker/machinechecker.go
  pkg/operator/controllers/condition.go
  pkg/operator/controllers/genevalogging/genevalogging_controller.go
  pkg/operator/controllers/monitoring/monitoring_controller.go
  pkg/operator/controllers/monitoring/monitoring_controller_test.go
  pkg/operator/controllers/pullsecret/pullsecret_controller.go
  pkg/operator/controllers/rbac/rbac_controller.go
  pkg/operator/controllers/routefix/routefix_controller.go
  pkg/operator/controllers/workaround/workaround_controller.go
  pkg/operator/deploy/bindata.go
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/staticresources/aro.openshift.io_clusters.yaml
Labels: next-up

#1238 Cleans up old dimensions in node metrics
  pkg/monitor/cluster/nodeconditions.go
  pkg/monitor/cluster/nodeconditions_test.go
Labels: enhancement
