Repository Azure/ARO-RP, pull requests merged in 2020-09, with the labels that each got.

#951 Add workaround controller and systemreserved fix
  cmd/aro/operator.go
  pkg/operator/controllers/const.go
  pkg/operator/controllers/workaround/generate.go
  pkg/operator/controllers/workaround/systemreserved.go
  pkg/operator/controllers/workaround/systemreserved_test.go
  pkg/operator/controllers/workaround/workaround.go
  pkg/operator/controllers/workaround/workaround_controller.go
  pkg/operator/controllers/workaround/workaround_controller_test.go
  pkg/util/dynamichelper/generate.go
  pkg/util/mocks/azureclient/workaround/workaround.go
  pkg/util/mocks/dynamichelper/dynamichelper.go
  pkg/util/mocks/operator/controllers/workaround/workaround.go
  pkg/util/scheme/scheme.go
Labels: priority-high

#919 Add summary metric for reporting
  pkg/api/openshiftcluster.go
  pkg/monitor/cluster/arooperatorconditions.go
  pkg/monitor/cluster/cache.go
  pkg/monitor/cluster/cluster.go
  pkg/monitor/cluster/clusteroperatorconditions.go
  pkg/monitor/cluster/clusteroperatorversions.go
  pkg/monitor/cluster/clusterversionconditions.go
  pkg/monitor/cluster/clusterversions.go
  pkg/monitor/cluster/machineconfigpoolconditions.go
  pkg/monitor/cluster/nodeconditions.go
  pkg/monitor/cluster/nodeconditions_test.go
  pkg/monitor/cluster/podconditions.go
  pkg/monitor/cluster/summary.go
  pkg/monitor/cluster/summary_test.go
  pkg/monitor/worker.go
Labels: next-up, priority-high

#959 Split upgrade method
  pkg/cluster/install.go
  pkg/cluster/preUpgradeChecks.go
  pkg/cluster/preUpgradeChecks_test.go
  pkg/cluster/upgrade.go
  pkg/frontend/admin_openshiftcluster_upgrade.go
  pkg/frontend/adminactions/adminactions.go
  pkg/frontend/adminactions/upgrade.go
  pkg/frontend/adminactions/upgrade_test.go
  pkg/frontend/frontend.go
  pkg/util/mocks/adminactions/adminactions.go
Labels: next-up, priority-high

#930 Introduce xmsenum
  .sha256sum
  Makefile
  hack/build-client.sh
  pkg/api/v20200430/generate.go
  pkg/client/services/redhatopenshift/mgmt/2020-10-31-preview/redhatopenshift/enums.go
  pkg/client/services/redhatopenshift/mgmt/2020-10-31-preview/redhatopenshift/models.go
  pkg/swagger/swagger.go
  pkg/swagger/types.go
  pkg/swagger/typewalker.go
  python/client/azure/mgmt/redhatopenshift/v2020_10_31_preview/models/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2020_10_31_preview/models/_azure_red_hat_open_shift_client_enums.py
  python/client/azure/mgmt/redhatopenshift/v2020_10_31_preview/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2020_10_31_preview/models/_models_py3.py
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-10-31-preview/redhatopenshift.json
Labels: hold

#928 Add CI Pool vmss
  .pipelines/build-and-push-images.yml
  .pipelines/ci.yml
  .pipelines/clean-subscription.yml
  .pipelines/deploy-dev-env.yml
  .pipelines/e2e-loop.yml
  .pipelines/e2e-with-billing-all-regions.yml
  .pipelines/e2e-with-billing.yml
  .pipelines/e2e.yml
  .pipelines/mirror-images.yml
  .pipelines/templates/template-az-cli-login.yml
  .pipelines/templates/template-az-cli-set-context.yml
  .pipelines/templates/template-checkout.yml
  .pipelines/templates/template-clean-agent.yml
  .pipelines/templates/template-clean-e2e-db.yml
  .pipelines/templates/template-clean-e2e-deps.yml
  .pipelines/templates/template-clean-subscription.yml
  .pipelines/templates/template-deploy-azure-env.yml
  .pipelines/templates/template-deploy-e2e-db.yml
  .pipelines/templates/template-deploy-e2e-deps.yml
  .pipelines/templates/template-deploy-shared-env.yml
  .pipelines/templates/template-job-deploy-azure-env.yml
  .pipelines/templates/template-prod-e2e-steps.yml
  .pipelines/templates/template-push-images-to-acr.yml
  .pipelines/templates/template-rp-and-billing-e2e-section.yml
  .pipelines/templates/template-rp-and-billing-e2e.yml
  .pipelines/templates/template-run-rp-and-e2e.yml
  .pipelines/templates/template-setup-azure-tools.yml
  .pipelines/templates/template-setup-golang-env.yml
  .pipelines/vars.yml
  Makefile
  deploy/env-development.json
  deploy/rp-development-predeploy.json
  docs/prepare-a-shared-rp-development-environment.md
  hack/devtools/deploy-shared-env.sh
  hack/devtools/setup-azure-tools.sh
  hack/e2e/run-rp-and-e2e.sh
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources.go
  pkg/deploy/generator/templates.go
Labels: priority-high

#859 Add pagination to admin cluster list API
  pkg/database/openshiftclusters.go
  pkg/frontend/admin_openshiftcluster_kubernetesobjects.go
  pkg/frontend/admin_openshiftcluster_list.go
  pkg/frontend/admin_openshiftcluster_list_test.go
  pkg/frontend/admin_openshiftcluster_resources_list.go
  pkg/frontend/frontend.go
  pkg/frontend/frontend_test.go
  pkg/frontend/openshiftcluster_list.go
  pkg/util/mocks/database/database.go
  test/e2e/adminapi_cluster_list.go
Labels: next-up, priority-medium

#987 Rollback fixpullsecret to enable operator deployment
  pkg/cluster/fixpullsecret.go
  pkg/cluster/fixpullsecret_test.go
  pkg/cluster/install.go
Labels: bug, priority-high
