Repository Azure/ARO-RP, pull requests merged in 2020-11, with the labels that each got.

#1102 Adds node name into pod metrics
  pkg/monitor/cluster/nodeconditions.go
  pkg/monitor/cluster/nodeconditions_test.go
  pkg/monitor/cluster/podconditions.go
  pkg/monitor/cluster/podconditions_test.go
Labels: release-blocker

#1105 Propagate cvo error to geneva
  pkg/frontend/adminactions/upgrade.go
  pkg/frontend/adminactions/upgrade_test.go
Labels: next-up

#1113 Add baselineversion metric
  pkg/monitor/cluster/clusterversions.go
  pkg/monitor/cluster/clusterversions_test.go
Labels: next-up

#1119 Save the version of the RP that creates a cluster
  pkg/api/openshiftcluster.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
Labels: next-up

#1121 add CreatedBy to admin API
  pkg/api/admin/openshiftcluster.go
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/admin/openshiftcluster_validatestatic_test.go
  pkg/api/openshiftcluster.go
  pkg/cluster/install.go
  pkg/cluster/install_test.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
Labels: next-up

#1063 Add tests for backend/
  pkg/backend/backend.go
  pkg/backend/openshiftcluster.go
  pkg/backend/openshiftcluster/adminupdate.go
  pkg/backend/openshiftcluster/create.go
  pkg/backend/openshiftcluster/delete.go
  pkg/backend/openshiftcluster/generate.go
  pkg/backend/openshiftcluster/openshiftcluster.go
  pkg/backend/openshiftcluster/update.go
  pkg/backend/openshiftcluster_test.go
  pkg/backend/subscriptions.go
  pkg/util/mocks/openshiftcluster/openshiftcluster.go
Labels: next-up

#1131 Discovery cache hack
  pkg/util/dynamichelper/discovery/cache_fallback_discovery_client.go
  pkg/util/dynamichelper/dynamichelper.go
Labels: next-up, ready-for-review

#1140 mend fixupNSGs to support 4.4 and 4.5 clusters in PROD
  pkg/util/cluster/cluster.go
Labels: next-up

#1125 Update Development RP Cluster Deploy Docs
  docs/deploy-development-rp.md
  hack/ssh-agent.sh
Labels: next-up

#1116 Sync tooling image into ACR
  .pipelines/mirror-images.yml
  cmd/aro/mirror.go
Labels: next-up

#1123 Enable boot diagnostics on RP nodes
  deploy/config.yaml.example
  deploy/generate.go
  deploy/rp-production-parameters.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/config.go
  pkg/deploy/config_test.go
  pkg/deploy/generator/resources.go
  pkg/deploy/generator/templates.go
Labels: next-up

#1139 Clean-Up Resources on Dev Cluster Delete
  pkg/util/azureclient/mgmt/authorization/roleassignments.go
  pkg/util/azureclient/mgmt/authorization/roleassignments_addons.go
  pkg/util/azureclient/mgmt/features/deployments_addons.go
  pkg/util/azureclient/mgmt/network/routetable.go
  pkg/util/azureclient/mgmt/network/routetable_addons.go
  pkg/util/azureclient/mgmt/network/subnets_addons.go
  pkg/util/cluster/cluster.go
  pkg/util/mocks/azureclient/mgmt/authorization/authorization.go
  pkg/util/mocks/azureclient/mgmt/features/features.go
  pkg/util/mocks/azureclient/mgmt/network/network.go
Labels: next-up

#1101 Initial refactoring to enable Azure cloud environment awareness
  cmd/aro/mirror.go
  deploy/rp-production.json
  pkg/api/validate/openshiftcluster_validatedynamic.go
  pkg/backend/openshiftcluster/create.go
  pkg/backend/openshiftcluster/openshiftcluster.go
  pkg/bootstraplogging/bootstraplogging.go
  pkg/cluster/blobservice.go
  pkg/cluster/cluster.go
  pkg/cluster/deploystorage.go
  pkg/database/database.go
  pkg/deploy/bindata.go
  pkg/env/core.go
  pkg/env/dev.go
  pkg/env/env.go
  pkg/env/prod.go
  pkg/frontend/adminactions/adminactions.go
  pkg/frontend/adminactions/serialtool.go
  pkg/operator/apis/aro.openshift.io/v1alpha1/cluster_types.go
  pkg/operator/controllers/genevalogging/genevalogging.go
  pkg/operator/controllers/routefix/routefix.go
  pkg/operator/deploy/bindata.go
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/staticresources/aro.openshift.io_clusters.yaml
  pkg/util/acrtoken/acrtoken.go
  pkg/util/billing/billing.go
  pkg/util/instancemetadata/dev.go
  pkg/util/instancemetadata/instancemetadata.go
  pkg/util/instancemetadata/prod.go
  pkg/util/instancemetadata/prod_test.go
  pkg/util/keyvault/find.go
  pkg/util/mocks/env/env.go
  pkg/util/version/const.go
Labels: next-up, ready-for-review

#1183 remove certificate policy upgrade code, all certs are upgraded
  pkg/cluster/install.go
  pkg/cluster/tls.go
  pkg/util/azureclient/keyvault/base.go
  pkg/util/keyvault/keyvault.go
  pkg/util/mocks/azureclient/keyvault/keyvault.go
  pkg/util/mocks/keyvault/keyvault.go
Labels: next-up, ready-for-review

#1173 Update go-cosmosdb
  go.mod
  go.sum
  pkg/database/cosmosdb/zz_generated_cosmosdb.go
  pkg/database/cosmosdb/zz_generated_database.go
  pkg/database/database.go
  vendor/github.com/jim-minter/go-cosmosdb/pkg/gencosmosdb/bindata.go
  vendor/modules.txt
Labels: next-up

#1174 More RP startup refactoring
  cmd/aro/monitor.go
  cmd/aro/rp.go
  deploy/rp-development-predeploy.json
  deploy/rp-production-parameters.json
  deploy/rp-production-predeploy.json
  deploy/rp-production.json
  docs/authorizers.md
  docs/deploy-development-rp.md
  docs/prepare-a-shared-rp-development-environment.md
  hack/db/db.go
  hack/devtools/deploy-shared-env.sh
  hack/e2e/run-rp-and-e2e.sh
  pkg/api/validate/openshiftcluster_validatedynamic_test.go
  pkg/backend/openshiftcluster/openshiftcluster.go
  pkg/cluster/cluster.go
  pkg/cluster/delete.go
  pkg/cluster/tls.go
  pkg/database/database.go
  pkg/database/extensions_test.go
  pkg/deploy/bindata.go
  pkg/deploy/config.go
  pkg/deploy/config_test.go
  pkg/deploy/deploy.go
  pkg/deploy/generator/const.go
  pkg/deploy/generator/resources.go
  pkg/deploy/generator/templates.go
  pkg/env/core.go
  pkg/env/env.go
  pkg/env/prod.go
  pkg/frontend/frontend.go
  pkg/frontend/security_test.go
  pkg/frontend/shared_test.go
  pkg/util/azureclient/mgmt/dns/zones.go
  pkg/util/azureclient/mgmt/dns/zones_addons.go
  pkg/util/azureclient/mgmt/documentdb/databaseaccounts.go
  pkg/util/azureclient/mgmt/documentdb/generate.go
  pkg/util/azureclient/mgmt/insights/generate.go
  pkg/util/azureclient/mgmt/insights/metricalerts.go
  pkg/util/azureclient/mgmt/keyvault/generate.go
  pkg/util/azureclient/mgmt/keyvault/vaults.go
  pkg/util/azureclient/mgmt/keyvault/vaults_addons.go
  pkg/util/azureclient/mgmt/msi/generate.go
  pkg/util/azureclient/mgmt/privatedns/generate.go
  pkg/util/azureclient/mgmt/redhatopenshift/generate.go
  pkg/util/azureclient/mgmt/storage/accounts.go
  pkg/util/azureclient/mgmt/storage/generate.go
  pkg/util/encryption/xchacha20poly1305.go
  pkg/util/encryption/xchacha20poly1305_test.go
  pkg/util/keyvault/find.go
  pkg/util/keyvault/uri.go
  pkg/util/mocks/azureclient/mgmt/dns/dns.go
  pkg/util/mocks/azureclient/mgmt/documentdb/documentdb.go
  pkg/util/mocks/azureclient/mgmt/insights/insights.go
  pkg/util/mocks/azureclient/mgmt/keyvault/keyvault.go
  pkg/util/mocks/azureclient/mgmt/mock_redhatopenshift/redhatopenshift.go
  pkg/util/mocks/azureclient/mgmt/msi/msi.go
  pkg/util/mocks/azureclient/mgmt/privatedns/privatedns.go
  pkg/util/mocks/azureclient/mgmt/storage/storage.go
  pkg/util/mocks/env/env.go
Labels: next-up, ready-for-review

#1126 Revert "Revert "Fix permissions on cluster deletion in az cli""
  python/az/aro/azext_aro/_rbac.py
  python/az/aro/azext_aro/custom.py
Labels: next-up, ready-for-review

#1112 Run e2e tests from the image
  .pipelines/deploy-azure-env.yml
  .pipelines/e2e-with-billing.yml
  .pipelines/e2e.yml
  .pipelines/int-release.yml
  .pipelines/prod-release.yml
  .pipelines/templates/template-az-cli-set-context.yml
  .pipelines/templates/template-clean-e2e-db.yml
  .pipelines/templates/template-clean-subscription.yml
  .pipelines/templates/template-deploy-azure-env.yml
  .pipelines/templates/template-deploy-e2e-db.yml
  .pipelines/templates/template-deploy-shared-env.yml
  .pipelines/templates/template-job-deploy-azure-env.yml
  .pipelines/templates/template-prod-e2e-steps.yml
  .pipelines/templates/template-push-images-to-acr.yml
  .pipelines/templates/template-rp-and-billing-e2e-section.yml
  .pipelines/templates/template-rp-and-billing-e2e.yml
  .pipelines/templates/template-run-rp-and-e2e.yml
  docs/prepare-a-shared-rp-development-environment.md
  docs/testing.md
  hack/e2e/run-rp-and-e2e.sh
  pkg/util/cluster/cluster.go
  test/e2e/setup.go
Labels: next-up, ready-for-review

#1145 Add monitoring controller to configure prometheus to persist data
  README.md
  cmd/aro/operator.go
  pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
  pkg/operator/controllers/checker/checker_controller.go
  pkg/operator/controllers/const.go
  pkg/operator/controllers/genevalogging/genevalogging_controller.go
  pkg/operator/controllers/monitoring/monitoring_controller.go
  pkg/operator/controllers/monitoring/monitoring_controller_test.go
  pkg/operator/controllers/pullsecret/pullsecret_controller.go
  pkg/operator/controllers/workaround/workaround_controller.go
  test/e2e/operator.go
Labels: next-up

#1188 bump versions
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/monitor/cluster/clusterversions_test.go
  pkg/util/dynamichelper/discovery/bindata.go
  pkg/util/dynamichelper/discovery/cache/assets_version
  pkg/util/version/const.go
Labels: next-up

#1192 cloud awareness in RP deployment resources
  deploy/rp-production-parameters.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/config.go
  pkg/deploy/config_test.go
  pkg/deploy/generator/resources.go
  pkg/deploy/generator/templates.go
Labels: next-up

#1193 cloud awareness in cluster creation
  pkg/cluster/deployresources.go
  pkg/cluster/deployresources_resources.go
Labels: next-up

#1181 Make workers count unbound
  .sha256sum
  pkg/api/v20191231preview/openshiftcluster.go
  pkg/api/v20191231preview/openshiftcluster_validatestatic.go
  pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20191231preview/openshiftclustercredentials.go
  pkg/api/v20200430/openshiftcluster.go
  pkg/api/v20200430/openshiftcluster_validatestatic.go
  pkg/api/v20200430/openshiftcluster_validatestatic_test.go
  pkg/api/v20200430/openshiftclustercredentials.go
  pkg/api/v20201031preview/openshiftcluster.go
  pkg/api/v20201031preview/openshiftcluster_validatestatic.go
  pkg/api/v20201031preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20201031preview/openshiftclustercredentials.go
  pkg/client/services/redhatopenshift/mgmt/2020-04-30/redhatopenshift/models.go
  pkg/client/services/redhatopenshift/mgmt/2020-10-31-preview/redhatopenshift/models.go
  python/client/azure/mgmt/redhatopenshift/v2020_04_30/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2020_04_30/models/_models_py3.py
  python/client/azure/mgmt/redhatopenshift/v2020_10_31_preview/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2020_10_31_preview/models/_models_py3.py
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-04-30/redhatopenshift.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-10-31-preview/redhatopenshift.json
Labels: next-up

#1190 remove ciDeployTooling parameter
  deploy/env-development.json
  hack/devtools/deploy-shared-env.sh
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources.go
  pkg/deploy/generator/templates.go
Labels: next-up
