Repository Azure/ARO-RP, pull requests merged in 2020-10, with the labels that each got.

#1034 pkg/cluster cleanup
  pkg/cluster/arm.go
  pkg/cluster/arooperator.go
  pkg/cluster/billing.go
  pkg/cluster/billing_test.go
  pkg/cluster/blobservice.go
  pkg/cluster/cluster.go
  pkg/cluster/condition.go
  pkg/cluster/condition_test.go
  pkg/cluster/consolebranding.go
  pkg/cluster/consolebranding_test.go
  pkg/cluster/deployresources.go
  pkg/cluster/deploystorage.go
  pkg/cluster/deploystorage_test.go
  pkg/cluster/disableupdates.go
  pkg/cluster/disableupdates_test.go
  pkg/cluster/fixlbprobeconfig.go
  pkg/cluster/fixlbprobeconfig_test.go
  pkg/cluster/fixnsg.go
  pkg/cluster/fixnsg_test.go
  pkg/cluster/fixpullsecret.go
  pkg/cluster/fixpullsecret_test.go
  pkg/cluster/gatherlogs.go
  pkg/cluster/graph.go
  pkg/cluster/install.go
  pkg/cluster/install_test.go
  pkg/cluster/ipaddresses.go
  pkg/cluster/kubeconfig.go
  pkg/cluster/kubeconfig_test.go
  pkg/cluster/loadbalancer.go
  pkg/cluster/nsg.go
  pkg/cluster/removebootstrap.go
  pkg/cluster/routefix.go
  pkg/cluster/samples.go
  pkg/cluster/start_vms.go
  pkg/cluster/start_vms_test.go
  pkg/cluster/tls.go
Labels: priority-low

#1059 Add ability to tag resourceGroups
  pkg/cluster/deploystorage.go
  pkg/cluster/deploystorage_test.go
Labels: ready-for-review

#1092 Remove must-gather
  pkg/frontend/admin_openshiftcluster_mustgather.go
  pkg/frontend/adminactions/adminactions.go
  pkg/frontend/adminactions/mustgather.go
  pkg/frontend/frontend.go
  pkg/util/mocks/adminactions/adminactions.go
  pkg/util/version/const.go
  pkg/util/version/stream.go
  test/e2e/adminapi_mustgather.go
Labels: ready-for-review

#1064 rp,operator version metrics
  pkg/monitor/cluster/cache.go
  pkg/monitor/cluster/cluster.go
  pkg/monitor/cluster/clusterversions.go
  pkg/monitor/cluster/clusterversions_test.go
  pkg/monitor/cluster/deploymentstatuses.go
  pkg/operator/deploy/deploy.go
Labels: ready-for-review

#977 Refactor SDK to be used in CI
  .pipelines/e2e.yml
  .pipelines/templates/template-clean-e2e-deps.yml
  .pipelines/templates/template-deploy-e2e-deps.yml
  .pipelines/templates/template-prod-e2e-steps.yml
  .pipelines/templates/template-run-rp-and-e2e.yml
  Makefile
  deploy/cluster-predeploy.json
  deploy/rp-production-global.json
  deploy/rp-production.json
  docs/deploy-development-rp.md
  docs/testing.md
  hack/cluster/cluster.go
  hack/e2e/run-rp-and-e2e.sh
  hack/kubeadminkubeconfig/get.go
  hack/kubeadminkubeconfig/kubeconfig.go
  pkg/cluster/deploystorage.go
  pkg/deploy/bindata.go
  pkg/deploy/generator/const.go
  pkg/deploy/generator/generators.go
  pkg/deploy/generator/resources.go
  pkg/deploy/generator/resources_cluster.go
  pkg/deploy/generator/templates.go
  pkg/util/azureclient/graphrbac/applications.go
  pkg/util/azureclient/graphrbac/applications_addons.go
  pkg/util/azureclient/graphrbac/generate.go
  pkg/util/azureclient/graphrbac/serviceprincipals.go
  pkg/util/azureclient/graphrbac/serviceprincipals_addons.go
  pkg/util/azureclient/mgmt/redhatopenshift/openshiftclusters_addons.go
  pkg/util/cluster/aad.go
  pkg/util/cluster/cluster.go
  pkg/util/instancemetadata/dev.go
  pkg/util/instancemetadata/instancemetadata.go
  pkg/util/mocks/azureclient/graphrbac/graphrbac.go
  pkg/util/mocks/azureclient/mgmt/mock_redhatopenshift/redhatopenshift.go
  pkg/util/rbac/rbac.go
  python/az/aro/azext_aro/custom.py
  test/e2e/adminapi_cluster_list.go
  test/e2e/adminapi_kubernetesobjects.go
  test/e2e/adminapi_redeployvm.go
  test/e2e/adminapi_resources.go
  test/e2e/list.go
  test/e2e/scalenodes.go
  test/e2e/setup.go
  test/e2e/update.go
  test/util/kubeadminkubeconfig/kubeconfig.go
  test/util/kubeadminkubeconfig/kubetoken.go
  test/util/kubeadminkubeconfig/kubetoken_test.go
Labels: ready-for-review, release-blocker

#1104 Add hardEviction
  pkg/operator/controllers/workaround/systemreserved.go
  pkg/operator/controllers/workaround/systemreserved_test.go
  pkg/util/dynamichelper/dynamichelper.go
  pkg/util/dynamichelper/dynamichelper_test.go
Labels: ready-for-review, release-blocker

#1087 adding a new metric called arooperator.heartbeat
  pkg/monitor/cluster/arooperatorheartbeat.go
  pkg/monitor/cluster/arooperatorheartbeat_test.go
  pkg/monitor/cluster/cluster.go
Labels: release-blocker
