Repository Azure/ARO-RP, pull requests merged in 2020-06, with the labels that each got.

#709 [docs]Add contributing section to az aro python development
  docs/az-aro-python-development.md
Labels: next-up

#693 Add the ability to delete resource groups when vnet is in different resource group
  .pipelines/clean-e2e.yml
  .pipelines/clean-subscription.yml
  .pipelines/templates/template-clean-subscription.yml
  hack/clean/clean.go
  hack/cleane2e/cleane2e.go
  pkg/util/purge/purge.go
  pkg/util/purge/resourcegroups.go
Labels: next-up

#828 Updates docs on testing custom builds in ARO
  docs/custom-payload-testing.md
Labels: documentation

#728 Attempt to update routetable permissions
  hack/e2e/run-rp-and-e2e.sh
  python/az/aro/azext_aro/_rbac.py
  python/az/aro/azext_aro/custom.py
Labels: next-up

#710 changed the default vmImage: ubuntu-latest to agent pools.
  .pipelines/build-and-push-images.yml
  .pipelines/ci.yml
  .pipelines/clean-e2e.yml
  .pipelines/deploy-dev-env.yml
  .pipelines/e2e-loop.yml
  .pipelines/templates/template-job-deploy-azure-env.yml
Labels: next-up

#829 Az command changes in documentation and in E2E scripts
  docs/deploy-development-rp.md
  docs/prepare-a-shared-rp-development-environment.md
  hack/devtools/deploy-shared-env.sh
  hack/e2e/run-rp-and-e2e.sh
Labels: documentation, priority-low, size-small

#849 Move pull request template to exist at the root of the .github directory
  .github/PULL_REQUEST_TEMPLATE.md
Labels: priority-low, ready-for-review, size-small
