Repository Azure/ARO-RP, pull requests merged in 2021-12, with the labels that each got.

#1645 Rotate the encryption secrets on deploy
  pkg/deploy/devconfig.go
  pkg/deploy/predeploy.go
  pkg/util/encryption/aescbc_test.go
  test/database/aead.go
Labels: priority-medium, size-large, ready-for-review, next-release

#1870 Fix sre portal
  pkg/portal/bindata.go
  pkg/portal/portal.go
  portal/dist/main.js
  portal/src/index.js
Labels: bug, priority-high, release-blocker

#1880 Add subscription of keyvault to e2e template
  .pipelines/e2e.yml
Labels: ready-for-review, flake

#1877 Update ARM authentication metadata endpoint for public cloud
  pkg/util/clientauthorizer/arm.go
  pkg/util/clientauthorizer/arm_test.go
Labels: ready-for-review, flake

#1860 Update docs and required dev-config params
  docs/deploy-full-rp-service-in-dev.md
  pkg/deploy/devconfig.go
Labels: size-small, ready-for-review

#1798 Wait for machine deletion after node scaling tests
  test/e2e/operator.go
  test/e2e/scalenodes.go
Labels: ready-for-review, flake

#1886 Make keyvault client cloud aware
  pkg/util/azureclient/mgmt/keyvault/vaults.go
  pkg/util/cluster/cluster.go
Labels: bug, next-up

#1850 Feat: Add Restart Counter Metric for System Components
  pkg/monitor/cluster/podconditions.go
  pkg/monitor/cluster/podconditions_test.go
  pkg/util/namespace/namespace.go
  pkg/util/namespace/namespace_test.go
Labels: LGTM

#1873 Add a test for NodeDrainer reconciler (node controller)
  pkg/operator/controllers/node/node_controller_test.go
Labels: priority-low, ready-for-review
