Repository Azure/ARO-RP, pull requests merged in 2021-11, with the labels that each got.

#1829 Fixing Python CI
  python/az/aro/azext_aro/_aad.py
  python/az/aro/azext_aro/_validators.py
  python/az/aro/azext_aro/custom.py
Labels: next-up, ready-for-review

#1832 Pull Secret Unmarshalling Bugfix
  pkg/util/pullsecret/pullsecret.go
  pkg/util/pullsecret/pullsecret_test.go
Labels: bug

#1682 Implement the REST portions of Admin Portal 2.0
  cmd/aro/portal.go
  docs/portal-ui.md
  hack/aead/aead.go
  hack/fakecluster/fakecluster.go
  pkg/portal/cluster.go
  pkg/portal/cluster/bindata.go
  pkg/portal/cluster/clusteroperators.go
  pkg/portal/cluster/clusteroperators_test.go
  pkg/portal/cluster/fetcher.go
  pkg/portal/cluster/generate.go
  pkg/portal/cluster/testdocs/clusteroperator.json
  pkg/portal/cluster_info.go
  pkg/portal/cluster_test.go
  pkg/portal/http_test.go
  pkg/portal/info.go
  pkg/portal/info_test.go
  pkg/portal/portal.go
  pkg/portal/security_test.go
Labels: ready-for-review, next-release

#1827 Fix race condition in the gateway doc deletion
  pkg/cluster/delete.go
  pkg/cluster/ipaddresses.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/operator/deploy/deploy.go
Labels: priority-high, hold, release-blocker, next-release

#1831 Populate Missing Gateway Record Log with LinkID
  pkg/gateway/linkid.go
Labels: priority-medium, size-small, ready-for-review

#1817 fixing user admin kubeconfig api-int to api on PUCM
  pkg/cluster/fixuserkubeconfig.go
  pkg/cluster/kubeconfig.go
  pkg/cluster/kubeconfig_test.go
Labels: bug, ready-for-review, next-release

#1835 bump mdm/mdsd to october releases
  Makefile
  deploy/gateway-production.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/util/version/const.go
Labels: priority-high, size-small, next-release

#1731 Docs and make file nits
  Dockerfile.fluentbit
  Makefile
  docs/deploy-full-rp-service-in-dev.md
Labels: documentation, priority-medium, size-medium, ready-for-review, LGTM

#1675 Introduce a "task" selection option to AdminUpdate for running just the ARO Operator update steps
  pkg/api/admin/openshiftcluster.go
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/admin/openshiftcluster_validatestatic.go
  pkg/api/admin/openshiftcluster_validatestatic_test.go
  pkg/api/defaults.go
  pkg/api/openshiftcluster.go
  pkg/backend/openshiftcluster.go
  pkg/backend/openshiftcluster_test.go
  pkg/cluster/adminupdate_test.go
  pkg/cluster/install.go
  pkg/database/openshiftclusters.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
Labels: priority-medium, size-medium, ready-for-review, operator

#1836 Workaround mdsd bug
  deploy/gateway-production.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
Labels: priority-high, size-small, next-release

#1844 add clusterresourcegroupId to fix nsg regression
  pkg/operator/deploy/deploy.go
Labels: bug, size-small

#1801 Move health probe to manager
  cmd/aro/operator.go
Labels: priority-low, size-small, ready-for-review, operator

#1849 update config version, abstract gateway devconfig to version const.go
  pkg/deploy/devconfig.go
  pkg/util/version/const.go
Labels: size-small, ready-for-review

#1852 For anyone that does or might in the future use Goland
  .gitignore
Labels: priority-low, size-small, LGTM

#1824 Don't reconcile the DNSMasq Stuffs if It's Disabled
  pkg/operator/controllers/dnsmasq/machineconfig_controller.go
  pkg/operator/controllers/dnsmasq/machineconfigpool_controller.go
Labels: bug, priority-high, next-release

#1855 Fix GroupKind argument to EnsureDelete
  pkg/operator/controllers/workaround/systemreserved.go
Labels: bug, priority-high, size-small, ready-for-review

#1857 add tags aro to mirror step docs as required to compile installer
  docs/deploy-full-rp-service-in-dev.md
Labels: documentation, size-small
