Repository Azure/ARO-RP, pull requests merged in 2021-08, with the labels that each got.

#1517 Bump ugorji library and start using -tags codec.safe
  Makefile
  go.mod
  go.sum
  pkg/cluster/fixmcsuserdata_test.go
  vendor/github.com/ugorji/go/codec/README.md
  vendor/github.com/ugorji/go/codec/binc.go
  vendor/github.com/ugorji/go/codec/build.sh
  vendor/github.com/ugorji/go/codec/cbor.go
  vendor/github.com/ugorji/go/codec/codecgen.go
  vendor/github.com/ugorji/go/codec/decimal.go
  vendor/github.com/ugorji/go/codec/decode.go
  vendor/github.com/ugorji/go/codec/doc.go
  vendor/github.com/ugorji/go/codec/encode.go
  vendor/github.com/ugorji/go/codec/fast-path.generated.go
  vendor/github.com/ugorji/go/codec/fast-path.go.tmpl
  vendor/github.com/ugorji/go/codec/fast-path.not.go
  vendor/github.com/ugorji/go/codec/gen-dec-map.go.tmpl
  vendor/github.com/ugorji/go/codec/gen-helper.generated.go
  vendor/github.com/ugorji/go/codec/gen-helper.go.tmpl
  vendor/github.com/ugorji/go/codec/gen.generated.go
  vendor/github.com/ugorji/go/codec/gen.go
  vendor/github.com/ugorji/go/codec/go.mod
  vendor/github.com/ugorji/go/codec/goversion_arrayof_gte_go15.go
  vendor/github.com/ugorji/go/codec/goversion_arrayof_lt_go15.go
  vendor/github.com/ugorji/go/codec/goversion_fmt_time_gte_go15.go
  vendor/github.com/ugorji/go/codec/goversion_fmt_time_lt_go15.go
  vendor/github.com/ugorji/go/codec/goversion_makemap_lt_go110.go
  vendor/github.com/ugorji/go/codec/goversion_makemap_not_unsafe_gte_go110.go
  vendor/github.com/ugorji/go/codec/goversion_makemap_unsafe_gte_go110.go
  vendor/github.com/ugorji/go/codec/goversion_maprange_gte_go112.go
  vendor/github.com/ugorji/go/codec/goversion_maprange_lt_go112.go
  vendor/github.com/ugorji/go/codec/goversion_unexportedembeddedptr_gte_go110.go
  vendor/github.com/ugorji/go/codec/goversion_unexportedembeddedptr_lt_go110.go
  vendor/github.com/ugorji/go/codec/goversion_unsupported_lt_go14.go
  vendor/github.com/ugorji/go/codec/goversion_vendor_eq_go15.go
  vendor/github.com/ugorji/go/codec/goversion_vendor_eq_go16.go
  vendor/github.com/ugorji/go/codec/goversion_vendor_gte_go17.go
  vendor/github.com/ugorji/go/codec/goversion_vendor_lt_go15.go
  vendor/github.com/ugorji/go/codec/helper.go
  vendor/github.com/ugorji/go/codec/helper_not_unsafe.go
  vendor/github.com/ugorji/go/codec/helper_not_unsafe_not_gc.go
  vendor/github.com/ugorji/go/codec/helper_unsafe.go
  vendor/github.com/ugorji/go/codec/helper_unsafe_compiler_gc.go
  vendor/github.com/ugorji/go/codec/helper_unsafe_compiler_not_gc.go
  vendor/github.com/ugorji/go/codec/json.go
  vendor/github.com/ugorji/go/codec/mammoth-test.go.tmpl
  vendor/github.com/ugorji/go/codec/mammoth2-test.go.tmpl
  vendor/github.com/ugorji/go/codec/msgpack.go
  vendor/github.com/ugorji/go/codec/reader.go
  vendor/github.com/ugorji/go/codec/rpc.go
  vendor/github.com/ugorji/go/codec/simple.go
  vendor/github.com/ugorji/go/codec/sort-slice.generated.go
  vendor/github.com/ugorji/go/codec/sort-slice.go.tmpl
  vendor/github.com/ugorji/go/codec/test.py
  vendor/github.com/ugorji/go/codec/writer.go
  vendor/modules.txt
Labels: LGTM, dependencies, next-up, priority-high, ready-for-review

#1616 Add dbTokenClientID to RP Config
  cmd/aro/dbtoken.go
  deploy/rp-production-parameters.json
  deploy/rp-production.json
  docs/prepare-a-shared-rp-development-environment.md
  pkg/deploy/bindata.go
  pkg/deploy/config.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/templates_rp.go
Labels: LGTM, priority-medium, ready-for-review, size-small

#1627 Makes default StorageClass to use disk encryption set, if provided
  pkg/cluster/install.go
  pkg/cluster/storageclass.go
  pkg/cluster/storageclass_test.go
Labels: LGTM, priority-medium, ready-for-review, size-small

#1564 fix/ change purger logic
  hack/clean/clean.go
  pkg/cluster/deploystorage.go
Labels: LGTM, priority-medium, ready-for-review, size-small

#1652 Add norway west for tests
  .pipelines/e2e-with-billing-all-regions.yml
Labels: LGTM, priority-high, ready-for-review, size-small

#1656 Revendor installer
  go.mod
  go.sum
  pkg/api/openshiftcluster.go
  pkg/cluster/deploystorage.go
  pkg/cluster/sshkeys.go
  pkg/operator/controllers/dnsmasq/cluster_controller.go
  vendor/github.com/openshift/installer/data/assets_vfsdata.go
  vendor/github.com/openshift/installer/pkg/aro/dnsmasq/dnsmasq.go
  vendor/github.com/openshift/installer/pkg/asset/cluster/tfvars.go
  vendor/github.com/openshift/installer/pkg/asset/ignition/bootstrap/bootstrap.go
  vendor/github.com/openshift/installer/pkg/asset/installconfig/aws/permissions.go
  vendor/github.com/openshift/installer/pkg/asset/installconfig/aws/validation.go
  vendor/github.com/openshift/installer/pkg/asset/installconfig/openstack/validate.go
  vendor/github.com/openshift/installer/pkg/asset/installconfig/openstack/validation/machinepool.go
  vendor/github.com/openshift/installer/pkg/asset/installconfig/openstack/validation/platform.go
  vendor/github.com/openshift/installer/pkg/asset/machines/master.go
  vendor/github.com/openshift/installer/pkg/asset/machines/worker.go
  vendor/github.com/openshift/installer/pkg/asset/manifests/openshift.go
  vendor/github.com/openshift/installer/pkg/asset/manifests/operators.go
  vendor/github.com/openshift/installer/pkg/asset/manifests/template.go
  vendor/github.com/openshift/installer/pkg/asset/targets/targets.go
  vendor/github.com/openshift/installer/pkg/asset/templates/content/bootkube/aro-dns-config.go
  vendor/github.com/openshift/installer/pkg/asset/templates/content/bootkube/aro-imageregistry-config.go
  vendor/github.com/openshift/installer/pkg/asset/templates/content/bootkube/aro-imageregistry.go
  vendor/github.com/openshift/installer/pkg/tfvars/openstack/bootstrap_ignition.go
  vendor/github.com/openshift/installer/pkg/tfvars/openstack/openstack.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/types.go
Labels: priority-high, size-small, ready-for-review, LGTM

#1651 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: priority-low, size-small, ready-for-review

#1650 save ocp versions to storage account
  deploy/rp-production-global.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/upgrade.go
  pkg/frontend/adminactions/upgrade.go
  pkg/monitor/cluster/clusterversions.go
  pkg/util/version/const.go
  pkg/util/version/stream.go
  pkg/util/version/stream_test.go
  pkg/util/version/version.go
Labels: priority-medium, size-small, ready-for-review

#1666 Introduce pipeline chaining
  .pipelines/e2e.yml
Labels: priority-medium, size-small, ready-for-review, LGTM

#1667 Escape periods in regex expression
  hack/validate-imports/validate-imports.go
Labels: priority-low, size-small, ready-for-review, LGTM

#1648 Add unit test for Node controller
  pkg/operator/controllers/node/const.go
  pkg/operator/controllers/node/node_controller.go
  pkg/operator/controllers/node/node_controller_test.go
Labels: priority-low, size-small, ready-for-review

#1679 Cleanup azureclient
  pkg/deploy/deploy.go
  pkg/util/azureclient/mgmt/compute/disks_addons.go
  pkg/util/azureclient/mgmt/compute/virtualmachinesscalesets_addons.go
  pkg/util/azureclient/mgmt/features/deployments_addons.go
  pkg/util/azureclient/mgmt/features/features.go
  pkg/util/azureclient/mgmt/features/generate.go
  pkg/util/azureclient/mgmt/features/providers.go
  pkg/util/azureclient/mgmt/features/resourcegroups_addons.go
  pkg/util/azureclient/mgmt/network/interfaces_addons.go
  pkg/util/azureclient/mgmt/network/loadbalancers_addons.go
  pkg/util/azureclient/mgmt/network/privateendpoints_addons.go
  pkg/util/azureclient/mgmt/network/publicipaddresses.go
  pkg/util/azureclient/mgmt/network/publicipaddresses_addons.go
  pkg/util/azureclient/mgmt/network/routetable_addons.go
  pkg/util/azureclient/mgmt/network/securitygroups_addons.go
  pkg/util/azureclient/mgmt/network/subnets_addons.go
  pkg/util/azureclient/mgmt/network/virtualnetworkpeerings.go
  pkg/util/azureclient/mgmt/network/virtualnetworkpeerings_addons.go
  pkg/util/azureclient/mgmt/network/virtualnetworks.go
  pkg/util/azureclient/mgmt/network/virtualnetworks_addons.go
  pkg/util/azureclient/mgmt/storage/accounts.go
  pkg/util/azureclient/mgmt/storage/accounts_addons.go
  pkg/util/mocks/azureclient/mgmt/features/features.go
  pkg/util/mocks/azureclient/mgmt/network/network.go
Labels: priority-medium, size-medium, ready-for-review

#1685 Trigger CI with a tag
  .pipelines/ci.yml
Labels: priority-medium, size-small, ready-for-review, LGTM

#1683 update keyvault api version to 2019-09-01
  deploy/rp-development-predeploy.json
  deploy/rp-production-predeploy.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_rp.go
  pkg/util/azureclient/apiversions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2016-10-01/keyvault/enums.go
  vendor/github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2019-09-01/keyvault/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2019-09-01/keyvault/_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2019-09-01/keyvault/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2019-09-01/keyvault/enums.go
  vendor/github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2019-09-01/keyvault/keys.go
  vendor/github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2019-09-01/keyvault/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2019-09-01/keyvault/operations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2019-09-01/keyvault/privateendpointconnections.go
  vendor/github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2019-09-01/keyvault/privatelinkresources.go
  vendor/github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2019-09-01/keyvault/vaults.go
  vendor/github.com/Azure/azure-sdk-for-go/services/keyvault/mgmt/2019-09-01/keyvault/version.go
  vendor/modules.txt
Labels: priority-medium, size-medium, ready-for-review, dependencies, LGTM

#1672 Add subscription feature MTU3900
  pkg/api/featureflags.go
  pkg/cluster/deploystorage.go
  pkg/cluster/overridemtu.go
Labels: priority-high, size-medium, next-up, ready-for-review, LGTM

#1668 ARM spec adjust
  .sha256sum
  hack/build-client.sh
  pkg/api/admin/openshiftcluster.go
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/admin/openshiftcluster_validatestatic_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/openshiftcluster.go
  pkg/api/v20210901preview/openshiftcluster.go
  pkg/api/v20210901preview/openshiftcluster_convert.go
  pkg/api/v20210901preview/openshiftcluster_example.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic_test.go
  pkg/client/services/redhatopenshift/mgmt/2020-04-30/redhatopenshift/openshiftclusters.go
  pkg/client/services/redhatopenshift/mgmt/2021-09-01-preview/redhatopenshift/enums.go
  pkg/client/services/redhatopenshift/mgmt/2021-09-01-preview/redhatopenshift/models.go
  pkg/client/services/redhatopenshift/mgmt/2021-09-01-preview/redhatopenshift/openshiftclusters.go
  pkg/cluster/generateconfig.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/swagger/generator.go
  pkg/swagger/swagger.go
  pkg/swagger/types.go
  pkg/swagger/typewalker.go
  pkg/util/cluster/cluster.go
  python/client/azure/__init__.py
  python/client/azure/mgmt/__init__.py
  python/client/azure/mgmt/redhatopenshift/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2021_09_01_preview/models/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2021_09_01_preview/models/_azure_red_hat_open_shift_client_enums.py
  python/client/azure/mgmt/redhatopenshift/v2021_09_01_preview/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2021_09_01_preview/models/_models_py3.py
  python/client/azure/mgmt/redhatopenshift/v2021_09_01_preview/py.typed
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2021-09-01-preview/examples/OpenShiftClusters_CreateOrUpdate.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2021-09-01-preview/examples/OpenShiftClusters_Update.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2021-09-01-preview/redhatopenshift.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-04-30/redhatopenshift.json
Labels: question, priority-medium, size-medium, ready-for-review

#1662 Remove failed vmss
  pkg/deploy/deploy.go
  pkg/deploy/deploy_gateway.go
  pkg/deploy/deploy_rp.go
  pkg/deploy/deploy_test.go
  pkg/deploy/saveversion.go
  pkg/util/azureclient/mgmt/compute/virtualmachinesscalesets.go
  pkg/util/azureclient/mgmt/compute/virtualmachinesscalesets_addons.go
  pkg/util/mocks/azureclient/mgmt/compute/compute.go
Labels: priority-high, size-medium, next-up, ready-for-review

#1687 Certificate issue adjust
  pkg/cluster/install.go
  pkg/cluster/tls.go
  pkg/util/steps/condition.go
  pkg/util/steps/runner_test.go
Labels: priority-high, size-small, ready-for-review

#1655 Add new operator controller MachineSet
  README.md
  cmd/aro/operator.go
  pkg/operator/apis/aro.openshift.io/v1alpha1/cluster_types.go
  pkg/operator/controllers/const.go
  pkg/operator/controllers/machineset/const.go
  pkg/operator/controllers/machineset/machineset_controller.go
  pkg/operator/controllers/machineset/machineset_controller_test.go
  pkg/operator/deploy/bindata.go
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/staticresources/aro.openshift.io_clusters.yaml
  test/e2e/scalenodes.go
Labels: size-medium, ready-for-review

#1695 Add ose-tools to mirroring if registry.redhat.io pull secret not present
  cmd/aro/mirror.go
Labels: priority-low, size-small, ready-for-review

#1697 Removed 'az subscription set' and bumped the 4.7 version to 4.7.24
  deploy/gateway-production.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_gateway.go
  pkg/util/dynamichelper/discovery/bindata.go
  pkg/util/dynamichelper/discovery/cache/assets_version
  pkg/util/version/const.go
Labels: priority-high, size-small, release-blocker, LGTM

#1508 Operator SDK decommissioning
  go.mod
  pkg/monitor/cluster/arooperatorconditions.go
  pkg/operator/apis/aro.openshift.io/v1alpha1/cluster_types.go
  pkg/operator/apis/aro.openshift.io/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/controllers/checker/internetchecker.go
  pkg/operator/controllers/checker/serviceprincipalchecker.go
  pkg/operator/controllers/condition.go
  pkg/operator/controllers/machine/machine_controller.go
  pkg/operator/controllers/machine/machine_controller_test.go
  pkg/operator/controllers/pullsecret/pullsecret_controller_test.go
  pkg/operator/deploy/bindata.go
  pkg/operator/deploy/staticresources/aro.openshift.io_clusters.yaml
  pkg/operator/generate.go
  pkg/util/conditions/condition.go
  pkg/util/conditions/condition_test.go
  test/e2e/operator.go
  vendor/github.com/operator-framework/operator-sdk/LICENSE
  vendor/github.com/operator-framework/operator-sdk/pkg/status/conditions.go
  vendor/modules.txt
Labels: next-up, ready-for-review
