Repository Azure/ARO-RP, pull requests merged in 2021-07, with the labels that each got.

#1541 Conditional Delete when CRG ManagedBy != OpenShiftCluster.Id
  pkg/cluster/delete.go
Labels: hold, next-up

#1598 Replaces func() with context.CancelFunc in tests
  pkg/api/validate/dynamic/dynamic_test.go
Labels: size-small

#1553 OneBranch Pipeline for Kusto Cluster Deployments
  .pipelines/onebranch/pipeline.logging.kusto.pullrequest.yml
  .pipelines/onebranch/scripts/kusto.sh
  .pipelines/onebranch/templates/template-generate-ev2-manifests.yml
  .pipelines/onebranch/templates/template-logging-kusto-bootstrapper.yml
  .pipelines/onebranch/templates/template-logging-kusto.yml
Labels: hold

#1505 Replace existing machine checker with new operator controller Machine
  README.md
  cmd/aro/operator.go
  pkg/operator/controllers/checker/checker_controller.go
  pkg/operator/controllers/checker/machinechecker_test.go
  pkg/operator/controllers/const.go
  pkg/operator/controllers/machine/const.go
  pkg/operator/controllers/machine/machine.go
  pkg/operator/controllers/machine/machine_controller.go
  pkg/operator/controllers/machine/machine_controller_test.go
Labels: next-up

#1613 Fix reconciler errors from Node controller
  pkg/operator/controllers/node/node_controller.go
Labels: LGTM, ready-for-review

#1612 Reduce logging
  pkg/monitor/cluster/arooperatorconditions.go
  pkg/monitor/cluster/clusterversionconditions.go
  pkg/monitor/cluster/machineconfigpool.go
  test/e2e/adminapi_redeployvm.go
Labels: LGTM, ready-for-review

#1610 Add fixSSH fallback
  pkg/cluster/fixssh.go
  pkg/cluster/fixssh_test.go
Labels: LGTM, ready-for-review

#1609 Add limits to ARO operator
  pkg/operator/deploy/bindata.go
  pkg/operator/deploy/staticresources/master/deployment.yaml
  pkg/operator/deploy/staticresources/worker/deployment.yaml
Labels: LGTM, ready-for-review, size-small

#1584 Debug bootstrapConfigMapReady phase
  pkg/cluster/condition.go
  pkg/cluster/condition_test.go
Labels: LGTM, ready-for-review

#1595 Server-Side Encryption and Encryption at host validations
  pkg/api/error.go
  pkg/api/v20210131preview/openshiftcluster_validatestatic.go
  pkg/api/v20210131preview/openshiftcluster_validatestatic_test.go
  pkg/api/validate/dynamic/diskencryptionset.go
  pkg/api/validate/dynamic/diskencryptionset_test.go
  pkg/api/validate/dynamic/dynamic.go
  pkg/api/validate/dynamic/dynamic_test.go
  pkg/api/validate/dynamic/encryptionathost.go
  pkg/api/validate/dynamic/encryptionathost_test.go
  pkg/api/validate/format_regexps.go
  pkg/api/validate/openshiftcluster_validatedynamic.go
  pkg/operator/controllers/checker/serviceprincipalchecker.go
  pkg/util/azureclient/mgmt/compute/diskencryptionsets.go
  pkg/util/azureclient/mgmt/compute/generate.go
  pkg/util/mocks/azureclient/mgmt/compute/compute.go
Labels: LGTM, ready-for-review, size-medium

#1614 Follow-up #1603 - bootstrap logging fix
  go.mod
  go.sum
  pkg/bootstraplogging/bootstraplogging.go
  vendor/github.com/openshift/installer/data/assets_vfsdata.go
  vendor/github.com/openshift/installer/pkg/asset/bootstraplogging/bootstraplogging.go
  vendor/modules.txt
Labels: ready-for-review

#1602 standardize names/order of args/fields in ARO operator
  cmd/aro/operator.go
  pkg/cluster/arooperator.go
  pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
  pkg/operator/controllers/alertwebhook/alertwebhook_controller_test.go
  pkg/operator/controllers/azurensg/azurensg_controller.go
  pkg/operator/controllers/azurensg/subnetnsg.go
  pkg/operator/controllers/azurensg/subnetnsg_test.go
  pkg/operator/controllers/checker/checker_controller.go
  pkg/operator/controllers/checker/internetchecker.go
  pkg/operator/controllers/checker/serviceprincipalchecker.go
  pkg/operator/controllers/clusteroperatoraro/clusteroperatoraro_controller.go
  pkg/operator/controllers/genevalogging/const.go
  pkg/operator/controllers/genevalogging/genevalogging.go
  pkg/operator/controllers/genevalogging/genevalogging_controller.go
  pkg/operator/controllers/machine/machine.go
  pkg/operator/controllers/machine/machine_controller.go
  pkg/operator/controllers/machine/machine_controller_test.go
  pkg/operator/controllers/monitoring/monitoring_controller.go
  pkg/operator/controllers/node/node_controller.go
  pkg/operator/controllers/pullsecret/pullsecret_controller.go
  pkg/operator/controllers/pullsecret/pullsecret_controller_test.go
  pkg/operator/controllers/rbac/rbac_controller.go
  pkg/operator/controllers/routefix/routefix.go
  pkg/operator/controllers/routefix/routefix_controller.go
  pkg/operator/controllers/workaround/const.go
  pkg/operator/controllers/workaround/ifreload.go
  pkg/operator/controllers/workaround/systemreserved.go
  pkg/operator/controllers/workaround/workaround_controller.go
  pkg/operator/controllers/workaround/workaround_controller_test.go
  pkg/operator/deploy/deploy.go
Labels: LGTM, next-up, priority-low, size-small

#1615 Refactor dynamic validator
  pkg/api/validate/dynamic/dynamic.go
  pkg/operator/controllers/checker/serviceprincipalchecker.go
Labels: priority-low, ready-for-review, size-small

#1621 correct fix version for icmp on 4.6
  pkg/operator/controllers/routefix/routefix_controller.go
  pkg/operator/controllers/routefix/routefix_controller_test.go
Labels: LGTM, next-up, priority-high, ready-for-review, size-small

#1571 Default to OVNKubernetes NetworkType for E2E, enable API access for production
  .sha256sum
  pkg/api/admin/openshiftcluster.go
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/admin/openshiftcluster_validatestatic_test.go
  pkg/api/openshiftcluster.go
  pkg/api/v20210131preview/openshiftcluster.go
  pkg/api/v20210131preview/openshiftcluster_convert.go
  pkg/api/v20210131preview/openshiftcluster_validatestatic.go
  pkg/api/v20210131preview/openshiftcluster_validatestatic_test.go
  pkg/client/services/redhatopenshift/mgmt/2021-01-31-preview/redhatopenshift/enums.go
  pkg/client/services/redhatopenshift/mgmt/2021-01-31-preview/redhatopenshift/models.go
  pkg/cluster/generateconfig.go
  pkg/util/cluster/cluster.go
  python/client/azure/mgmt/redhatopenshift/v2021_01_31_preview/models/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2021_01_31_preview/models/_azure_red_hat_open_shift_client_enums.py
  python/client/azure/mgmt/redhatopenshift/v2021_01_31_preview/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2021_01_31_preview/models/_models_py3.py
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2021-01-31-preview/redhatopenshift.json
Labels: next-up

#1622 Add operator readme section with deployment info
  pkg/operator/README.md
Labels: LGTM, documentation, priority-low, ready-for-review, size-small

#1625 Makes ParseVersion() to trim spaces
  pkg/operator/controllers/routefix/routefix_controller.go
  pkg/util/version/version.go
  pkg/util/version/version_test.go
Labels: LGTM, next-up, priority-high, ready-for-review, size-small

#1617 Add Missing RP Configs to devconfig
  pkg/deploy/devconfig.go
Labels: LGTM, priority-medium, ready-for-review, size-small

#1619 Simplifies dynamic.NewServicePrincipalValidator
  pkg/api/validate/dynamic/dynamic.go
  pkg/operator/controllers/checker/serviceprincipalchecker.go
  pkg/operator/controllers/checker/serviceprincipalchecker_test.go
Labels: LGTM, priority-low, size-small

#1606 move kubeconfig in deploystorage to dedicated step
  pkg/cluster/deploystorage.go
  pkg/cluster/install.go
  pkg/cluster/kubeconfig.go
Labels: ready-for-review

#1636 fix: certificateRefresher ticker.C timeout
  pkg/env/certificateRefresher_test.go
Labels: LGTM, next-up, priority-high, ready-for-review, size-small

#1639 off node scanning
  deploy/rp-production-parameters.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/config.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/templates_rp.go
Labels: LGTM, ready-for-review, size-small

#1644 Bump versions of MDM + MDSD to latest (rebased)
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/util/version/const.go
Labels: LGTM, next-up, priority-high, ready-for-review, size-small

#1604 OneBranch Pipelines for Geneva Configuration
  .pipelines/onebranch/pipeline.logging.geneva.bootstrapper.pullrequest.yml
  .pipelines/onebranch/pipeline.logging.geneva.pullrequest.yml
  .pipelines/onebranch/scripts/geneva-bootstrapper.sh
  .pipelines/onebranch/scripts/geneva.sh
  .pipelines/onebranch/templates/template-generate-ev2-manifests.yml
  .pipelines/onebranch/templates/template-logging-geneva-bootstrapper.yml
  .pipelines/onebranch/templates/template-logging-geneva.yml
Labels: priority-medium, ready-for-review, size-medium

#1646 Revert "Add limits to ARO operator"
  pkg/operator/deploy/bindata.go
  pkg/operator/deploy/staticresources/master/deployment.yaml
  pkg/operator/deploy/staticresources/worker/deployment.yaml
Labels: next-up, priority-high, ready-for-review, release-blocker, size-small

#1643 Bump 4.7 and 4.6 Versions
  pkg/util/dynamichelper/discovery/bindata.go
  pkg/util/dynamichelper/discovery/cache/assets_version
  pkg/util/version/const.go
Labels: LGTM, next-up, priority-high, ready-for-review, size-small

#1647 Unit test to verify PullSpec format
  pkg/util/version/stream_test.go
Labels: LGTM, priority-medium, ready-for-review, size-small
