Repository Azure/ARO-RP, pull requests merged in 2021-05, with the labels that each got.

#1406 Documentation for deploying whole int-style servce in dev mode
  Makefile
  docs/deploy-development-rp.md
  docs/deploy-full-rp-service-in-dev.md
  docs/prepare-your-dev-environment.md
  docs/prepare-your-development-environment-using-osx.md
Labels: next-up

#1441 Removes unnecessary retries from the reconcilers
  pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
  pkg/operator/controllers/monitoring/monitoring_controller.go
  pkg/operator/controllers/pullsecret/pullsecret_controller.go
  pkg/operator/controllers/workaround/systemreserved.go
Labels: operator, priority-low, size-medium

#1491 Webpack build process (retry)
  .gitignore
  Makefile
  docs/portal-ui.md
  pkg/portal/assets/lib/bootstrap-4.5.2.min.css
  pkg/portal/assets/lib/bootstrap-4.5.2.min.js
  pkg/portal/assets/lib/bootstrap-select-1.13.14.min.css
  pkg/portal/assets/lib/bootstrap-select-1.13.14.min.js
  pkg/portal/assets/lib/jquery-3.5.1.min.js
  pkg/portal/assets/lib/popper-1.12.9.min.js
  pkg/portal/bindata.go
  pkg/portal/generate.go
  pkg/portal/security_test.go
  pkg/util/log/audit/schema.go
  portal/dist/index.html
  portal/dist/main.js
  portal/dist/main.js.LICENSE.txt
  portal/dist/styles.css
  portal/package-lock.json
  portal/package.json
  portal/src/index.html
  portal/src/index.js
  portal/webpack.common.js
  portal/webpack.dev.js
  portal/webpack.prod.js
  test/util/log/log.go
  test/util/testpoller/testpoller.go
Labels: next-up

#1511 tests: add tests for util/ready package
  pkg/util/ready/ready.go
  pkg/util/ready/ready_test.go
Labels: priority-low

#1514 Allow Geneva source ACR override
  cmd/aro/mirror.go
Labels: next-up

#1496 Revert "Merge pull request #1486 from mjudeikis/client.package.refresh"
  deploy/env-development.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_dev.go
  pkg/deploy/generator/resources_rp.go
Labels: next-up
