Repository Azure/ARO-RP, pull requests merged in 2021-10, with the labels that each got.

#1767 change order to ensure startVM is done early
  pkg/cluster/install.go
Labels: bug, priority-high, size-small, ready-for-review, LGTM

#1769 docs: README - rename azurensg -> subnets
  README.md
Labels: documentation, priority-low, size-small, ready-for-review, LGTM

#1773 Fixes worker profile static validation for Encryption At Host
  pkg/api/v20210901preview/openshiftcluster_validatestatic.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic_test.go
Labels: bug, priority-medium, size-small, ready-for-review

#1739 AzExt - Adding support for the v2021-09-01-preview API
  docs/disk-encryption-set.md
  python/az/aro/HISTORY.rst
  python/az/aro/azext_aro/_client_factory.py
  python/az/aro/azext_aro/_params.py
  python/az/aro/azext_aro/_rbac.py
  python/az/aro/azext_aro/_validators.py
  python/az/aro/azext_aro/commands.py
  python/az/aro/azext_aro/custom.py
Labels: enhancement, size-medium, next-up, ready-for-review

#1762 Cloud Aware SRE Portal Oauth Endpoints
  pkg/portal/middleware/aad.go
  pkg/portal/middleware/aad_test.go
Labels: priority-medium, size-small, ready-for-review

#1661 don't monitor spot node conditions
  pkg/monitor/cluster/cluster.go
  pkg/monitor/cluster/nodeconditions.go
  pkg/monitor/cluster/nodeconditions_test.go
Labels: priority-low, size-medium, ready-for-review

#1467 Enable DB to use AEAD_AES_256_CBC_HMAC_SHA_512
  cmd/aro/monitor.go
  cmd/aro/portal.go
  cmd/aro/rp.go
  deploy/rp-development-predeploy.json
  deploy/rp-production-predeploy.json
  hack/db/db.go
  hack/devtools/deploy-shared-env.sh
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/predeploy.go
  pkg/env/env.go
  pkg/util/azureclient/keyvault/base_addons.go
  pkg/util/encryption/generate.go
  pkg/util/encryption/multi.go
  pkg/util/encryption/multi_test.go
  pkg/util/keyvault/keyvault.go
  pkg/util/mocks/azureclient/keyvault/keyvault.go
  pkg/util/mocks/encryption/encryption.go
  pkg/util/mocks/keyvault/keyvault.go
Labels: priority-medium, size-medium

#1705 E2E - revert cluster worker replicas after test
  test/e2e/operator.go
  test/e2e/scalenodes.go
Labels: ready-for-review, operator

#1778 Remove gateway check for ARM feature flag on cluster create
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
Labels: next-release

#1815 docs/publish-rhcos-image.md: Link to ADO wiki
  docs/publish-rhcos-image.md
Labels: documentation
