Repository Azure/ARO-RP, pull requests merged in 2021-09, with the labels that each got.

#1709 Fix regression
  pkg/cluster/tls.go
Labels: priority-high, next-up, LGTM

#1635 Fluentbit service moved to a container
  deploy/rp-production-parameters.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/config.go
  pkg/deploy/deploy_rp.go
  pkg/deploy/devconfig.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/templates_rp.go
Labels: priority-medium, size-medium, ready-for-review, LGTM

#1663 Storage Lockdown -1 - Refactor subnets related components
  cmd/aro/operator.go
  pkg/cluster/cluster.go
  pkg/operator/apis/aro.openshift.io/v1alpha1/cluster_types.go
  pkg/operator/controllers/azurensg/const.go
  pkg/operator/controllers/azurensg/subnetnsg.go
  pkg/operator/controllers/azurensg/subnetnsg_test.go
  pkg/operator/controllers/const.go
  pkg/operator/controllers/subnets/subnet_nsg.go
  pkg/operator/controllers/subnets/subnetnsg_test.go
  pkg/operator/controllers/subnets/subnets_controller.go
  pkg/operator/deploy/bindata.go
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/staticresources/aro.openshift.io_clusters.yaml
  pkg/util/mocks/subnet/subnet.go
  pkg/util/purge/purge.go
  pkg/util/subnet/cluster_subnets.go
  pkg/util/subnet/cluster_subnets_test.go
  pkg/util/subnet/const.go
  pkg/util/subnet/generate.go
  pkg/util/subnet/subnet.go
Labels: priority-medium, size-medium, ready-for-review

#1726 Add southcentralus to rp pickZones exception, not gateway
  deploy/gateway-production-parameters.json
  deploy/gateway-production.json
  deploy/rp-production-parameters.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/templates_gateway.go
  pkg/deploy/generator/templates_rp.go
Labels: priority-high, hold

#1728 Add More Non-Zoned Region Exceptions
  deploy/gateway-production-parameters.json
  deploy/gateway-production.json
  deploy/rp-production-parameters.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/templates_gateway.go
  pkg/deploy/generator/templates_rp.go
Labels: priority-high, size-small

#1711 standardize placement of generate command
  deploy/generate.go
  pkg/api/admin/generate.go
  pkg/api/generate.go
  pkg/api/v20200430/generate.go
  pkg/api/v20210901preview/generate.go
  pkg/database/cosmosdb/generate.go
Labels: priority-low, size-small, ready-for-review

#1738 added a 'doNotMirrorTags' map to skip un-mirrorable versions
  cmd/aro/mirror.go
Labels: priority-high, size-small, ready-for-review, flake

#1740 Add skip to operator e2e if not in dev mode
  test/e2e/operator.go
  test/e2e/scalenodes.go
Labels: priority-high, size-small, ready-for-review, flake

#1748 Disable redeploy VM tests
  test/e2e/adminapi_redeployvm.go
Labels: next-up, flake

#1749 Default e2e Clusters to Create with OpenShiftSDN Instead of OVNK8s
  pkg/util/cluster/cluster.go
Labels: next-up, flake

#1723 Populate registry storage account
  go.mod
  go.sum
  pkg/cluster/cluster.go
  pkg/cluster/install.go
  pkg/cluster/storageaccounts.go
  vendor/github.com/openshift/api/imageregistry/v1/00-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/01-crd.yaml
  vendor/github.com/openshift/api/imageregistry/v1/doc.go
  vendor/github.com/openshift/api/imageregistry/v1/register.go
  vendor/github.com/openshift/api/imageregistry/v1/types.go
  vendor/github.com/openshift/api/imageregistry/v1/types_imagepruner.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/imageregistry/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/config.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/doc.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/imagepruner.go
  vendor/github.com/openshift/client-go/imageregistry/clientset/versioned/typed/imageregistry/v1/imageregistry_client.go
  vendor/modules.txt
Labels: priority-high, size-small, next-up, ready-for-review

#1733 Updated the Geneva images to Sept 2021 images
  deploy/gateway-production.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/util/version/const.go
Labels: next-up

#1743 Update documentation with the new AAD group
  docs/prepare-a-shared-rp-development-environment.md
Labels: documentation, priority-low, size-small, ready-for-review

#1712 remove redundant code (covered by getParameters)
  pkg/deploy/deploy_gateway.go
  pkg/deploy/deploy_rp.go
Labels: priority-low, size-small, ready-for-review

#1759 Updated pipelines to use the RP-Config for Ev2 Manifest Generation
  .pipelines/onebranch/pipeline.bootstrapper.pullrequest.yml
  .pipelines/onebranch/pipeline.image.mirror.pullrequest.yml
  .pipelines/onebranch/templates/template-generate-ev2-manifests.yml
  .pipelines/onebranch/templates/template-image-mirror.yml
Labels: priority-medium, size-small, ready-for-review

#1732 ARO Fips Mode Installation
  .sha256sum
  pkg/api/admin/openshiftcluster.go
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/openshiftcluster.go
  pkg/api/v20210901preview/openshiftcluster.go
  pkg/api/v20210901preview/openshiftcluster_convert.go
  pkg/client/services/redhatopenshift/mgmt/2021-09-01-preview/redhatopenshift/enums.go
  pkg/client/services/redhatopenshift/mgmt/2021-09-01-preview/redhatopenshift/models.go
  pkg/cluster/generateconfig.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/util/cluster/cluster.go
  python/client/azure/mgmt/redhatopenshift/v2021_09_01_preview/models/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2021_09_01_preview/models/_azure_red_hat_open_shift_client_enums.py
  python/client/azure/mgmt/redhatopenshift/v2021_09_01_preview/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2021_09_01_preview/models/_models_py3.py
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2021-09-01-preview/redhatopenshift.json
  test/e2e/fips.go
  test/e2e/setup.go
Labels: size-medium, ready-for-review

#1702 Ensure build tag "aro" is present
  Makefile
  cmd/aro/ensurebuildtag.go
  cmd/aro/ensurebuildtag_aro.go
  cmd/aro/ensurebuildtag_test.go
  cmd/aro/main.go
  docs/deploy-development-rp.md
Labels: priority-medium, size-medium, ready-for-review
