Repository Azure/ARO-RP, pull requests merged in 2021-06, with the labels that each got.

#1513 Cloudfit/removeencryptionathost
  deploy/rp-production-parameters.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/config_test.go
  pkg/deploy/deploy.go
  pkg/deploy/deploy_rp.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/templates.go
  pkg/deploy/generator/templates_rp.go
Labels: next-up

#1534 Add azurensg controller to README.md
  README.md
Labels: ready-for-review

#1544 Support short CN in any cloud
  pkg/util/keyvault/keyvault.go
  pkg/util/keyvault/keyvault_test.go
Labels: next-up, ready-for-review

#1442 RP support for compute isolation
  .sha256sum
  pkg/api/admin/openshiftcluster.go
  pkg/api/openshiftcluster.go
  pkg/api/v20210131preview/openshiftcluster.go
  pkg/api/v20210131preview/openshiftcluster_validatestatic.go
  pkg/api/validate/dynamic/quota.go
  pkg/api/validate/vm.go
  pkg/client/services/redhatopenshift/mgmt/2021-01-31-preview/redhatopenshift/enums.go
  pkg/client/services/redhatopenshift/mgmt/2021-01-31-preview/redhatopenshift/models.go
  python/client/azure/mgmt/redhatopenshift/v2021_01_31_preview/models/_azure_red_hat_open_shift_client_enums.py
  python/client/azure/mgmt/redhatopenshift/v2021_01_31_preview/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2021_01_31_preview/models/_models_py3.py
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2021-01-31-preview/redhatopenshift.json
Labels: next-up, ready-for-review

#1542 Add MSI back into prodfromenv
  pkg/util/instancemetadata/prodfromenv.go
Labels: ready-for-review

#1565 document cmd to trigger adminupdate with dev rp && dev cluster
  docs/deploy-development-rp.md
Labels: documentation, ready-for-review
