Repository Azure/ARO-RP, pull requests merged in 2021-02, with the labels that each got.

#1273 Conditions should not block
  pkg/operator/deploy/deploy.go
  test/e2e/operator.go
Labels: bug, next-up

#1243 Collect Audit Logs From RP Frontend
  cmd/aro/main.go
  cmd/aro/rp.go
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources.go
  pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go
  pkg/frontend/admin_openshiftcluster_list_test.go
  pkg/frontend/admin_openshiftcluster_redeployvm_test.go
  pkg/frontend/admin_openshiftcluster_resources_list_test.go
  pkg/frontend/asyncoperationresult_get_test.go
  pkg/frontend/asyncoperationsstatus_get_test.go
  pkg/frontend/frontend.go
  pkg/frontend/middleware/log.go
  pkg/frontend/middleware/log_test.go
  pkg/frontend/openshiftcluster_delete_test.go
  pkg/frontend/openshiftcluster_get_test.go
  pkg/frontend/openshiftcluster_list_test.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/frontend/openshiftclustercredentials_post_test.go
  pkg/frontend/security_test.go
  pkg/frontend/shared_test.go
  pkg/frontend/subscriptions_put_test.go
  pkg/util/log/audit/audit.go
  pkg/util/log/audit/audit_test.go
  pkg/util/log/audit/schema.go
  pkg/util/log/log.go
  test/util/log/log.go
Labels: next-up

#1265 Ingress Profile enricher
  pkg/util/clusterdata/clusterdata.go
  pkg/util/clusterdata/ingress_profiles_task.go
  pkg/util/clusterdata/ingress_profiles_task_test.go
Labels: next-up

#1288 SRE portal UI: allow searching in the dropdown element
  pkg/portal/assets/index.html
  pkg/portal/assets/index.js
  pkg/portal/assets/lib/bootstrap-select-1.13.14.min.css
  pkg/portal/assets/lib/bootstrap-select-1.13.14.min.js
  pkg/portal/assets/lib/popper-1.12.9.min.js
  pkg/portal/bindata.go
Labels: enhancement

#1328 bump to 4.6.17, 4.5.31
  pkg/util/dynamichelper/discovery/bindata.go
  pkg/util/dynamichelper/discovery/cache/assets_version
  pkg/util/version/const.go
Labels: next-up

#1321 Add step to initialize SP clients in the install
  pkg/api/validate/openshiftcluster_validatedynamic.go
  pkg/api/validate/quota.go
  pkg/cluster/cluster.go
  pkg/cluster/install.go
  pkg/cluster/serviceprincipal.go
  pkg/cluster/validate.go
  pkg/util/aad/aad.go
Labels: next-up

#1322 Docker to podman migration
  deploy/env-development.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources.go
Labels: next-up

#1327 Debugging in e2e
  test/e2e/operator.go
Labels: next-up

#1336 fix vnet peering code in INT
  .pipelines/templates/template-prod-e2e-steps.yml
  pkg/util/cluster/cluster.go
Labels: next-up

#1329 Remove full deploy
  .pipelines/deploy-azure-env.yml
  .pipelines/int-release.yml
  .pipelines/prod-release.yml
  .pipelines/templates/template-deploy-azure-env.yml
  .pipelines/templates/template-job-deploy-azure-env.yml
  cmd/aro/deploy.go
  deploy/cluster-predeploy.json
  deploy/rp-production-global-acr-replication.json
  deploy/rp-production-global-subscription.json
  deploy/rp-production-global.json
  deploy/rp-production-managed-identity.json
  deploy/rp-production-parameters.json
  deploy/rp-production-predeploy-parameters.json
  deploy/rp-production-predeploy.json
  deploy/rp-production-subscription.json
  deploy/rp-production.json
  docs/deploy-upgrade-rp.md
  pkg/deploy/bindata.go
  pkg/deploy/config_test.go
  pkg/deploy/deploy.go
  pkg/deploy/deploy_test.go
  pkg/deploy/generator/resources.go
  pkg/deploy/generator/resources_cluster.go
  pkg/deploy/generator/templates.go
  pkg/deploy/predeploy.go
  pkg/util/cluster/cluster.go
  pkg/util/rbac/rbac.go
Labels: next-up

#1279 Credentials rotation - backend
  pkg/api/v20191231preview/openshiftcluster.go
  pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20200430/openshiftcluster.go
  pkg/api/v20200430/openshiftcluster_validatestatic_test.go
  pkg/api/v20210131preview/openshiftcluster.go
  pkg/api/v20210131preview/openshiftcluster_validatestatic_test.go
  pkg/cluster/arm.go
  pkg/cluster/arm_test.go
  pkg/cluster/cluster.go
  pkg/cluster/clusterserviceprincipal.go
  pkg/cluster/clusterserviceprincipal_test.go
  pkg/cluster/denyassignment.go
  pkg/cluster/denyassignment_test.go
  pkg/cluster/deploystorage.go
  pkg/cluster/deploystorage_resources.go
  pkg/cluster/deploystorage_test.go
  pkg/cluster/install.go
  pkg/cluster/install_test.go
  pkg/util/azureclient/mgmt/authorization/denyassignment.go
  pkg/util/azureclient/mgmt/authorization/denyassignment_addons.go
  pkg/util/azureclient/mgmt/authorization/generate.go
  pkg/util/mocks/azureclient/mgmt/authorization/authorization.go
Labels: next-up
