Repository Azure/ARO-RP, pull requests merged in 2021-04, with the labels that each got.

#1436 Acr location override
  deploy/rp-production-global.json
  pkg/deploy/bindata.go
  pkg/deploy/config.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/templates_rp.go
  pkg/deploy/predeploy.go
Labels: next-up

#1435 Add MsgPack value
  pkg/operator/controllers/genevalogging/genevalogging.go
Labels: next-up

#1440 Replaces Background ctx with TODO one
  pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
  pkg/operator/controllers/checker/checker_controller.go
  pkg/operator/controllers/dnsmasq/cluster_controller.go
  pkg/operator/controllers/dnsmasq/machineconfig_controller.go
  pkg/operator/controllers/dnsmasq/machineconfigpool_controller.go
  pkg/operator/controllers/genevalogging/genevalogging_controller.go
  pkg/operator/controllers/monitoring/monitoring_controller.go
  pkg/operator/controllers/node/node_controller.go
  pkg/operator/controllers/pullsecret/pullsecret_controller.go
  pkg/operator/controllers/rbac/rbac_controller.go
  pkg/operator/controllers/routefix/routefix_controller.go
  pkg/operator/controllers/workaround/workaround_controller.go
Labels: operator, priority-low, size-small

#1230 Operator: Expose Cluster SP as Condition
  cmd/aro/operator.go
  pkg/operator/apis/aro.openshift.io/v1alpha1/cluster_types.go
  pkg/operator/controllers/checker/checker_controller.go
  pkg/operator/controllers/checker/const.go
  pkg/operator/controllers/checker/machinechecker.go
  pkg/operator/controllers/checker/serviceprincipalchecker.go
  pkg/operator/controllers/checker/serviceprincipalchecker_test.go
Labels: next-up

#1348 Skeleton for blocking cluster updates via clusteroperator status
  cmd/aro/operator.go
  go.mod
  go.sum
  pkg/operator/controllers/clusteroperatoraro/clusteroperatoraro_controller.go
  pkg/operator/controllers/const.go
  pkg/util/scheme/scheme.go
  vendor/github.com/openshift/library-go/LICENSE
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/modules.txt
Labels: next-up, operator, size-medium

#1448 Changes required variables in ssh-agent.sh
  hack/ssh-agent.sh
Labels: priority-low, size-small

#1411 Add IFxAudit Logging To Admin Portal
  cmd/aro/main.go
  cmd/aro/portal.go
  pkg/frontend/security_test.go
  pkg/portal/kubeconfig/kubeconfig.go
  pkg/portal/kubeconfig/kubeconfig_test.go
  pkg/portal/kubeconfig/proxy_test.go
  pkg/portal/middleware/aad.go
  pkg/portal/middleware/aad_test.go
  pkg/portal/middleware/log.go
  pkg/portal/middleware/log_test.go
  pkg/portal/portal.go
  pkg/portal/security_test.go
  pkg/util/log/log.go
Labels: next-up

#1421 Add prometheus PVC clean workaround
  pkg/operator/controllers/workaround/cleanprompvc.go
  pkg/operator/controllers/workaround/cleanprompvc_test.go
  pkg/operator/controllers/workaround/workaround_controller.go
Labels: next-up

#1413 Remove persistence prometheus
  pkg/operator/controllers/monitoring/monitoring_controller.go
  pkg/operator/controllers/monitoring/monitoring_controller_test.go
Labels: next-up

#1261 CLI Credential rotation
  linter_exclusions.yml
  pkg/util/aad/aad.go
  pkg/util/azureerrors/error.go
  pkg/util/refreshable/refreshable.go
  python/az/aro/azext_aro/_aad.py
  python/az/aro/azext_aro/_params.py
  python/az/aro/azext_aro/_validators.py
  python/az/aro/azext_aro/custom.py
  python/az/aro/linter_exclusions.yml
Labels: next-up, ready-for-review

#1466 Update README with clusteroperatoraro controller and serviceprincipal checker in checker controller
  README.md
Labels: documentation, priority-low
