Repository Azure/ARO-RP, pull requests merged in 2022-05, with the labels that each got.

#2051 Update the secret rotate time to 7 days during RP deploy
  pkg/deploy/predeploy.go
Labels: ready-for-review

#2092 Remove dead mirror code referencing 4.3 version which isn't mirrored
  pkg/mirror/graph.go
Labels: ready-for-review

#1892 Add MTU to the internal OCP Document
  pkg/api/admin/openshiftcluster.go
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/openshiftcluster.go
  pkg/cluster/adminupdate_test.go
  pkg/cluster/deploystorage.go
  pkg/cluster/install.go
  pkg/cluster/networkprofile.go
  pkg/cluster/networkprofile_test.go
Labels: ready-for-review, next-release

#2090 Remove ACR Image Override for Geneva
  pkg/util/version/const.go
Labels: ready-for-review

#2079 Small updates to shared rp docs from working sessions
  docs/prepare-a-shared-rp-development-environment.md
Labels: ready-for-review

#2062 Additional gateway tests
  pkg/database/generate.go
  pkg/gateway/gateway.go
  pkg/gateway/gateway_test.go
  pkg/gateway/metrics.go
  pkg/gateway/metrics_test.go
  pkg/util/mocks/database/database.go
Labels: ready-for-review

#2102 Move Fluentbit RPM Package to Container in Gateway
  deploy/gateway-production-parameters.json
  deploy/gateway-production.json
  pkg/deploy/bindata.go
  pkg/deploy/deploy_gateway.go
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/templates_gateway.go
Labels: ready-for-review

#2095 set MDSD_MSGPACK_SORT_COLUMNS to perf column sorting on MDSD side
  deploy/gateway-production.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
Labels: ready-for-review

#2073 Development subscription migration
  deploy/env-development.json
  docs/deploy-development-rp.md
  docs/prepare-a-shared-rp-development-environment.md
  docs/unit-testing-for-monitoring-metrics.md
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_dev.go
  pkg/util/cluster/cluster.go
Labels: ready-for-review

#2042 Update az cli extension to use api v2022_04_01
  python/az/aro/azext_aro/_client_factory.py
  python/az/aro/azext_aro/_params.py
  python/az/aro/azext_aro/commands.py
  python/az/aro/azext_aro/custom.py
Labels: size-small, ready-for-review

#2035 Cluster create after api 2022-04-01
  pkg/util/cluster/cluster.go
Labels: size-small, ready-for-review

#1994 Added a new function for a hardcoded filter of namespaces
  docs/upstream-differences.md
  pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go
  pkg/frontend/validate.go
  pkg/monitor/cluster/daemonsetstatuses.go
  pkg/monitor/cluster/deploymentstatuses.go
  pkg/monitor/cluster/jobconditions.go
  pkg/monitor/cluster/podconditions.go
  pkg/monitor/cluster/podconditions_test.go
  pkg/monitor/cluster/prometheusalerts.go
  pkg/monitor/cluster/replicasetstatuses.go
  pkg/monitor/cluster/statefulsetstatuses.go
  pkg/util/namespace/namespace.go
  pkg/util/namespace/namespace_test.go
  test/e2e/adminapi_kubernetesobjects.go
Labels: ready-for-review

#2031 Added unit test for the makeURLSegments function of dynamichelper
  pkg/util/dynamichelper/dynamichelper_test.go
Labels: ready-for-review

#1889 Geneva master resize
  pkg/frontend/admin_openshiftcluster_startvm.go
  pkg/frontend/admin_openshiftcluster_startvm_test.go
  pkg/frontend/admin_openshiftcluster_stopvm.go
  pkg/frontend/admin_openshiftcluster_stopvm_test.go
  pkg/frontend/admin_openshiftcluster_vmresize.go
  pkg/frontend/admin_openshiftcluster_vmresize_test.go
  pkg/frontend/admin_openshiftcluster_vmsizelist.go
  pkg/frontend/admin_openshiftcluster_vmsizelist_test.go
  pkg/frontend/adminactions/azureactions.go
  pkg/frontend/frontend.go
  pkg/frontend/validate.go
  pkg/util/azureclient/mgmt/compute/virtualmachines_addons.go
  pkg/util/mocks/adminactions/adminactions.go
  pkg/util/mocks/azureclient/mgmt/compute/compute.go
Labels: ready-for-review, next-release

#2116 NSG controller - reconcile nil NSG
  pkg/operator/controllers/subnets/subnet_controller_test.go
  pkg/operator/controllers/subnets/subnet_nsg.go
Labels: bug, size-small, ready-for-review

#2112 Fix deleteNic when the nic is in failed provisioning state
  pkg/cluster/delete.go
  pkg/cluster/delete_test.go
Labels: ready-for-review

#2142 Switch to using the ubi8 go-toolset for building
  Dockerfile.aro-multistage
Labels: ready-for-review

#2094 Add additional values to CloudError and Cluster Operation Logs
  pkg/backend/openshiftcluster.go
  pkg/util/log/log.go
Labels: next-release

#2030 Improved the unit test coverage for the merge function of dynamichelper
  pkg/util/dynamichelper/dynamichelper_test.go
Labels: ready-for-review

#2138 Switch CI to FIPS enabled Go 1.17
  deploy/env-development.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_dev.go
Labels: next-up, ready-for-review

#2143 Enable MUO M2 by default
  pkg/operator/controllers/muo/muo_controller.go
  pkg/operator/controllers/muo/muo_controller_test.go
  pkg/util/version/const.go
Labels: next-up, ready-for-review, operator, next-release

#2123 Add an in-cluster alert when mhc remediates frequently
  README.md
  go.mod
  go.sum
  hack/validate-imports/validate-imports.go
  pkg/operator/controllers/machinehealthcheck/bindata.go
  pkg/operator/controllers/machinehealthcheck/doc.go
  pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller.go
  pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/operator/controllers/machinehealthcheck/staticresources/mhcremediationalert.yaml
  pkg/util/scheme/scheme.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/LICENSE
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: enhancement, ready-for-review, operator, next-release

#2134 Allow overriding the operator version in the admin API
  pkg/api/admin/openshiftcluster.go
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/openshiftcluster.go
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/deploy_test.go
Labels: operator, next-release

#2099 Generate the InfraID without Installer dependency
  hack/validate-imports/validate-imports.go
  pkg/cluster/deploystorage.go
  pkg/cluster/deploystorage_test.go
  pkg/cluster/install.go
Labels: ready-for-review

#2104 Split ensureGraph into customisations and saving
  pkg/cluster/deploystorage.go
  pkg/cluster/install.go
Labels: ready-for-review
