Repository Azure/ARO-RP, pull requests merged in 2022-07, with the labels that each got.

#2208 [M5] Split audit logging test functionality into a different file
  test/util/log/audit.go
  test/util/log/log.go
Labels: ready-for-review

#2204 [M5] Remove reliance on the OpenShiftClusterDocument in install code
  pkg/bootstraplogging/bootstraplogging.go
  pkg/cluster/install.go
  pkg/installer/custominstallconfig.go
  pkg/installer/deployresources.go
  pkg/installer/deployresources_resources.go
  pkg/installer/generateconfig.go
  pkg/installer/graph.go
  pkg/installer/install.go
  pkg/installer/manager.go
Labels: ready-for-review

#1791 Add some egress/networking config checks in the Operator
  cmd/aro/operator.go
  pkg/operator/apis/aro.openshift.io/v1alpha1/cluster_types.go
  pkg/operator/controllers/checker/checker_controller.go
  pkg/operator/controllers/checker/clusterdns.go
  pkg/operator/controllers/checker/clusterdns_test.go
  pkg/operator/controllers/checker/ingresscert.go
  pkg/operator/controllers/checker/ingresscert_test.go
Labels: size-small, ready-for-review, operator

#2226 New API Version
  .sha256sum
  Makefile
  cmd/aro/rp.go
  pkg/api/v20220904/generate.go
  pkg/api/v20220904/openshiftcluster.go
  pkg/api/v20220904/openshiftcluster_convert.go
  pkg/api/v20220904/openshiftcluster_example.go
  pkg/api/v20220904/openshiftcluster_marshal.go
  pkg/api/v20220904/openshiftcluster_validatestatic.go
  pkg/api/v20220904/openshiftcluster_validatestatic_test.go
  pkg/api/v20220904/openshiftclusteradminkubeconfig.go
  pkg/api/v20220904/openshiftclusteradminkubeconfig_convert.go
  pkg/api/v20220904/openshiftclusteradminkubeconfig_example.go
  pkg/api/v20220904/openshiftclustercredentials.go
  pkg/api/v20220904/openshiftclustercredentials_convert.go
  pkg/api/v20220904/openshiftclustercredentials_example.go
  pkg/api/v20220904/register.go
  pkg/swagger/generator.go
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/OpenShiftClusters_CreateOrUpdate.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/OpenShiftClusters_Delete.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/OpenShiftClusters_Get.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/OpenShiftClusters_List.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/OpenShiftClusters_ListAdminCredentials.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/OpenShiftClusters_ListByResourceGroup.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/OpenShiftClusters_ListCredentials.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/OpenShiftClusters_Update.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/Operations_List.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/redhatopenshift.json
Labels: ready-for-review

#2200 Fix panic bug in centraluseuap
  pkg/installer/deployresources.go
  pkg/installer/deployresources_test.go
  pkg/installer/generateconfig.go
Labels: ready-for-review

#2154 Adding validations for subnet provisioning state
  pkg/api/validate/dynamic/dynamic.go
  pkg/api/validate/dynamic/dynamic_test.go
  python/az/aro/azext_aro/_validators.py
Labels: ready-for-review

#2089 Added unit test for the EnsureDeleted function of dynamichelper
  pkg/util/dynamichelper/dynamichelper.go
  pkg/util/dynamichelper/dynamichelper_test.go
Labels: ready-for-review

#2231 Hive: preparation for adoption & reconciliation on update
  pkg/cluster/cluster.go
  pkg/cluster/delete.go
  pkg/cluster/deregisterFromHive.go
  pkg/cluster/hive.go
  pkg/cluster/install.go
  pkg/cluster/registerWithHive.go
  pkg/hive/manager.go
  pkg/hive/resources.go
Labels: ready-for-review

#2234 Update Default ARO Version to Fix with Availability Set Name Length
  .pipelines/e2e-with-billing.yml
  .pipelines/templates/template-job-deploy-azure-env-tag.yml
  .pipelines/templates/template-job-deploy-azure-env.yml
  .pipelines/templates/template-prod-e2e-steps.yml
  .pipelines/templates/template-rp-and-billing-e2e.yml
  hack/e2e/run-rp-and-e2e.sh
  hack/validate-imports/allowed-import-names.yaml
  pkg/api/v20191231preview/openshiftcluster_validatestatic.go
  pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20200430/openshiftcluster_validatestatic.go
  pkg/api/v20200430/openshiftcluster_validatestatic_test.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20220401/openshiftcluster_validatestatic.go
  pkg/api/v20220401/openshiftcluster_validatestatic_test.go
  pkg/api/v20220904/openshiftcluster_validatestatic.go
  pkg/api/v20220904/openshiftcluster_validatestatic_test.go
  pkg/api/validate/openshiftcluster.go
  pkg/api/validate/openshiftcluster_test.go
  pkg/util/dynamichelper/discovery/bindata.go
  pkg/util/dynamichelper/discovery/cache/assets_version
  pkg/util/version/const.go
Labels: ready-for-review

#2233 fix operation uniqueness
  pkg/frontend/asyncoperationresult_get.go
  pkg/frontend/asyncoperationresult_get_test.go
  pkg/frontend/asyncoperationsstatus_get.go
  pkg/frontend/asyncoperationsstatus_get_test.go
Labels: ready-for-review

#2241 Feat: Add API support for choosing Software Defined Network (OVN/SDN)
  .sha256sum
  pkg/api/v20220904/openshiftcluster.go
  pkg/api/v20220904/openshiftcluster_convert.go
  pkg/api/v20220904/openshiftcluster_validatestatic.go
  pkg/api/v20220904/openshiftcluster_validatestatic_test.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/client.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/enums.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/models.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/openshiftclusters.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/operations.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/redhatopenshiftapi/interfaces.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/version.go
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/_azure_red_hat_open_shift_client.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/_configuration.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/_patch.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/_vendor.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/models/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/models/_azure_red_hat_open_shift_client_enums.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/models/_models_py3.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/operations/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/operations/_open_shift_clusters_operations.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/operations/_operations.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/py.typed
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/redhatopenshift.json
Labels: ready-for-review

#2235 Add Private Cluster Flag for Local Development
  docs/deploy-development-rp.md
  pkg/util/cluster/cluster.go
Labels: ready-for-review

#2178 e2e to definitively determine a cluster is ARO
  test/e2e/aro.go
Labels: enhancement, size-small, ready-for-review

#2251 Adding openvpn for civm's to support Simply Secure
  deploy/env-development.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_dev.go
Labels: ready-for-review

#2170 Create DNS record for the AKS API during provisioning
  hack/devtools/deploy-shared-env.sh
  pkg/deploy/assets/aks-development.json
Labels: ready-for-review

#2259 Doc: add step to Re-deploy VM of a dev cluster
  docs/deploy-development-rp.md
Labels: ready-for-review

#2264 slight refactor to use of FriendlyName function
  pkg/cluster/gatherlogs.go
  pkg/monitor/cluster/cluster.go
Labels: ready-for-review

#2169 Update changes required for Microsoft Graph
  docs/prepare-a-shared-rp-development-environment.md
  hack/devtools/deploy-shared-env.sh
Labels: ready-for-review

#2274 docs: update aad group name
  docs/prepare-a-shared-rp-development-environment.md
Labels: documentation, size-small, ready-for-review

#2267 parseUnverified returns cloudError
  pkg/api/error.go
  pkg/util/aad/aad.go
Labels: ready-for-review

#2276 Add codeql configuration to prevent scanning vendor directory
  .github/workflows/codeql-analysis.yml
  .github/workflows/codeql-config.yml
Labels: ready-for-review

#2230 Prevent AdminAction redeploy if VM has an ephemeral OS disk
  pkg/frontend/adminactions/azureactions.go
Labels: ready-for-review

#1882 ensure that the ARO operator is running at the desired image
  pkg/cluster/adminupdate_test.go
  pkg/cluster/arooperator.go
  pkg/cluster/install.go
  pkg/operator/deploy/deploy.go
  pkg/util/mocks/operator/deploy/deploy.go
Labels: ready-for-review

#2161 make monitor Ignore preempted completed pods
  pkg/monitor/cluster/podconditions.go
  vendor/k8s.io/kubernetes/pkg/kubelet/events/event.go
  vendor/modules.txt
Labels: ready-for-review

#2265 Set qualys download link config param
  pkg/deploy/assets/gateway-production-parameters.json
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production-parameters.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/config.go
  pkg/deploy/deploy_gateway.go
  pkg/deploy/deploy_rp.go
  pkg/deploy/devconfig.go
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/templates_gateway.go
  pkg/deploy/generator/templates_rp.go
Labels: ready-for-review

#2247 Remove all UBI7
  Dockerfile.aro-multistage
  Dockerfile.fluentbit
  Makefile
Labels: ready-for-review

#2195 [M6] Generate database UUIDs in a way that can be deterministic for testing
  cmd/aro/portal.go
  hack/validate-imports/allowed-import-names.yaml
  pkg/api/admin/openshiftcluster_validatestatic_test.go
  pkg/api/v20191231preview/openshiftcluster_validatestatic.go
  pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20200430/openshiftcluster_validatestatic.go
  pkg/api/v20200430/openshiftcluster_validatestatic_test.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20220401/openshiftcluster_validatestatic.go
  pkg/api/v20220401/openshiftcluster_validatestatic_test.go
  pkg/api/v20220904/openshiftcluster_validatestatic.go
  pkg/api/v20220904/openshiftcluster_validatestatic_test.go
  pkg/database/asyncoperations.go
  pkg/database/gateway.go
  pkg/database/generate.go
  pkg/database/monitors.go
  pkg/database/openshiftclusters.go
  pkg/database/portal.go
  pkg/database/subscriptions.go
  pkg/dbtoken/server.go
  pkg/deploy/generator/templates.go
  pkg/env/armhelper.go
  pkg/frontend/asyncoperations.go
  pkg/frontend/middleware/log.go
  pkg/frontend/middleware/validate.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/gateway/gateway_test.go
  pkg/hive/manager.go
  pkg/portal/kubeconfig/kubeconfig.go
  pkg/portal/kubeconfig/kubeconfig_test.go
  pkg/portal/kubeconfig/proxy_test.go
  pkg/portal/middleware/aad.go
  pkg/portal/middleware/aad_test.go
  pkg/portal/middleware/bearer.go
  pkg/portal/ssh/proxy.go
  pkg/portal/ssh/ssh.go
  pkg/portal/ssh/ssh_test.go
  pkg/util/acrtoken/acrtoken.go
  pkg/util/arm/marshal.go
  pkg/util/cluster/aad.go
  pkg/util/cluster/cluster.go
  pkg/util/log/audit/audit.go
  pkg/util/mocks/database/database.go
  pkg/util/uuid/uuid.go
  test/database/fixtures.go
  test/database/inmemory.go
  test/util/deterministicuuid/deterministicuuid.go
  test/util/deterministicuuid/deterministicuuid_test.go
Labels: ready-for-review

#2246 Fix broken mirror specific version arg
  cmd/aro/mirror.go
  pkg/mirror/graph.go
Labels: ready-for-review
