Repository Azure/ARO-RP, pull requests merged in 2022-08, with the labels that each got.

#2225 Added an endpoint to list available versions to install
  .sha256sum
  pkg/api/installversions.go
  pkg/api/register.go
  pkg/api/v20220904/installversions.go
  pkg/api/v20220904/installversions_convert.go
  pkg/api/v20220904/installversions_example.go
  pkg/api/v20220904/openshiftcluster.go
  pkg/api/v20220904/register.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/list.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/models.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/openshiftclusters.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/operations.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/redhatopenshiftapi/interfaces.go
  pkg/frontend/frontend.go
  pkg/frontend/installversions_list.go
  pkg/frontend/installversions_list_test.go
  pkg/frontend/operations_get.go
  pkg/swagger/generator.go
  pkg/swagger/swagger.go
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/_azure_red_hat_open_shift_client.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/models/_models_py3.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/operations/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/operations/_list_operations.py
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/List_Install_Versions.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/redhatopenshift.json
Labels: ready-for-review

#2266 generate and insert public key on deploy
  pkg/deploy/config.go
Labels: ready-for-review

#2282 add logic to choose default disk
  pkg/installer/generateconfig.go
  pkg/util/computeskus/computeskus.go
  pkg/util/computeskus/computeskus_test.go
Labels: ready-for-review

#2305 Fix panic on AdminUpdate for clusters with custom storage
  pkg/cluster/storageaccounts.go
  pkg/operator/controllers/storageaccounts/storageaccounts.go
Labels: bug

#2314 Cleanup hack/clean.go
  hack/clean/clean.go
Labels: ready-for-review

#2075 Dropping ipRules parameter; it is not used in this template (causes "unable to parse template on line 1" error)
  pkg/deploy/assets/rp-development.json
  pkg/deploy/generator/templates_rp.go
Labels: ready-for-review

#2055 Updated rbac-development.json used in setting up a shared rp environment to allow for creating a custom role definition for the first party sub.
  pkg/deploy/assets/rbac-development.json
Labels: ready-for-review

#2103 Add Cordon and Drain Related Admin Endpoints for New Geneva Actions
  pkg/frontend/admin_openshiftcluster_cordonnode.go
  pkg/frontend/admin_openshiftcluster_cordonnode_test.go
  pkg/frontend/admin_openshiftcluster_drainnode.go
  pkg/frontend/admin_openshiftcluster_drainnode_test.go
  pkg/frontend/adminactions/drain.go
  pkg/frontend/adminactions/kubeactions.go
  pkg/frontend/frontend.go
  pkg/util/mocks/adminactions/adminactions.go
  test/e2e/adminapi_drainnode.go
Labels: ready-for-review

#2213 Refactor/simplify enable service endpoints
  pkg/cluster/enableendpoints.go
  pkg/cluster/enableendpoints_test.go
  pkg/cluster/storageaccount_test.go
  pkg/cluster/storageaccounts.go
  pkg/util/mocks/subnet/subnet.go
  pkg/util/subnet/addendpoints.go
  pkg/util/subnet/addendpoints_test.go
  pkg/util/subnet/subnet.go
Labels: size-medium, ready-for-review

#2214 Added ServiceEndpoint for Microsoft.Storage to the generator for development
  pkg/deploy/assets/rp-development-predeploy.json
  pkg/deploy/generator/resources_rp.go
Labels: ready-for-review

#2307 Scope the OpenShift install version listing by location
  .sha256sum
  Makefile
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/list.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/models.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/openshiftclusters.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/operations.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/redhatopenshiftapi/interfaces.go
  pkg/frontend/frontend.go
  pkg/frontend/installversions_list_test.go
  pkg/frontend/operations_get.go
  pkg/swagger/generator.go
  pkg/swagger/paths.go
  pkg/swagger/swagger.go
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/_azure_red_hat_open_shift_client.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/models/_models_py3.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/operations/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/operations/_list_operations.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/operations/_open_shift_clusters_operations.py
  swagger/common-types/resource-management/v3/types.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/List_Install_Versions.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/redhatopenshift.json
Labels: ready-for-review

#2315 Updating docs for applying patches to installer-aro
  docs/upstream-differences.md
Labels: documentation, ready-for-review

#2238 Move Dev Environment VPN to Enable Connection to RP and Cluster Private IPs Simultaneously
  pkg/deploy/assets/env-development.json
  pkg/deploy/assets/rp-development-predeploy.json
  pkg/deploy/assets/rp-production-predeploy.json
  pkg/deploy/generator/resources.go
  pkg/deploy/generator/resources_dev.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/templates_dev.go
  pkg/deploy/generator/templates_gateway.go
  pkg/deploy/generator/templates_rp.go
Labels: ready-for-review

#2114 Add Force Delete Parameter to Delete Kubernetes Object Admin Endpoint for New Geneva Action
  pkg/frontend/admin_openshiftcluster_kubernetesobjects.go
  pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go
  pkg/frontend/adminactions/kubeactions.go
  pkg/frontend/validate.go
  pkg/util/mocks/adminactions/adminactions.go
  test/e2e/adminapi_kubernetesobjects.go
Labels: ready-for-review

#2320 re-implement cloud aware function for e2e test
  test/e2e/operator.go
Labels: ready-for-review, next-release

#2190 az aro update: startvms, validate api servers, and configure api/ingress certs
  pkg/cluster/install.go
Labels: ready-for-review

#2308 added hiveEnsureResources unit tests
  pkg/cluster/hive_test.go
Labels: ready-for-review

#2311 Added hiveDeleteResources unit tests
  pkg/cluster/hive_test.go
Labels: ready-for-review

#2309 Migrate OneBranch pipelines to isolated ACR
  .pipelines/onebranch/pipeline.buildrp.official.yml
  .pipelines/onebranch/pipeline.buildrp.pullrequest.yml
  .pipelines/onebranch/templates/template-buildrp-builddocker.yml
  Dockerfile.aro-multistage-onebranch
Labels: ready-for-review

#2312 update pipeline to only generate release notes
  .pipelines/generate-release-notes-tagged.yml
  docs/releases.md
Labels: ready-for-review

#2328 Persist tags on ensureResourceGroup
  pkg/cluster/deploystorage.go
  pkg/cluster/deploystorage_test.go
Labels: ready-for-review, next-release

#2330 Do not fail cluster installation if the default storage account already exists
  pkg/cluster/storageclass.go
Labels: ready-for-review

#2336 fixing private key formatting
  pkg/deploy/config.go
Labels: bug, ready-for-review, next-release

#2212 added github action for go ci
  .github/workflows/ci-go.yml
  Dockerfile.ci
  hack/ci-utils/build.sh
Labels: ready-for-review

#2285 Add expression to exclude logs from openshift-logging namespace
  pkg/operator/controllers/genevalogging/const.go
Labels: ready-for-review

#2331 Refactor how we version the aro operator deploymennt
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/deploy_test.go
  pkg/operator/deploy/staticresources/master/deployment.yaml.tmpl
  pkg/operator/deploy/staticresources/worker/deployment.yaml.tmpl
Labels: ready-for-review, next-release

#2275 DRY implementation to our admin_vm_actions
  pkg/frontend/admin_openshiftcluster_redeployvm.go
  pkg/frontend/admin_openshiftcluster_startvm.go
  pkg/frontend/admin_openshiftcluster_stopvm.go
  pkg/frontend/admin_openshiftcluster_vmresize.go
  pkg/frontend/admin_openshiftcluster_vmsizelist.go
  pkg/frontend/admin_vm_actions.go
  pkg/frontend/frontend.go
Labels: ready-for-review

#2341 Deprecation Fix: Replace strings.Title with Caser
  go.mod
  pkg/swagger/paths.go
  vendor/golang.org/x/text/cases/cases.go
  vendor/golang.org/x/text/cases/context.go
  vendor/golang.org/x/text/cases/fold.go
  vendor/golang.org/x/text/cases/icu.go
  vendor/golang.org/x/text/cases/info.go
  vendor/golang.org/x/text/cases/map.go
  vendor/golang.org/x/text/cases/tables10.0.0.go
  vendor/golang.org/x/text/cases/tables11.0.0.go
  vendor/golang.org/x/text/cases/tables12.0.0.go
  vendor/golang.org/x/text/cases/tables13.0.0.go
  vendor/golang.org/x/text/cases/tables9.0.0.go
  vendor/golang.org/x/text/cases/trieval.go
  vendor/golang.org/x/text/internal/internal.go
  vendor/golang.org/x/text/internal/match.go
  vendor/modules.txt
Labels: size-small, ready-for-review

#2325 [M4/M5/M6] Read Hive kubeconfig from AKS live
  cmd/aro/monitor.go
  pkg/backend/openshiftcluster.go
  pkg/backend/openshiftcluster_test.go
  pkg/env/core.go
  pkg/env/env.go
  pkg/env/prod.go
  pkg/hive/util.go
  pkg/monitor/monitor.go
  pkg/monitor/worker.go
  pkg/util/azureclient/mgmt/containerservice/generate.go
  pkg/util/azureclient/mgmt/containerservice/managedcluster_addons.go
  pkg/util/azureclient/mgmt/containerservice/managedclusters.go
  pkg/util/liveconfig/dev.go
  pkg/util/liveconfig/hive.go
  pkg/util/liveconfig/hive_test.go
  pkg/util/liveconfig/manager.go
  pkg/util/liveconfig/testdata/kubeconfig
  pkg/util/mocks/azureclient/mgmt/containerservice/containerservice.go
  pkg/util/mocks/env/env.go
  test/util/testliveconfig/liveconfig.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-10-01/containerservice/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-10-01/containerservice/_meta.json
  vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-10-01/containerservice/agentpools.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-10-01/containerservice/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-10-01/containerservice/enums.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-10-01/containerservice/maintenanceconfigurations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-10-01/containerservice/managedclusters.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-10-01/containerservice/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-10-01/containerservice/operations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-10-01/containerservice/privateendpointconnections.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-10-01/containerservice/privatelinkresources.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-10-01/containerservice/resolveprivatelinkserviceid.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-10-01/containerservice/snapshots.go
  vendor/github.com/Azure/azure-sdk-for-go/services/containerservice/mgmt/2021-10-01/containerservice/version.go
  vendor/modules.txt
Labels: ready-for-review

#2346 clean up naming in liveconfig
  pkg/util/liveconfig/dev.go
  pkg/util/liveconfig/hive.go
  pkg/util/liveconfig/manager.go
Labels: ready-for-review

#2348 Set supported operations on an API version basis
  pkg/api/operation.go
  pkg/api/register.go
  pkg/api/v20191231preview/register.go
  pkg/api/v20200430/register.go
  pkg/api/v20210901preview/register.go
  pkg/api/v20220401/register.go
  pkg/api/v20220904/register.go
  pkg/frontend/operations_get.go
Labels: bug, ready-for-review, next-release

#2350 Add AKS cluster admin role to the RP MSI
  pkg/deploy/assets/rp-development.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_rp.go
  pkg/util/rbac/rbac.go
Labels: ready-for-review, next-release

#2342 Update Hive image mirror tag
  cmd/aro/mirror.go
Labels: ready-for-review, next-release

#2356 API 2022-09-04: install-version parameter activation and version listing fixes
  .sha256sum
  pkg/api/v20220904/installversions.go
  pkg/api/v20220904/installversions_convert.go
  pkg/api/v20220904/openshiftcluster.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/list.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/models.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/redhatopenshiftapi/interfaces.go
  pkg/frontend/installversions_list_test.go
  pkg/swagger/examples.go
  pkg/util/azureclient/mgmt/redhatopenshift/2022-09-04/redhatopenshift/openshiftclusters.go
  pkg/util/azureclient/mgmt/redhatopenshift/2022-09-04/redhatopenshift/openshiftclusters_addons.go
  pkg/util/azureclient/mgmt/redhatopenshift/2022-09-04/redhatopenshift/operations.go
  pkg/util/azureclient/mgmt/redhatopenshift/2022-09-04/redhatopenshift/operations_addons.go
  pkg/util/cluster/cluster.go
  python/az/aro/HISTORY.rst
  python/az/aro/azext_aro/_help.py
  python/az/aro/azext_aro/_params.py
  python/az/aro/azext_aro/_validators.py
  python/az/aro/azext_aro/custom.py
  python/az/aro/setup.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/models/_models_py3.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/operations/_list_operations.py
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/List_Install_Versions.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/redhatopenshift.json
  test/e2e/setup.go
Labels: next-release

#2319 make ensureAROOperatorRunningDesiredVersion a condition
  pkg/cluster/adminupdate_test.go
  pkg/cluster/arooperator.go
  pkg/cluster/arooperator_test.go
  pkg/cluster/install.go
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/deploy_test.go
  pkg/util/mocks/operator/deploy/deploy.go
Labels: ready-for-review, next-release

#2351 Pass Hive installation based parameters through to Hive
  pkg/deploy/assets/rp-production-parameters.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/config.go
  pkg/deploy/devconfig.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/templates_rp.go
Labels: ready-for-review

#2334 Create update OpenShift versions command
  cmd/aro/main.go
  cmd/aro/update_ocp_versions.go
Labels: ready-for-review, next-release

#2361 Specify platform when building or running images
  Makefile
  hack/build-client.sh
Labels: ready-for-review

#2352 include openshift-cluster-version in monitoring
  pkg/util/namespace/namespace.go
  pkg/util/namespace/namespace_test.go
Labels: size-small, ready-for-review

#2333 Switch RP NSG from using rpNsgSourceAddressPrefixes to static GenevaActions service tag
  pkg/deploy/assets/rp-development-predeploy.json
  pkg/deploy/assets/rp-production-predeploy-parameters.json
  pkg/deploy/assets/rp-production-predeploy.json
  pkg/deploy/config.go
  pkg/deploy/devconfig.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/templates.go
  pkg/deploy/generator/templates_rp.go
Labels: ready-for-review

#2366 Drain Node E2E Test Fix
  test/e2e/adminapi_drainnode.go
Labels: ready-for-review

#2215 [M5] Initial storage of ClusterDocument in Hive
  pkg/cluster/cluster.go
  pkg/cluster/hive.go
  pkg/cluster/hive_test.go
  pkg/cluster/install.go
  pkg/hive/install.go
  pkg/hive/manager.go
  pkg/hive/manager_test.go
  pkg/hive/resources.go
  pkg/hive/resources_test.go
  pkg/util/liveconfig/dev.go
  pkg/util/liveconfig/hive.go
  pkg/util/liveconfig/manager.go
  pkg/util/mocks/hive/hive.go
  test/util/testliveconfig/liveconfig.go
Labels: ready-for-review

#2369 Fix autorest client generation
  Dockerfile.autorest
  Makefile
  hack/build-client.sh
Labels: ready-for-review

#2367 Update Shared RP Custom Role Permissions
  pkg/deploy/assets/rbac-development.json
Labels: ready-for-review

#2353 Removing yum exclude on WALinuxAgent to resolve dependency errors
  pkg/deploy/assets/env-development.json
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_dev.go
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
Labels: ready-for-review
