Repository Azure/ARO-RP, pull requests merged in 2022-12, with the labels that each got.

#2561 fixed race condition in frontend
  pkg/frontend/admin_openshiftcluster_redeployvm.go
  pkg/frontend/admin_openshiftcluster_startvm.go
  pkg/frontend/admin_openshiftcluster_stopvm.go
  pkg/frontend/admin_openshiftcluster_vmresize.go
  pkg/frontend/admin_vm_actions.go
  pkg/frontend/frontend.go
Labels: bug, ready-for-review, next-release

#2568 Fix AKS shard number and add equalfold
  .pipelines/e2e.yml
  test/e2e/aks.go
Labels: next-release

#2572 reads from embedded files instead of filesystem
  pkg/portal/portal.go
Labels: bug, priority-high, next-release

#2576 Hive Install: Allow access from the AKS pod subnet
  pkg/cluster/deploystorage_resources.go
Labels: ready-for-review

#2581 Update az aro extension to support specifying --pull-secret file without @ prefix
  python/az/aro/azext_aro/_validators.py
  python/az/aro/azext_aro/tests/latest/unit/test_validators.py
Labels: ready-for-review

#2586 Update `pkg/util/cluster/cluster.go` to use v20220904
  pkg/util/cluster/cluster.go
Labels: ready-for-review

#2591 Operator deploy fix
  pkg/operator/deploy/deploy.go
  pkg/util/dynamichelper/createorder.go
  pkg/util/dynamichelper/workloadhelper.go
Labels: ready-for-review

#2592 Specify the APIServerIPOverride for Hive installs
  pkg/hive/install.go
Labels: ready-for-review

#2529 Add unit tests for database package
  cmd/aro/dbtoken.go
  cmd/aro/gateway.go
  cmd/aro/monitor.go
  cmd/aro/portal.go
  cmd/aro/rp.go
  cmd/aro/update_ocp_versions.go
  hack/db/db.go
  pkg/database/asyncoperations_test.go
  pkg/database/clustermanager_test.go
  pkg/database/database.go
  pkg/database/database_test.go
  pkg/database/gateway_test.go
  pkg/database/monitors_test.go
  pkg/database/openshiftclusters_test.go
  pkg/database/openshiftversions_test.go
  pkg/database/portal_test.go
  pkg/util/azureclient/mgmt/documentdb/databaseaccounts.go
  pkg/util/azureclient/mgmt/documentdb/generate.go
  pkg/util/mocks/documentdb/documentdb.go
  test/database/billing_test.go
  test/database/subscriptions_test.go
Labels: ready-for-review

#2600 Consolidate documents to docs folder
  docs/operators.md
  docs/portalv2.md
Labels: documentation, ready-for-review

#2593 Update redeployvm e2e test to use unique name for each uptime pod
  test/e2e/adminapi_redeployvm.go
Labels: ready-for-review
