Repository Azure/ARO-RP, pull requests merged in 2022-02, with the labels that each got.

#1766 imageconfig controller
  README.md
  cmd/aro/operator.go
  pkg/api/defaults.go
  pkg/operator/controllers/const.go
  pkg/operator/controllers/imageconfig/image_controller.go
  pkg/operator/controllers/imageconfig/image_controller_test.go
Labels: priority-medium, size-medium, ready-for-review

#1935 Suppress stderr within Makefile command
  Makefile
Labels: ready-for-review

#1936 Do not overwrite FIPs environment variable in CI VMs
  deploy/env-development.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_dev.go
Labels: bug, ready-for-review

#1948 Update correct directory path for pipeline template files
  .pipelines/int-release-tag.yml
  .pipelines/prod-release-tag.yml
  .pipelines/templates/template-job-deploy-azure-env-tag.yml
Labels: bug, ready-for-review

#1940 Bump golang version to 1.16 in CI VMs
  Dockerfile.aro-multistage
  deploy/env-development.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_dev.go
Labels: ready-for-review

#1942 Deleting MDM/MDSD/Kusto OneBranch Pipeline Definitions
  .pipelines/onebranch/pipeline.logging.geneva.bootstrapper.pullrequest.yml
  .pipelines/onebranch/pipeline.logging.geneva.pullrequest.yml
  .pipelines/onebranch/pipeline.logging.kusto.pullrequest.yml
  .pipelines/onebranch/scripts/geneva-bootstrapper.sh
  .pipelines/onebranch/scripts/geneva.sh
  .pipelines/onebranch/scripts/kusto.sh
  .pipelines/onebranch/templates/template-logging-geneva-bootstrapper.yml
  .pipelines/onebranch/templates/template-logging-geneva.yml
  .pipelines/onebranch/templates/template-logging-kusto.yml
Labels: ready-for-review

#1956 quick fixes in docs
  docs/testing.md
  hack/local-monitor-testing/deploy_MDM_VM.sh
  pkg/operator/README.md
Labels: enhancement, good first issue, size-small, ready-for-review

#1933 drop net_raw on rp related containers
  deploy/gateway-production.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
Labels: size-small, hold, ready-for-review

#1927 Add Central US EUAP to nonZonalRegions
  deploy/gateway-production-parameters.json
  deploy/gateway-production.json
  deploy/rp-production-parameters.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/templates_gateway.go
  pkg/deploy/generator/templates_rp.go
Labels: hold

#1856 remove network acceleration due to issues discovered
  deploy/gateway-production.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_gateway.go
Labels: size-small

#1928 add a field to indicate spotInstances in node.conditions metric
  pkg/monitor/cluster/cluster.go
  pkg/monitor/cluster/nodeconditions.go
  pkg/monitor/cluster/nodeconditions_test.go
Labels: enhancement, good first issue, size-small, next-up, ready-for-review, next-release

#1975 add additional logging to redeploy vm e2e
  test/e2e/adminapi_redeployvm.go
Labels: size-small, flake

#1973 Egress Lockdown: Enable and Toggle
  pkg/api/admin/openshiftcluster_validatestatic.go
  pkg/api/admin/openshiftcluster_validatestatic_test.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/operator/deploy/deploy.go
  test/e2e/cluster.go
Labels: size-medium, hold, next-up, next-release
