Repository Azure/ARO-RP, pull requests merged in 2022-10, with the labels that each got.

#2421 CI E2E in SimplySecure
  .pipelines/e2e.yml
  docs/prepare-a-shared-rp-development-environment.md
  hack/devtools/deploy-shared-env.sh
  hack/e2e/run-rp-and-e2e.sh
  pkg/cluster/nsg.go
  pkg/deploy/assets/aks-development.json
  pkg/util/azureclient/mgmt/network/virtualnetworkpeerings.go
  pkg/util/azureclient/mgmt/network/virtualnetworkpeerings_addons.go
  pkg/util/cluster/cluster.go
  pkg/util/mocks/azureclient/mgmt/network/network.go
Labels: ready-for-review

#2399 Certificate renewal PUCM type to rotate in-cluster MDSD/ingress/API certs
  pkg/api/admin/openshiftcluster.go
  pkg/api/admin/openshiftcluster_validatestatic.go
  pkg/api/openshiftcluster.go
  pkg/cluster/adminupdate_test.go
  pkg/cluster/arooperator.go
  pkg/cluster/install.go
  pkg/operator/deploy/deploy.go
  pkg/util/mocks/operator/deploy/deploy.go
Labels: ready-for-review

#2431 upgrade golangci-litn, removed deadcode linter, duplicate of unused
  .github/workflows/golint.yml
  .golangci.yml
Labels: ready-for-review

#2425 Fix InternalServerError for decoding outdated securecookie
  pkg/portal/middleware/aad.go
  pkg/portal/middleware/aad_test.go
Labels: ready-for-review

#2438 E2E clients cleanup
  test/e2e/disk_encryption.go
  test/e2e/setup.go
Labels: hold

#2444 Add .dockerignore file :rocket:
  .dockerignore
Labels: ready-for-review

#2448 Revert "Merge pull request #2444 from bennerv/add-dockerignore"
  .dockerignore
Labels: size-small, ready-for-review

#1955 Collect must-gathers on failed e2e runs
  .pipelines/e2e.yml
  .pipelines/vars.yml
  hack/e2e/run-rp-and-e2e.sh
  test/e2e/setup.go
Labels: ready-for-review

#2457 Force the aro operator deployment to be a string
  pkg/operator/deploy/staticresources/master/deployment.yaml.tmpl
  pkg/operator/deploy/staticresources/worker/deployment.yaml.tmpl
Labels: bug, ready-for-review

#2442 Update docs for deploying the full-service RP in a dev environment :writing_hand:
  docs/deploy-full-rp-service-in-dev.md
Labels: ready-for-review

#2454 Set the correct VM family on the currently supported GPU instance types
  pkg/api/validate/dynamic/quota.go
Labels: ready-for-review

#2480 add cadenmarchese to owners
  .github/CODEOWNERS
Labels: ready-for-review

#2440 AKS AgentPool MSI permissions and remove duplicated Keyvault issuer steps
  pkg/deploy/assets/rp-development-predeploy.json
  pkg/deploy/assets/rp-production-predeploy.json
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/predeploy.go
Labels: ready-for-review, next-release

#2474 Set OCP pullspec back to quay.io after the Hive installation completes
  pkg/cluster/disableupdates.go
Labels: ready-for-review, next-release

#2470 Liveconfig: Global AKS shard admin credentials
  pkg/env/core.go
  pkg/hive/install.go
  pkg/monitor/monitor.go
  pkg/monitor/worker.go
  pkg/util/azureclient/mgmt/containerservice/managedcluster_addons.go
  pkg/util/liveconfig/dev.go
  pkg/util/liveconfig/hive.go
  pkg/util/liveconfig/hive_test.go
  pkg/util/liveconfig/manager.go
  pkg/util/liveconfig/testdata/kubeconfigAdmin
  pkg/util/mocks/azureclient/mgmt/containerservice/containerservice.go
Labels: ready-for-review, next-release

#2451 added difference checker
  .dockerignore
  hack/ci-utils/build.sh
  hack/ci-utils/differenceChecker/main.go
Labels: ready-for-review

#2493 validate permissions on NAT gateways
  pkg/api/error.go
  pkg/api/validate/dynamic/dynamic.go
  pkg/api/validate/dynamic/dynamic_test.go
Labels: ready-for-review, skippy

#2394 Add network contributor to NAT gateway
  python/az/aro/azext_aro/custom.py
Labels: ready-for-review, skippy

#2481 added more linter
  .golangci.yml
  pkg/api/v20220401/openshiftcluster_example.go
  pkg/api/v20220904/openshiftcluster_example.go
  pkg/api/validate/dynamic/quota.go
  pkg/frontend/admin_openshiftcluster_vmresize_test.go
  pkg/frontend/openshiftversions_list.go
  pkg/monitor/cluster/arooperatorconditions.go
  pkg/monitor/cluster/machineconfigpool_test.go
  pkg/monitor/cluster/prometheusalerts.go
  pkg/monitor/worker.go
  pkg/util/conditions/condition.go
  pkg/util/keyvault/keyvault.go
  test/util/deterministicuuid/deterministicuuid.go
Labels: size-small, ready-for-review
