Repository Azure/ARO-RP, pull requests merged in 2022-06, with the labels that each got.

#2122 refactored muo to extract deployer
  hack/validate-imports/validate-imports.go
  pkg/operator/controllers/muo/bindata.go
  pkg/operator/controllers/muo/deploy.go
  pkg/operator/controllers/muo/deploy_test.go
  pkg/operator/controllers/muo/generate.go
  pkg/operator/controllers/muo/muo_controller.go
  pkg/operator/controllers/muo/muo_controller_test.go
  pkg/operator/controllers/muo/staticresources/config.yaml
  pkg/operator/controllers/muo/staticresources/deployment.yaml
  pkg/operator/controllers/muo/template_test.go
  pkg/operator/controllers/muo/test_files/connected.yaml
  pkg/operator/controllers/muo/test_files/local.yaml
  pkg/util/deployer/deploy_test.go
  pkg/util/deployer/deployer.go
  pkg/util/deployer/generate.go
  pkg/util/deployer/staticresources/deployment.yaml
  pkg/util/mocks/deployer/deployer.go
Labels: ready-for-review

#2119 removed go-bindata from pkg/operator
  hack/validate-imports/validate-imports.go
  pkg/operator/deploy/bindata.go
  pkg/operator/deploy/deploy.go
  pkg/operator/generate.go
  pkg/util/embed/embeddedfiles.go
Labels: ready-for-review

#1885 add: Getpodlogs kubeaction api
  docs/deploy-development-rp.md
  pkg/frontend/admin_openshiftcluster_kubernetespods_logs.go
  pkg/frontend/admin_openshiftcluster_kubernetespods_logs_test.go
  pkg/frontend/adminactions/kubeactions.go
  pkg/frontend/frontend.go
  pkg/frontend/validate.go
  pkg/frontend/validate_test.go
  pkg/util/mocks/adminactions/adminactions.go
  test/e2e/adminapi.go
  test/e2e/adminapi_cluster_getlogs.go
Labels: ready-for-review

#2130 Migrate from AD to MS Graph
  python/az/aro/azext_aro/_aad.py
  python/az/aro/azext_aro/custom.py
Labels: ready-for-review

#2136 clean up of validate import, now uses a yaml file for maintainability
  hack/validate-imports/allowed-import-names.yaml
  hack/validate-imports/validate-imports.go
Labels: ready-for-review

#2157 Add name length validation on ARO clusters for non-zonal regions
  hack/validate-imports/allowed-import-names.yaml
  pkg/api/v20191231preview/openshiftcluster_validatestatic.go
  pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20200430/openshiftcluster_validatestatic.go
  pkg/api/v20200430/openshiftcluster_validatestatic_test.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20220401/openshiftcluster_validatestatic.go
  pkg/api/v20220401/openshiftcluster_validatestatic_test.go
  pkg/api/validate/openshiftcluster.go
  pkg/api/validate/openshiftcluster_test.go
Labels: priority-high, size-small, next-up, ready-for-review

#2160 Typo in pipeline script
  .pipelines/templates/template-prod-e2e-steps.yml
Labels: ready-for-review, release-blocker

#2155 include openshift-operator-lifecycle-manager in monitoring
  pkg/util/namespace/namespace.go
  pkg/util/namespace/namespace_test.go
Labels: ready-for-review

#2162 Update gateway arm template deployment name and log message
  pkg/cluster/gatewayprivateendpoint.go
Labels: ready-for-review

#2163 fix bug where mhc wouldn't kick in after CR change
  pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller.go
Labels: priority-high, size-small, ready-for-review

#2156 reduce the use of bindata for machinehealthcheck controller
  pkg/operator/controllers/machinehealthcheck/bindata.go
  pkg/operator/controllers/machinehealthcheck/generate.go
  pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller.go
Labels: priority-low, ready-for-review

#2128 AKS development environment
  Makefile
  deploy/aks-development.json
  docs/deploy-development-rp.md
  hack/devtools/deploy-shared-env.sh
  hack/get-admin-aks-kubeconfig.sh
  hack/ssh-aks.sh
  pkg/deploy/bindata.go
Labels: ready-for-review

#2167 Fix azureproviderspec regression
  hack/validate-imports/allowed-import-names.yaml
  pkg/cluster/fixmcsuserdata.go
  pkg/operator/controllers/machine/machine.go
  pkg/util/clusterdata/worker_profiles_task.go
  pkg/util/machine/azureproviderspec.go
  pkg/util/machine/azureproviderspec_test.go
Labels: priority-high, size-small, next-up, ready-for-review, release-blocker, next-release

#2141 Mirror App-SRE images (MUO, Hive) to ACR
  cmd/aro/mirror.go
Labels: hold

#2185 Listen to the pullsecret in the MUO Operator
  pkg/operator/controllers/muo/muo_controller.go
Labels: next-up, ready-for-review

#2159 Move the Installer-related code into a different package
  pkg/cluster/deploystorage.go
  pkg/cluster/install.go
  pkg/installer/condition.go
  pkg/installer/custominstallconfig.go
  pkg/installer/deployresources.go
  pkg/installer/deployresources_resources.go
  pkg/installer/deployresources_test.go
  pkg/installer/generateconfig.go
  pkg/installer/graph.go
  pkg/installer/install.go
  pkg/installer/manager.go
  pkg/installer/overridemtu.go
Labels: ready-for-review

#2171 Hive AKS development environment deploy
  .gitignore
  docs/hive.md
  hack/hive-config/cluster-image-sets/4.10.15.yaml
  hack/hive-config/hive-config.yaml
  hack/hive-dev-install.sh
  hack/hive-generate-config.sh
Labels: ready-for-review

#2194 Refactor/simplify openshift cluster database
  pkg/cluster/install.go
  pkg/cluster/sshkeys.go
  pkg/cluster/storageSuffix.go
  pkg/database/openshiftclusters.go
Labels: ready-for-review

#2197 Bump MDM/MDSD image versions
  deploy/gateway-production.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/util/version/const.go
Labels: ready-for-review

#2199 Move initialize aro deployer step to before ensureAroOperator
  pkg/cluster/adminupdate_test.go
  pkg/cluster/install.go
Labels: ready-for-review

#2189 operator deployment improvement
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/deploy_test.go
  pkg/operator/deploy/staticresources/master/deployment.yaml.tmpl
  pkg/operator/deploy/staticresources/worker/deployment.yaml.tmpl
Labels: ready-for-review

#2187 add docs, script, and makefile to log into/use shared cluster
  Makefile
  docs/img/sharedcluster.png
  docs/shared-cluster.md
  hack/shared-cluster.sh
Labels: documentation, size-small, ready-for-review

#2207 feature: enable mhc by default
  pkg/api/defaults.go
  pkg/operator/controllers/machinehealthcheck/doc.go
  test/e2e/operator.go
Labels: ready-for-review, next-release

#2217 mitigate regression in azsecpack version 2.20
  deploy/gateway-production.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
Labels: next-release
