Repository Azure/ARO-RP, pull requests merged in 2022-03, with the labels that each got.

#1751 L series support - RP changes
  pkg/api/admin/openshiftcluster.go
  pkg/api/openshiftcluster.go
  pkg/api/validate/dynamic/quota.go
  pkg/api/validate/vm.go
Labels: enhancement, priority-medium, hold

#1790 Add SKU availability and restriction checks to dynamic validation
  pkg/api/validate/dynamic/dynamic.go
  pkg/api/validate/dynamic/sku.go
  pkg/api/validate/dynamic/sku_test.go
  pkg/api/validate/openshiftcluster_validatedynamic.go
  pkg/env/prod.go
  pkg/util/computeskus/computeskus.go
  pkg/util/computeskus/computeskus_test.go
Labels: enhancement, ready-for-review

#1925 Minor ARO operator refactoring
  cmd/aro/operator.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
  pkg/operator/controllers/alertwebhook/alertwebhook_controller_test.go
  pkg/operator/controllers/banner/banner_controller.go
  pkg/operator/controllers/banner/banner_controller_test.go
  pkg/operator/controllers/checker/checker_controller.go
  pkg/operator/controllers/clusteroperatoraro/clusteroperatoraro_controller.go
  pkg/operator/controllers/const.go
  pkg/operator/controllers/dnsmasq/cluster_controller.go
  pkg/operator/controllers/dnsmasq/machineconfig_controller.go
  pkg/operator/controllers/dnsmasq/machineconfigpool_controller.go
  pkg/operator/controllers/genevalogging/genevalogging.go
  pkg/operator/controllers/genevalogging/genevalogging_controller.go
  pkg/operator/controllers/genevalogging/genevalogging_test.go
  pkg/operator/controllers/imageconfig/image_controller.go
  pkg/operator/controllers/imageconfig/image_controller_test.go
  pkg/operator/controllers/machine/machine_controller.go
  pkg/operator/controllers/machine/machine_controller_test.go
  pkg/operator/controllers/machineset/machineset_controller.go
  pkg/operator/controllers/machineset/machineset_controller_test.go
  pkg/operator/controllers/monitoring/monitoring_controller.go
  pkg/operator/controllers/monitoring/monitoring_controller_test.go
  pkg/operator/controllers/muo/deploy.go
  pkg/operator/controllers/muo/deploy_test.go
  pkg/operator/controllers/muo/muo_controller.go
  pkg/operator/controllers/muo/muo_controller_test.go
  pkg/operator/controllers/node/node_controller.go
  pkg/operator/controllers/node/node_controller_test.go
  pkg/operator/controllers/previewfeature/previewfeature_controller.go
  pkg/operator/controllers/pullsecret/pullsecret_controller.go
  pkg/operator/controllers/pullsecret/pullsecret_controller_test.go
  pkg/operator/controllers/rbac/rbac_controller.go
  pkg/operator/controllers/routefix/routefix_controller.go
  pkg/operator/controllers/storageaccounts/storageaccount_controller.go
  pkg/operator/controllers/storageaccounts/storageaccounts_test.go
  pkg/operator/controllers/subnets/subnet_controller_test.go
  pkg/operator/controllers/subnets/subnets_controller.go
  pkg/operator/controllers/workaround/workaround_controller.go
  pkg/operator/controllers/workaround/workaround_controller_test.go
  test/e2e/operator.go
  test/e2e/scalenodes.go
Labels: ready-for-review

#1986 fix protobuf, containerd vulns, add validate-fips step into onebranch build rp template
  .pipelines/onebranch/templates/template-buildrp-buildaro.yml
  go.mod
  go.sum
  vendor/github.com/docker/go-metrics/go.mod
  vendor/github.com/docker/go-metrics/go.sum
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/viper/go.mod
  vendor/github.com/spf13/viper/go.sum
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
Labels: size-small, ready-for-review

#1993 Dockerfile to create MUO image
  Dockerfile.muo
Labels: priority-high, next-up, ready-for-review

#2009 Add the MUO configmap deployment to the Operator
  pkg/operator/controllers/muo/bindata.go
  pkg/operator/controllers/muo/config/config.go
  pkg/operator/controllers/muo/deploy.go
  pkg/operator/controllers/muo/deploy_test.go
  pkg/operator/controllers/muo/muo_controller.go
  pkg/operator/controllers/muo/muo_controller_test.go
  pkg/operator/controllers/muo/staticresources/config.yaml
  pkg/operator/mocks/muo/muo.go
Labels: enhancement, priority-high, next-up, operator

#2001 Fixing E2E Flake Redeploy VM
  test/e2e/adminapi_redeployvm.go
Labels: size-small, ready-for-review, flake

#2024 disable ipv6 router advertisements on rp/gateway vmss
  deploy/gateway-production.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
Labels: size-small, ready-for-review

#2025 Enable Managed Upgrade Operator on new clusters
  pkg/api/defaults.go
  pkg/operator/controllers/muo/muo_controller.go
  pkg/operator/controllers/muo/muo_controller_test.go
  pkg/util/version/const.go
  test/e2e/operator.go
Labels: priority-high, next-up, ready-for-review, operator
