Repository Azure/ARO-RP, pull requests merged in 2022-09, with the labels that each got.

#2375 Move the disabling of samples and operatorhub sources earlier in the installation process
  pkg/cluster/install.go
Labels: ready-for-review, next-release

#2376 Update auth used by rhcos uploads
  hack/rhcos-sas/rhcos-sas.go
Labels: size-small, ready-for-review

#2364 Remove SDN option from the stable API
  .sha256sum
  pkg/api/v20220904/openshiftcluster.go
  pkg/api/v20220904/openshiftcluster_convert.go
  pkg/api/v20220904/openshiftcluster_validatestatic.go
  pkg/api/v20220904/openshiftcluster_validatestatic_test.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/enums.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/models.go
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/models/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/models/_azure_red_hat_open_shift_client_enums.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/models/_models_py3.py
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/redhatopenshift.json
Labels: ready-for-review

#2210 Added cluster install time metrics
  pkg/backend/openshiftcluster.go
  pkg/backend/openshiftcluster_test.go
  pkg/cluster/cluster.go
  pkg/cluster/install.go
  pkg/cluster/install_test.go
  pkg/installer/install.go
  pkg/util/steps/action.go
  pkg/util/steps/condition.go
  pkg/util/steps/refreshing.go
  pkg/util/steps/runner.go
  pkg/util/steps/runner_test.go
Labels: size-medium, ready-for-review

#2379 bump ado agent to 2.206.1
  pkg/deploy/assets/env-development.json
  pkg/deploy/generator/resources_dev.go
Labels: ready-for-review

#2374 M6: Enable multi-version cluster installation
  cmd/aro/rp.go
  pkg/api/components/installversion/openshiftcluster.go
  pkg/api/components/installversion/parse.go
  pkg/api/components/installversion/parse_test.go
  pkg/api/v20220904/openshiftcluster_example.go
  pkg/api/v20220904/openshiftcluster_validatestatic.go
  pkg/api/validate/format_regexps.go
  pkg/backend/backend.go
  pkg/backend/openshiftcluster.go
  pkg/backend/openshiftcluster_test.go
  pkg/cluster/cluster.go
  pkg/cluster/install.go
  pkg/cluster/install_version.go
  pkg/cluster/install_version_test.go
  pkg/frontend/installversions_list.go
  pkg/frontend/installversions_list_test.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/frontend/validate.go
  pkg/hive/install.go
  pkg/hive/manager.go
  pkg/hive/manager_test.go
  pkg/installer/generateconfig.go
  pkg/installer/manager.go
  pkg/util/liveconfig/dev.go
  pkg/util/liveconfig/hive.go
  pkg/util/liveconfig/manager.go
  test/util/deterministicuuid/deterministicuuid.go
  test/util/testliveconfig/liveconfig.go
Labels: ready-for-review, next-release

#2382 Hive image with CLI Image domain override support
  cmd/aro/mirror.go
  hack/hive-generate-config.sh
Labels: ready-for-review, next-release

#2386 Update CI VMSS CSE script to resize LVM partition
  pkg/deploy/assets/env-development.json
  pkg/deploy/generator/resources_dev.go
Labels: size-small, ready-for-review

#2389 Revert RP AKS role assignment in favour of the AKS ARM template
  pkg/deploy/assets/rp-development.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_rp.go
  pkg/util/rbac/rbac.go
Labels: ready-for-review, next-release

#2109 Add Approve CSR Admin Endpoint for New Geneva Action
  pkg/frontend/admin_openshiftcluster_approvecsr.go
  pkg/frontend/admin_openshiftcluster_approvecsr_test.go
  pkg/frontend/adminactions/certificatesigningrequests.go
  pkg/frontend/adminactions/kubeactions.go
  pkg/frontend/frontend.go
  pkg/util/mocks/adminactions/adminactions.go
  test/e2e/adminapi_csr.go
Labels: ready-for-review

#2409 Update OCM Swagger Examples
  pkg/api/v20220904/clustermanager_example.go
  pkg/swagger/examples.go
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/MachinePools_CreateOrUpdate.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/MachinePools_Get.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/MachinePools_List.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/MachinePools_Update.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/Secrets_CreateOrUpdate.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/Secrets_Get.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/Secrets_List.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/Secrets_Update.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/SyncIdentityProviders_CreateOrUpdate.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/SyncIdentityProviders_Get.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/SyncIdentityProviders_List.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/SyncIdentityProviders_Update.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/SyncSets_CreateOrUpdate.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/SyncSets_Get.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/SyncSets_List.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/examples/SyncSets_Update.json
Labels: ready-for-review

#2395 add gpu instance types
  pkg/api/openshiftcluster.go
  pkg/api/validate/dynamic/quota.go
  pkg/api/validate/vm.go
Labels: ready-for-review

#2340 make ImageConfig environment aware
  pkg/operator/controllers/imageconfig/image_controller.go
  pkg/operator/controllers/imageconfig/image_controller_test.go
  test/e2e/operator.go
Labels: ready-for-review

#2415 fix regressions from rebase/refactors
  pkg/api/v20220904/clustermanager_convert.go
  pkg/api/v20220904/register.go
Labels: next-release

#2411 Add unit tests for OCM frontend routes
  docs/feature-flags.md
  pkg/database/clustermanager.go
  pkg/deploy/devconfig.go
  pkg/env/env.go
  pkg/env/zz_generated_feature_enumer.go
  pkg/frontend/clustermanager_delete.go
  pkg/frontend/clustermanager_delete_test.go
  pkg/frontend/clustermanager_get.go
  pkg/frontend/clustermanager_get_test.go
  pkg/frontend/clustermanager_putorpatch.go
  pkg/frontend/clustermanager_putorpatch_test.go
  pkg/frontend/frontend.go
  pkg/frontend/frontend_test.go
  pkg/frontend/security_test.go
  pkg/frontend/shared_test.go
  pkg/util/arm/resources.go
  test/database/clustermanager.go
  test/database/fixtures.go
  test/database/inmemory.go
Labels: ready-for-review

#2428 add color back into e2es, easier to see pass/fails in ADO
  Makefile
Labels: ready-for-review

#2434 workaround - FPSP Role Assignment Doesn't Have Get
  pkg/cluster/deploystorage.go
  pkg/cluster/deploystorage_test.go
Labels: bug, hold, next-release
