Repository Azure/ARO-RP, pull requests merged in 2022-11, with the labels that each got.

#2512 Exclude WALinuxAgent from vm update scripts
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/scripts/gatewayVMSS.sh
  pkg/deploy/generator/scripts/rpVMSS.sh
Labels: ready-for-review, next-release

#2337 Add ARO ingress controller
  cmd/aro/operator.go
  pkg/api/defaults.go
  pkg/operator/controllers/ingress/ingress_controller.go
  pkg/operator/controllers/ingress/ingress_controller_test.go
Labels: size-medium, ready-for-review, skippy

#2504 Move sshd_config step first in boot script, add basic logging
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/scripts/gatewayVMSS.sh
  pkg/deploy/generator/scripts/rpVMSS.sh
Labels: ready-for-review

#2488 Add unit tests for dynamic/serviceprincipal, azureclient/environments, clusterauthorizer
  pkg/api/validate/dynamic/dynamic.go
  pkg/api/validate/dynamic/generate.go
  pkg/api/validate/dynamic/serviceprincipal.go
  pkg/api/validate/dynamic/serviceprincipal_test.go
  pkg/api/validate/openshiftcluster_validatedynamic.go
  pkg/cluster/serviceprincipal.go
  pkg/operator/controllers/checker/serviceprincipalchecker.go
  pkg/operator/controllers/checker/serviceprincipalchecker_test.go
  pkg/operator/controllers/previewfeature/previewfeature_controller.go
  pkg/operator/controllers/storageaccounts/storageaccount_controller.go
  pkg/operator/controllers/subnets/subnets_controller.go
  pkg/util/aad/aad.go
  pkg/util/aad/generate.go
  pkg/util/azureclient/environments_test.go
  pkg/util/clusterauthorizer/authorizer.go
  pkg/util/clusterauthorizer/authorizer_test.go
  pkg/util/mocks/aad/aad.go
  pkg/util/mocks/dynamic/dynamic.go
Labels: size-medium, ready-for-review

#2521 Liveconfig: Use case insensitive matching for the AKS cluster lookup
  pkg/util/liveconfig/hive.go
Labels: bug, ready-for-review, next-release

#2509 Dynamic Keyvault access policy for the AKS agentpool MSI
  pkg/deploy/assets/rp-development-predeploy.json
  pkg/deploy/assets/rp-production-predeploy.json
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/templates_rp.go
  pkg/util/azureclient/apiversions.go
Labels: ready-for-review, next-release

#2355 [admin-portal]: add a fix for subscription ID filtering
  portal/v2/build/asset-manifest.json
  portal/v2/build/index.html
  portal/v2/build/static/js/main.2de0ba6f.js
  portal/v2/build/static/js/main.2de0ba6f.js.LICENSE.txt
  portal/v2/build/static/js/main.2de0ba6f.js.map
  portal/v2/build/static/js/main.7461e442.js
  portal/v2/build/static/js/main.7461e442.js.LICENSE.txt
  portal/v2/build/static/js/main.7461e442.js.map
  portal/v2/package-lock.json
  portal/v2/package.json
  portal/v2/src/ClusterList.tsx
Labels: ready-for-review

#2344 Refactor pkg/portal to use go:embed instead of go-bindata
  pkg/portal/assets/assets.go
  pkg/portal/assets/v1/build/index.html
  pkg/portal/assets/v1/build/main.js
  pkg/portal/assets/v1/build/main.js.LICENSE.txt
  pkg/portal/assets/v1/build/styles.css
  pkg/portal/assets/v2/build/asset-manifest.json
  pkg/portal/assets/v2/build/favicon.ico
  pkg/portal/assets/v2/build/index.html
  pkg/portal/assets/v2/build/static/js/main.d2a3e4e8.js
  pkg/portal/assets/v2/build/static/js/main.d2a3e4e8.js.LICENSE.txt
  pkg/portal/assets/v2/build/static/js/main.d2a3e4e8.js.map
  pkg/portal/generate.go
  pkg/portal/portal.go
Labels: ready-for-review, skippy

#2541 Fix admin portal go embed
  Makefile
  pkg/portal/assets/v2/build/static/js/main.0aeb07b4.js
  pkg/portal/assets/v2/build/static/js/main.0aeb07b4.js.LICENSE.txt
  pkg/portal/assets/v2/build/static/js/main.0aeb07b4.js.map
  pkg/portal/assets/v2/build/static/js/main.d2a3e4e8.js
  pkg/portal/assets/v2/build/static/js/main.d2a3e4e8.js.LICENSE.txt
  pkg/portal/assets/v2/build/static/js/main.d2a3e4e8.js.map
  pkg/portal/portal.go
  portal/v1/webpack.common.js
  portal/v2/package.json
  test/e2e/admin_portal.go
  test/e2e/setup.go
Labels: priority-high, ready-for-review

#2543 Follow up API fixes
  .sha256sum
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/machinepools.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/models.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/secrets.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/syncidentityproviders.go
  pkg/client/services/redhatopenshift/mgmt/2022-09-04/redhatopenshift/syncsets.go
  pkg/swagger/paths.go
  pkg/swagger/swagger.go
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/models/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/models/_models_py3.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/operations/_machine_pools_operations.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/operations/_secrets_operations.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/operations/_sync_identity_providers_operations.py
  python/client/azure/mgmt/redhatopenshift/v2022_09_04/operations/_sync_sets_operations.py
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2022-09-04/redhatopenshift.json
Labels: ready-for-review, next-release

#2552 Remove example files from .dockerignore
  .dockerignore
Labels: ready-for-review, next-release

#2551 Hive: exit if we enter ProvisionFailed status
  pkg/hive/manager.go
  pkg/hive/manager_test.go
Labels: ready-for-review, next-release

#2550 AKS MSI / cluster storage / ACR fixes for ARO-Installer in Production
  pkg/cluster/deploystorage_resources.go
  pkg/deploy/assets/rp-development-predeploy.json
  pkg/deploy/assets/rp-production-predeploy.json
  pkg/deploy/generator/resources_rp.go
  pkg/hive/resources.go
Labels: ready-for-review, next-release

#2545 Add more logs about aro deployment state
  pkg/monitor/cluster/arooperatorheartbeat.go
  pkg/monitor/cluster/arooperatorheartbeat_test.go
  pkg/operator/deploy/deploy.go
Labels: next-release

#2358 Add e2e test for hive kubeconfig
  test/e2e/aks.go
Labels: size-small, ready-for-review, next-release

#2553 Modify az get-versions iteration to match the latest round of API changes
  python/az/aro/azext_aro/custom.py
Labels: bug, ready-for-review, next-release

#2558 Skips AKS tests for defined regions without AKS
  test/e2e/aks.go
Labels: next-release

#2542 Migrates rest of the E2Es to use `Eventually` instead of `wait.Poll*`
  pkg/util/ready/ready.go
  pkg/util/ready/ready_test.go
  test/e2e/adminapi.go
  test/e2e/adminapi_cluster_get.go
  test/e2e/adminapi_cluster_getlogs.go
  test/e2e/adminapi_cluster_list.go
  test/e2e/adminapi_cluster_update.go
  test/e2e/adminapi_kubernetesobjects.go
  test/e2e/adminapi_redeployvm.go
  test/e2e/cluster.go
Labels: next-release

#2547 Fixed input on Admin Portal V1. Updated loader-utils to 2.0.4 to mitigate vulnerability.
  pkg/portal/assets/v1/build/index.html
  pkg/portal/assets/v1/build/main.js
  pkg/portal/assets/v1/build/main.js.LICENSE.txt
  pkg/portal/assets/v1/build/styles.css
  pkg/portal/assets/v2/build/asset-manifest.json
  pkg/portal/assets/v2/build/index.html
  pkg/portal/assets/v2/build/static/js/main.0aeb07b4.js
  pkg/portal/assets/v2/build/static/js/main.0aeb07b4.js.map
  pkg/portal/assets/v2/build/static/js/main.66cb7002.js
  pkg/portal/assets/v2/build/static/js/main.66cb7002.js.LICENSE.txt
  pkg/portal/assets/v2/build/static/js/main.66cb7002.js.map
  portal/v1/package-lock.json
  portal/v1/package.json
  portal/v1/src/index.html
  portal/v1/src/index.js
  portal/v1/src/select/select.css
  portal/v2/package-lock.json
  portal/v2/package.json
Labels: ready-for-review, next-release

#2560 Fixes a bug in the certificate PUCM process
  pkg/cluster/adminupdate_test.go
  pkg/cluster/install.go
Labels: bug, ready-for-review, next-release

#2563 Bump MDM containers to latest distroless versions
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/util/version/const.go
Labels: next-release

#2248 Public IP removal
  pkg/api/admin/openshiftcluster.go
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/featureflags.go
  pkg/api/openshiftcluster.go
  pkg/cluster/deploystorage.go
  pkg/cluster/install.go
  pkg/cluster/networkprofile.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/installer/custominstallconfig.go
  pkg/installer/deployresources_resources.go
  pkg/installer/generateconfig.go
  pkg/installer/install.go
Labels: ready-for-review, next-release

#2486 Remove all old-style prod-related pipeline configurations, leaving just CI & OneBranch
  .pipelines/build-and-push-fluentbit.yml
  .pipelines/build-and-push-images.yml
  .pipelines/deploy-azure-env-tag.yml
  .pipelines/deploy-azure-env.yml
  .pipelines/e2e-with-billing-all-regions.yml
  .pipelines/e2e-with-billing.yml
  .pipelines/generate-release-notes-tagged.yml
  .pipelines/int-release-tag.yml
  .pipelines/int-release.yml
  .pipelines/mirror-aro-to-int.yml
  .pipelines/prod-release-tag.yml
  .pipelines/prod-release.yml
  .pipelines/templates/template-deploy-azure-env.yml
  .pipelines/templates/template-job-deploy-azure-env-tag.yml
  .pipelines/templates/template-job-deploy-azure-env.yml
  .pipelines/templates/template-prod-e2e-steps.yml
  .pipelines/templates/template-push-images-to-acr-tagged.yml
  .pipelines/templates/template-rp-and-billing-e2e-section.yml
  .pipelines/templates/template-rp-and-billing-e2e.yml
Labels: ready-for-review, next-release
