Repository Azure/ARO-RP, pull requests merged in 2022-01, with the labels that each got.

#1894 Alertmanager fix
  pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
Labels: bug, priority-high, size-small, next-release

#1821 CI VM Fixes
  deploy/env-development.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_dev.go
Labels: ready-for-review

#1701 Set Operator flags from the RP
  pkg/api/admin/openshiftcluster.go
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/openshiftcluster.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/operator/apis/aro.openshift.io/v1alpha1/cluster_types.go
  pkg/operator/apis/aro.openshift.io/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
  pkg/operator/controllers/alertwebhook/alertwebhook_controller_test.go
  pkg/operator/controllers/banner/banner_controller.go
  pkg/operator/controllers/banner/banner_controller_test.go
  pkg/operator/controllers/checker/checker_controller.go
  pkg/operator/controllers/dnsmasq/cluster_controller.go
  pkg/operator/controllers/dnsmasq/machineconfig_controller.go
  pkg/operator/controllers/dnsmasq/machineconfigpool_controller.go
  pkg/operator/controllers/genevalogging/genevalogging_controller.go
  pkg/operator/controllers/machine/machine_controller.go
  pkg/operator/controllers/machine/machine_controller_test.go
  pkg/operator/controllers/machineset/machineset_controller.go
  pkg/operator/controllers/machineset/machineset_controller_test.go
  pkg/operator/controllers/monitoring/monitoring_controller.go
  pkg/operator/controllers/monitoring/monitoring_controller_test.go
  pkg/operator/controllers/node/node_controller.go
  pkg/operator/controllers/node/node_controller_test.go
  pkg/operator/controllers/pullsecret/pullsecret_controller.go
  pkg/operator/controllers/pullsecret/pullsecret_controller_test.go
  pkg/operator/controllers/rbac/rbac_controller.go
  pkg/operator/controllers/routefix/routefix_controller.go
  pkg/operator/controllers/subnets/subnets_controller.go
  pkg/operator/controllers/workaround/workaround_controller.go
  pkg/operator/controllers/workaround/workaround_controller_test.go
  pkg/operator/deploy/bindata.go
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/staticresources/aro.openshift.io_clusters.yaml
  test/e2e/operator.go
  test/e2e/scalenodes.go
Labels: size-medium, next-up, ready-for-review, operator

#1901 Enable reconciling azuresubnets/NSGs by default
  pkg/api/defaults.go
Labels: next-up

#1854 refector e2e for removing dependency.
  test/e2e/scalenodes.go
Labels: size-small

#1548 Restart mdm service when new certificate is downloaded
  deploy/gateway-production.json
  deploy/rp-production.json
  docs/certificate-rotation.md
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
Labels: enhancement, LGTM

#1674 [PIPELINES 2] Replace config fetch with direct code checkout
  .pipelines/deploy-azure-env.yml
  .pipelines/int-release.yml
  .pipelines/prod-release.yml
  .pipelines/templates/template-job-deploy-azure-env.yml
Labels: enhancement, size-small, ready-for-review

#1903 Allow fluentbit/mdsd image setting via feature flags
  pkg/operator/apis/aro.openshift.io/v1alpha1/cluster_types.go
  pkg/operator/controllers/genevalogging/genevalogging.go
  pkg/operator/controllers/genevalogging/genevalogging_controller.go
  pkg/operator/controllers/genevalogging/genevalogging_test.go
Labels: next-up, ready-for-review, operator

#1688 [PIPELINES 3] Add second pipeline deploying from tagged image
  .pipelines/deploy-azure-env-tag.yml
  .pipelines/int-release-tag.yml
  .pipelines/prod-release-tag.yml
  .pipelines/templates/template-job-deploy-azure-env-tag.yml
Labels: enhancement, size-medium, ready-for-review

#1684 [PIPELINES 4] Create release based on annotated git tag
  .pipelines/build-and-push-images-tagged.yml
  .pipelines/templates/template-push-images-to-acr-tagged.yml
  Makefile
Labels: enhancement, size-medium, ready-for-review

#1902 mdm/mdsd++
  deploy/gateway-production.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/util/version/const.go
Labels: priority-high, size-small, next-up, ready-for-review, next-release
