Repository Azure/ARO-RP, pull requests merged in 2022-04, with the labels that each got.

#2003 Proxy cleanup
  pkg/proxy/proxy.go
Labels: size-small, ready-for-review

#2039 Add `containers_image_openpgp` to deploy, run-portal, and unit-test-go
  Makefile
Labels: size-small

#1950 add worker only controller with operator for machine health check
  README.md
  cmd/aro/operator.go
  pkg/api/defaults.go
  pkg/operator/controllers/machinehealthcheck/bindata.go
  pkg/operator/controllers/machinehealthcheck/doc.go
  pkg/operator/controllers/machinehealthcheck/generate.go
  pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller.go
  pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
  pkg/operator/controllers/machinehealthcheck/staticresources/machinehealthcheck.yaml
Labels: enhancement, priority-high, size-small, next-up, ready-for-review, operator, release-blocker, next-release

#2021 check for ingressIP when ingressProfiles > 1
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/deploy_test.go
Labels: size-small, ready-for-review, next-release

#2041 Skip Linux AZ Sec Pack policies from running on VMSS creation
  deploy/gateway-production.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
Labels: ready-for-review, next-release

#2052 [bugfix] give /tmp a bit more room for when the CI VM gets busy
  deploy/env-development.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_dev.go
Labels: ready-for-review

#2007 Add testing to the proxy
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
Labels: ready-for-review

#2049 renamed oddly named metrics.Interface to MetricsEmitter
  pkg/backend/backend.go
  pkg/database/database.go
  pkg/database/metrics.go
  pkg/dbtoken/refresher.go
  pkg/dbtoken/server.go
  pkg/frontend/admin_openshiftcluster_list_test.go
  pkg/frontend/frontend.go
  pkg/frontend/middleware/metrics.go
  pkg/frontend/openshiftcluster_get_test.go
  pkg/frontend/openshiftcluster_list_test.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/gateway/gateway.go
  pkg/metrics/generate.go
  pkg/metrics/metrics.go
  pkg/metrics/statsd/azure/metrics.go
  pkg/metrics/statsd/azure/metrics_test.go
  pkg/metrics/statsd/cosmosdb/metrics.go
  pkg/metrics/statsd/cosmosdb/metrics_test.go
  pkg/metrics/statsd/golang/metrics.go
  pkg/metrics/statsd/k8s/metrics.go
  pkg/metrics/statsd/k8s/metrics_test.go
  pkg/metrics/statsd/statsd.go
  pkg/monitor/cluster/arooperatorheartbeat_test.go
  pkg/monitor/cluster/cluster.go
  pkg/monitor/cluster/clusteroperatorconditions_test.go
  pkg/monitor/cluster/clusteroperatorversions_test.go
  pkg/monitor/cluster/clusterversionconditions_test.go
  pkg/monitor/cluster/clusterversions_test.go
  pkg/monitor/cluster/daemonsetstatuses_test.go
  pkg/monitor/cluster/deploymentstatuses_test.go
  pkg/monitor/cluster/jobconditions_test.go
  pkg/monitor/cluster/machineconfigpool_test.go
  pkg/monitor/cluster/machineconfigpoolconditions_test.go
  pkg/monitor/cluster/nodeconditions_test.go
  pkg/monitor/cluster/podconditions_test.go
  pkg/monitor/cluster/replicasetstatuses_test.go
  pkg/monitor/cluster/statefulsetstatuses_test.go
  pkg/monitor/cluster/summary_test.go
  pkg/monitor/monitor.go
  pkg/portal/portal.go
  pkg/util/clusterdata/clusterdata.go
  pkg/util/heartbeat/heartbeat.go
  pkg/util/mocks/metrics/metrics.go
Labels: size-small, ready-for-review

#2058 updated path to quota file
  pkg/api/openshiftcluster.go
Labels: ready-for-review

#2027 Commit to allow password auth for VMSS jit access
  deploy/gateway-production.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
Labels: ready-for-review

#2084 Update pull secret references from cloud.redhat.com to cloud.openshift.com
  pkg/operator/controllers/muo/muo_controller.go
  pkg/operator/controllers/pullsecret/pullsecret_controller.go
  pkg/operator/controllers/pullsecret/pullsecret_controller_test.go
Labels: ready-for-review, next-release

#2081 Enables go fmt simplify in golangci config
  .golangci.yml
Labels: ready-for-review

#2059 redesigned the quota computation to something understandable
  pkg/api/validate/dynamic/quota.go
Labels: size-small, ready-for-review

#2087 Bump 4.9 install image to latest stable 4.9.28 to address etcd split brain issue
  pkg/operator/controllers/rbac/bindata.go
  pkg/operator/controllers/rbac/staticresources/clusterrole.yaml
  pkg/util/dynamichelper/discovery/bindata.go
  pkg/util/dynamichelper/discovery/cache/assets_version
  pkg/util/dynamichelper/discovery/cache/servergroups.json
  pkg/util/dynamichelper/discovery/cache/upgrade.managed.openshift.io/v1alpha1/serverresources.json
  pkg/util/version/const.go
Labels: next-release

#2065 Fail MUO test if we expect an error but don't get one
  pkg/operator/controllers/muo/muo_controller_test.go
Labels: ready-for-review

#2088 Bump fluentbit, mdm, and mdsd images to mitigate P0/P1s
  Makefile
  deploy/gateway-production.json
  deploy/rp-production.json
  pkg/deploy/bindata.go
  pkg/util/version/const.go
Labels: next-release
