Repository Azure/ARO-RP, pull requests merged in 2023-08, with the labels that each got.

#2936 Remove the provisioning state check around ensure managed rg
  pkg/cluster/deploybaseresources.go
  pkg/cluster/deploybaseresources_test.go
Labels: ready-for-review, next-release

#3070 Move pkg/api dependencies on util/subnet to api/util/subnet
  .golangci.yml
  pkg/api/util/subnet/const.go
  pkg/api/util/subnet/subnet.go
  pkg/api/util/subnet/subnet_test.go
  pkg/api/v20191231preview/openshiftcluster_validatestatic.go
  pkg/api/v20200430/openshiftcluster_validatestatic.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic.go
  pkg/api/v20220401/openshiftcluster_validatestatic.go
  pkg/api/v20220401/openshiftcluster_validatestatic_test.go
  pkg/api/v20220904/openshiftcluster_validatestatic.go
  pkg/api/v20220904/openshiftcluster_validatestatic_test.go
  pkg/api/v20230401/openshiftcluster_validatestatic.go
  pkg/api/v20230401/openshiftcluster_validatestatic_test.go
  pkg/api/v20230701preview/openshiftcluster_validatestatic.go
  pkg/api/v20230701preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20230904/openshiftcluster_validatestatic.go
  pkg/cluster/deploybaseresources.go
  pkg/cluster/nsg.go
  pkg/frontend/adminactions/resources_list.go
  pkg/operator/controllers/subnets/subnet_controller_test.go
  pkg/operator/controllers/subnets/subnet_nsg.go
  pkg/operator/deploy/deploy.go
  pkg/util/subnet/cluster_subnets.go
  pkg/util/subnet/subnet.go
  pkg/util/subnet/subnet_test.go
  pkg/validate/dynamic/dynamic.go
  test/e2e/adminapi_resources.go
  test/e2e/operator.go
Labels: ready-for-review, go, skippy

#3082 Pin to selenium grid 4.10
  hack/e2e/run-rp-and-e2e.sh
Labels: bug, priority-high, next-up

#3068 Aro 2998 monitoring errors
  pkg/operator/controllers/monitoring/monitoring_controller.go
  pkg/operator/controllers/monitoring/monitoring_controller_test.go
Labels: size-small, ready-for-review, loki

#3079 Move pkg/api dependencies on util/immutable to api/util/immutable
  pkg/api/admin/openshiftcluster_validatestatic.go
  pkg/api/admin/openshiftversion_validatestatic.go
  pkg/api/util/immutable/immutable.go
  pkg/api/util/immutable/immutable_test.go
  pkg/api/v20191231preview/openshiftcluster_validatestatic.go
  pkg/api/v20200430/openshiftcluster_validatestatic.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic.go
  pkg/api/v20220401/openshiftcluster_validatestatic.go
  pkg/api/v20220904/openshiftcluster_validatestatic.go
  pkg/api/v20230401/openshiftcluster_validatestatic.go
  pkg/api/v20230701preview/openshiftcluster_validatestatic.go
  pkg/api/v20230904/openshiftcluster_validatestatic.go
Labels: ready-for-review, go, skippy

#3088 Update RegistryProfile with new ACR token password once rotated
  pkg/cluster/acrtoken.go
Labels: bug, ready-for-review, next-release, chainsaw

#3106 Bumping the MDSD MDM Fluentbit images in RP
  cmd/aro/mirror.go
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/util/version/const.go
Labels: next-release

#3114 Add priority deletion ordering of nested Microsoft.Compute/galleries resources
  pkg/cluster/delete.go
Labels: next-release

#3080 use restricted scc for gatekeeper-manager-role
  pkg/operator/controllers/guardrails/config/config.go
  pkg/operator/controllers/guardrails/guardrails_config.go
  pkg/operator/controllers/guardrails/guardrails_controller_test.go
  pkg/operator/controllers/guardrails/staticresources/gk_audit_controller_deployment.yaml
  pkg/operator/controllers/guardrails/staticresources/gk_cluster_role.yaml
  pkg/operator/controllers/guardrails/staticresources/gk_controller_manager_deployment.yaml
  pkg/operator/controllers/guardrails/staticresources/gk_role.yaml
Labels: ready-for-review, next-release, skippy

#3087 Remove gvrresolver use in the frontend
  pkg/frontend/admin_openshiftcluster_approvecsr.go
  pkg/frontend/admin_openshiftcluster_cordonnode.go
  pkg/frontend/admin_openshiftcluster_drainnode.go
  pkg/frontend/admin_openshiftcluster_etcdrecovery.go
  pkg/frontend/admin_openshiftcluster_etcdrecovery_test.go
  pkg/frontend/admin_openshiftcluster_kubernetesobjects.go
  pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go
  pkg/frontend/adminactions/kubeactions.go
  pkg/frontend/validate.go
  pkg/frontend/validate_test.go
  pkg/util/mocks/adminactions/adminactions.go
Labels: ready-for-review, go, skippy

#3044 Remove install word in Condition error messages
  pkg/util/steps/condition.go
  pkg/util/steps/condition_test.go
Labels: size-small, ready-for-review, next-release, skippy

#3060 Unplanned Maintenance Signals
  cmd/aro/rp.go
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/scripts/rpVMSS.sh
  pkg/frontend/admin_hive_clusterdeployment_get_test.go
  pkg/frontend/admin_openshiftcluster_approvecsr_test.go
  pkg/frontend/admin_openshiftcluster_cordonnode_test.go
  pkg/frontend/admin_openshiftcluster_drainnode_test.go
  pkg/frontend/admin_openshiftcluster_etcdrecovery_test.go
  pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go
  pkg/frontend/admin_openshiftcluster_kubernetespods_logs_test.go
  pkg/frontend/admin_openshiftcluster_list_test.go
  pkg/frontend/admin_openshiftcluster_redeployvm_test.go
  pkg/frontend/admin_openshiftcluster_resources_list_test.go
  pkg/frontend/admin_openshiftcluster_startvm_test.go
  pkg/frontend/admin_openshiftcluster_stopvm_test.go
  pkg/frontend/admin_openshiftcluster_vmresize_test.go
  pkg/frontend/admin_openshiftcluster_vmsizelist_test.go
  pkg/frontend/admin_openshiftversion_list_test.go
  pkg/frontend/admin_openshiftversion_put_test.go
  pkg/frontend/asyncoperationresult_get_test.go
  pkg/frontend/asyncoperationsstatus_get_test.go
  pkg/frontend/clustermanager_delete_test.go
  pkg/frontend/clustermanager_get_test.go
  pkg/frontend/clustermanager_putorpatch_test.go
  pkg/frontend/fixetcd_test.go
  pkg/frontend/frontend.go
  pkg/frontend/middleware/maintenance.go
  pkg/frontend/middleware/maintenance_test.go
  pkg/frontend/openshiftcluster_applensdetectors_test.go
  pkg/frontend/openshiftcluster_delete_test.go
  pkg/frontend/openshiftcluster_get_test.go
  pkg/frontend/openshiftcluster_list_test.go
  pkg/frontend/openshiftcluster_preflightvalidation_test.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/frontend/openshiftclustercredentials_post_test.go
  pkg/frontend/openshiftclusterkubeconfigcredentials_post_test.go
  pkg/frontend/openshiftversions_list_test.go
  pkg/frontend/security_test.go
  pkg/frontend/subscriptions_put_test.go
Labels: ready-for-review, next-release, go

#3123 Remove the unneeded replace for hive
  go.mod
  vendor/modules.txt
Labels: next-up, ready-for-review, go, skippy

#3069 ARO-3112: Set DisableOutbound SNAT to true on Load Balancers
  cmd/aro/operator.go
  pkg/api/defaults.go
  pkg/operator/controllers/cloudproviderconfig/cloudproviderconfig_controller.go
  pkg/operator/controllers/cloudproviderconfig/cloudproviderconfig_controller_test.go
  test/e2e/operator.go
Labels: next-up, next-release, loki

#3120 add aro-monitor and aro-portal restart to predeploy steps
  pkg/deploy/predeploy.go
Labels: next-release, chainsaw

#3113 Fix credential rotation failure
  pkg/cluster/clusterserviceprincipal.go
  pkg/cluster/clusterserviceprincipal_test.go
Labels: chainsaw

#3095 multiple ARO managed public IPs per Load balancer during cluster update
  pkg/cluster/install.go
  pkg/cluster/loadbalancerprofile.go
  pkg/cluster/loadbalancerprofile_test.go
  pkg/util/azureclient/mgmt/network/generate.go
  pkg/util/azureclient/mgmt/network/loadbalancers.go
  pkg/util/azureclient/mgmt/network/publicipaddresses_addons.go
  pkg/util/mocks/azureclient/mgmt/network/network.go
  pkg/util/mocks/dynamic/dynamic.go
  pkg/util/uuid/fake/fake_uuid.go
  pkg/validate/dynamic/dynamic.go
  pkg/validate/dynamic/loadbalancerprofile.go
  pkg/validate/dynamic/loadbalancerprofile_test.go
  pkg/validate/openshiftcluster_validatedynamic.go
Labels: next-up, ready-for-review, next-release, loki

#3127 Specify the resource manager endpoint for the lb backend pool client
  pkg/util/azureclient/mgmt/network/loadbalancers.go
Labels: bug, ready-for-review, next-release

#3091 Remove upgrades from the Admin API
  pkg/frontend/admin_openshiftcluster_upgrade.go
  pkg/frontend/adminactions/kubeactions.go
  pkg/frontend/adminactions/upgrade.go
  pkg/frontend/adminactions/upgrade_test.go
  pkg/frontend/frontend.go
  pkg/util/mocks/adminactions/adminactions.go
Labels: next-up, ready-for-review, go, skippy

#3130 added guardrails namespace
  pkg/util/namespace/namespace.go
  pkg/util/namespace/namespace_test.go
Labels: size-small, ready-for-review, next-release, skippy

#3092 Remove old upgradestreams logic from the monitor & old parts of the RP
  cmd/aro/update_ocp_versions.go
  pkg/deploy/saveversion.go
  pkg/monitor/cluster/clusterversions.go
  pkg/monitor/cluster/clusterversions_test.go
  pkg/util/version/const.go
  pkg/util/version/stream.go
  pkg/util/version/stream_test.go
Labels: ready-for-review, go, skippy

#3128 Fix .gitignore for kubeconfigs
  .gitignore
Labels: ready-for-review, chainsaw

#3129 Reduce flakes in TestLoadBalancerProfile()
  pkg/cluster/loadbalancerprofile_test.go
Labels: size-small, ready-for-review, loki

#3133 increase machine health check node unready timeout to 15m
  pkg/operator/controllers/machinehealthcheck/doc.go
  pkg/operator/controllers/machinehealthcheck/staticresources/machinehealthcheck.yaml
Labels: ready-for-review, next-release, chainsaw

#3126 Mirror the hive version we intend to upgrade to
  cmd/aro/mirror.go
Labels: ready-for-review, chainsaw
