Repository Azure/ARO-RP, pull requests merged in 2023-04, with the labels that each got.

#2508 add param names to Emitter's interface methods and unify naming
  pkg/cluster/install.go
  pkg/cluster/install_test.go
  pkg/metrics/metrics.go
  pkg/metrics/noop/noop.go
  pkg/metrics/statsd/metrics.go
  pkg/metrics/statsd/metrics_test.go
  pkg/metrics/statsd/statsd.go
  pkg/util/steps/action.go
  pkg/util/steps/condition.go
  pkg/util/steps/refreshing.go
  pkg/util/steps/runner.go
  pkg/util/steps/runner_test.go
Labels: ready-for-review

#2831 Rename deploystorage to deploybaseresource
  pkg/cluster/deploybaseresources.go
  pkg/cluster/deploybaseresources_additional.go
  pkg/cluster/deploybaseresources_test.go
  pkg/cluster/install.go
Labels: ready-for-review

#2839 Update dev proxy instance type
  pkg/deploy/assets/env-development.json
  pkg/deploy/generator/resources_dev.go
Labels: ready-for-review

#2829 fix minor doc issues
  docs/deploy-development-rp.md
Labels: documentation

#2832 Fix `clean_e2e_db` not running in CI when e2e fails
  .pipelines/e2e.yml
Labels: ready-for-review

#2841 Geneva MDM Domain Change for INT in hack+devconfig
  hack/local-monitor-testing/deploy_MDM_VM.sh
  hack/local-monitor-testing/samples/dockerStartCommand-UDP.sh
  hack/local-monitor-testing/samples/dockerStartCommand.sh
  pkg/deploy/devconfig.go
Labels: size-small, ready-for-review, skippy

#2735 Fixing External LoadBalancer Backend Address Pool after Master node replacement
  pkg/cluster/fixssh.go
  pkg/cluster/fixssh_test.go
Labels: firefly

#2674 Created Cluster Health Dashboard in Admin Portal
  go.sum
  pkg/portal/assets/v2/build/asset-manifest.json
  pkg/portal/assets/v2/build/index.html
  pkg/portal/assets/v2/build/static/js/main.61fbb3a0.js
  pkg/portal/assets/v2/build/static/js/main.61fbb3a0.js.map
  pkg/portal/assets/v2/build/static/js/main.dfd095e3.js
  pkg/portal/assets/v2/build/static/js/main.dfd095e3.js.LICENSE.txt
  pkg/portal/assets/v2/build/static/js/main.dfd095e3.js.map
  pkg/portal/cluster.go
  pkg/portal/cluster/fetcher.go
  pkg/portal/cluster/statistics.go
  pkg/portal/cluster_info.go
  pkg/portal/portal.go
  pkg/portal/prometheus/proxy.go
  portal/v1/package-lock.json
  portal/v2/package-lock.json
  portal/v2/package.json
  portal/v2/src/App.tsx
  portal/v2/src/ClusterDetail.tsx
  portal/v2/src/ClusterDetailList.tsx
  portal/v2/src/ClusterDetailListComponents/MachineSetsWrapper.tsx
  portal/v2/src/ClusterDetailListComponents/MachinesWrapper.tsx
  portal/v2/src/ClusterDetailListComponents/NodesWrapper.tsx
  portal/v2/src/ClusterDetailListComponents/OverviewWrapper.tsx
  portal/v2/src/ClusterDetailListComponents/Statistics/GraphOptionsComponent.tsx
  portal/v2/src/ClusterDetailListComponents/Statistics/Statistics.tsx
  portal/v2/src/ClusterDetailListComponents/Statistics/StatisticsComponent.tsx
  portal/v2/src/ClusterDetailListComponents/Statistics/StatisticsWrapper.tsx
  portal/v2/src/ClusterList.tsx
  portal/v2/src/Request.tsx
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/modules.txt
Labels: ready-for-review, firefly

#2826 Allow aro operator to tolerate noschedule and noexecute
  pkg/operator/deploy/staticresources/master/deployment.yaml.tmpl
  pkg/operator/deploy/staticresources/worker/deployment.yaml.tmpl
Labels: ready-for-review

#2779 Use CheckAccess with AFEC to test in INT and Canary regions
  pkg/api/validate/dynamic/dynamic.go
  pkg/api/validate/dynamic/dynamic_test.go
  pkg/api/validate/openshiftcluster_validatedynamic.go
  pkg/util/mocks/azureclient/authz/remotepdp/remotepdp.go
  pkg/util/mocks/azureclient/azuresdk/azcore/tokencredential.go
  pkg/util/token/inspect.go
  pkg/util/token/inspect_test.go
Labels: ready-for-review

#2846 pkg/deploy: Caller provides an appropriate TokenCredential
  cmd/aro/deploy.go
  pkg/deploy/deploy.go
Labels: bug, ready-for-review

#2848 Fix mock reproducibility
  pkg/api/generate.go
  pkg/util/azureclient/authz/remotepdp/generate.go
  pkg/util/azureclient/azuresdk/azcore/generate.go
  pkg/util/azureclient/azuresdk/azcore/tokencredential.go
  pkg/util/clusterdata/generate.go
  pkg/util/mocks/api/api.go
  pkg/util/mocks/azureclient/authz/remotepdp/remotepdp.go
  pkg/util/mocks/azureclient/azuresdk/azcore/tokencredential.go
  pkg/util/mocks/clusterdata/clusterdata.go
  pkg/util/mocks/openshiftcluster/openshiftcluster.go
  pkg/util/mocks/refreshable/refreshable.go
Labels: next-up, ready-for-review, go, skippy

#2849 Update mirror image syncs to the latest versions
  cmd/aro/mirror.go
  go.mod
  go.sum
  vendor/golang.org/x/exp/LICENSE
  vendor/golang.org/x/exp/PATENTS
  vendor/golang.org/x/exp/constraints/constraints.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/exp/slices/zsortfunc.go
  vendor/golang.org/x/exp/slices/zsortordered.go
  vendor/golang.org/x/mod/modfile/read.go
  vendor/golang.org/x/mod/modfile/rule.go
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/tools/go/ast/inspector/typeof.go
  vendor/golang.org/x/tools/go/gcexportdata/gcexportdata.go
  vendor/golang.org/x/tools/go/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/ureader_yes.go
  vendor/golang.org/x/tools/go/internal/pkgbits/decoder.go
  vendor/golang.org/x/tools/go/internal/pkgbits/encoder.go
  vendor/golang.org/x/tools/go/internal/pkgbits/reloc.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_darwin.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_dirent_ino.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_dirent_namlen_bsd.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_unix.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/zstdlib.go
  vendor/modules.txt
Labels: next-up, ready-for-review, skippy

#2838 Add pki util to get certs that are used for applens
  pkg/frontend/adminactions/azureactions.go
  pkg/util/azureclient/applens/applens.go
  pkg/util/azureclient/applens/applens_client.go
  pkg/util/azureclient/applens/applens_client_options.go
  pkg/util/azureclient/environments.go
  pkg/util/pki/pki.go
  pkg/util/pki/pki_test.go
Labels: ready-for-review

#2853 Remove Standard_D96s_v4 and Standard_E96s_v4
  pkg/api/admin/openshiftcluster.go
  pkg/api/openshiftcluster.go
  pkg/api/validate/vm.go
Labels: ready-for-review, next-release

#2866 Nitpick update vm.go
  pkg/api/validate/vm.go
Labels: firefly

#2861 Func to list SupportedVMSizesByRole
  pkg/api/validate/vm.go
  pkg/frontend/admin_supportvmsizes_list.go
  pkg/frontend/validate.go
Labels: ready-for-review, skippy

#2819 Improve error check on failed RP deployment
  pkg/deploy/deploy.go
  pkg/deploy/deploy_test.go
  pkg/deploy/upgrade_gateway.go
  pkg/deploy/upgrade_rp.go
Labels: ready-for-review

#2805 Extract CosmosDB throughput configuration to ARM template parameters
  pkg/deploy/assets/databases-development.json
  pkg/deploy/assets/rp-production-parameters.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/config.go
  pkg/deploy/deploy_rp.go
  pkg/deploy/devconfig.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/templates.go
  pkg/deploy/generator/templates_rp.go
Labels: ready-for-review, loki

#2587 Add operator info admin portal
  pkg/portal/assets/v2/build/asset-manifest.json
  pkg/portal/assets/v2/build/index.html
  pkg/portal/assets/v2/build/static/js/main.0b4eab3b.js
  pkg/portal/assets/v2/build/static/js/main.0b4eab3b.js.LICENSE.txt
  pkg/portal/assets/v2/build/static/js/main.0b4eab3b.js.map
  pkg/portal/assets/v2/build/static/js/main.d84ac680.js
  pkg/portal/assets/v2/build/static/js/main.d84ac680.js.LICENSE.txt
  pkg/portal/cluster/clusteroperators.go
  pkg/portal/cluster/clusteroperators_test.go
  portal/v2/package-lock.json
  portal/v2/src/ClusterDetail.tsx
  portal/v2/src/ClusterDetailList.tsx
  portal/v2/src/ClusterDetailListComponents/ClusterOperator.tsx
  portal/v2/src/ClusterDetailListComponents/ClusterOperatorList.tsx
  portal/v2/src/ClusterDetailListComponents/ClusterOperatorsWrapper.tsx
  portal/v2/src/ClusterDetailListComponents/MachineSetsList.tsx
  portal/v2/src/ClusterDetailListComponents/MachineSetsWrapper.tsx
  portal/v2/src/ClusterDetailListComponents/MachinesList.tsx
  portal/v2/src/ClusterDetailListComponents/MachinesWrapper.tsx
  portal/v2/src/ClusterDetailListComponents/Nodes.tsx
  portal/v2/src/ClusterDetailListComponents/NodesList.tsx
  portal/v2/src/ClusterDetailListComponents/NodesWrapper.tsx
  portal/v2/src/Request.tsx
  portal/v2/src/Utilities.tsx
Labels: ready-for-review, firefly

#2855 Update to use new fluentbit, mdm, and mdsd
  Dockerfile.muo
  cmd/aro/mirror.go
  go.mod
  go.sum
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/util/version/const.go
  vendor/golang.org/x/exp/LICENSE
  vendor/golang.org/x/exp/PATENTS
  vendor/golang.org/x/exp/constraints/constraints.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/exp/slices/zsortfunc.go
  vendor/golang.org/x/exp/slices/zsortordered.go
  vendor/modules.txt
Labels: next-up, ready-for-review, next-release, skippy

#2856 Clean up some of the portal v2 config
  portal/v2/.npmrc
  portal/v2/package-lock.json
  portal/v2/package.json
Labels: ready-for-review, javascript
