Repository Azure/ARO-RP, pull requests merged in 2023-01, with the labels that each got.

#2628 Update to new MUO image
  cmd/aro/mirror.go
Labels: next-up, next-release, skippy

#2347 Sync AKS Dev deployment with production
  hack/devtools/deploy-shared-env.sh
  pkg/deploy/assets/aks-development.json
Labels: ready-for-review

#2634 logs added for frontend enrichment
  pkg/frontend/frontend.go
  pkg/frontend/openshiftcluster_delete.go
  pkg/frontend/openshiftcluster_get.go
  pkg/frontend/openshiftcluster_putorpatch.go
Labels: ready-for-review

#2624 Switch CI to running on 1ES
  .pipelines/ci.yml
  .pipelines/templates/template-checkout.yml
Labels: ready-for-review, skippy

#2630 Optionally deallocate a VM after performing a graceful stop VM action
  docs/deploy-development-rp.md
  pkg/frontend/admin_openshiftcluster_stopvm.go
  pkg/frontend/admin_openshiftcluster_stopvm_test.go
  pkg/frontend/adminactions/azureactions.go
  pkg/util/azureclient/mgmt/compute/virtualmachines_addons.go
  pkg/util/mocks/adminactions/adminactions.go
  pkg/util/mocks/azureclient/mgmt/compute/compute.go
Labels: ready-for-review

#2518 Switch to RHEL 8 for the RP and Gateway VMs
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/scripts/gatewayVMSS.sh
  pkg/deploy/generator/scripts/rpVMSS.sh
Labels: ready-for-review

#2616 decoupling functions from mux.Vars() in frontend
  pkg/frontend/asyncoperations.go
  pkg/frontend/clustermanager_get.go
  pkg/frontend/clustermanager_putorpatch.go
  pkg/frontend/openshiftcluster_delete.go
  pkg/frontend/openshiftcluster_putorpatch.go
Labels: ready-for-review

#2433 Test hive CreateNamespace in e2e
  test/e2e/aks.go
  test/e2e/hive_manager.go
  test/e2e/setup.go
Labels: size-small, ready-for-review

#2611 aad session expiration simplification
  hack/portalauth/portalauth.go
  pkg/portal/middleware/aad.go
  pkg/portal/middleware/aad_test.go
  pkg/portal/security_test.go
  test/e2e/setup.go
Labels: ready-for-review

#2631 e2e test for Hive-managed ARO clusters
  test/e2e/adminapi_cluster_get.go
  test/e2e/adminapi_cluster_getlogs.go
  test/e2e/adminapi_cluster_list.go
  test/e2e/adminapi_cluster_update.go
  test/e2e/adminapi_csr.go
  test/e2e/adminapi_drainnode.go
  test/e2e/adminapi_kubernetesobjects.go
  test/e2e/adminapi_redeployvm.go
  test/e2e/adminapi_resources.go
  test/e2e/hive.go
  test/e2e/setup.go
Labels: ready-for-review

#2044 Keynotfound empty subnet sp rotation
  python/az/aro/azext_aro/custom.py
Labels: ready-for-review, skippy

#2654 Run CI on the 1es-aro-ci-pool pool
  .pipelines/ci.yml
Labels: priority-high, next-up, skippy

#2482 add MUO reconciliation E2E test
  test/e2e/operator.go
Labels: size-small, ready-for-review

#2649 Update subnet generation for local dev
  pkg/util/cluster/cluster.go
Labels: ready-for-review

#2644 Fix/do not adopt hive created clusters during pucm
  pkg/api/admin/openshiftcluster.go
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/openshiftcluster.go
  pkg/cluster/adminupdate_test.go
  pkg/cluster/cluster.go
  pkg/cluster/install.go
  pkg/cluster/install_test.go
  pkg/cluster/install_version.go
  pkg/cluster/install_version_test.go
  pkg/cluster/version.go
  pkg/hive/install.go
Labels: next-up, ready-for-review, next-release

#2532 fix/delete usage of flags at package-level and include Go test direct…
  .gitignore
  Makefile
  hack/aead/aead.go
  hack/clean/clean.go
  hack/fakecluster/fakecluster.go
  hack/genkey/genkey.go
  hack/portalauth/portalauth.go
  hack/proxy/proxy.go
  hack/tunnel/tunnel.go
Labels: ready-for-review

#2651 Bump image mirror tags
  cmd/aro/mirror.go
Labels: next-up, ready-for-review, next-release

#2664 update docs: configure local ARO-RP to create clusters using a Hive d…
  docs/deploy-development-rp.md
Labels: ready-for-review

#2663 replaced deprecated gorilla with standard library
  pkg/dbtoken/server.go
  pkg/dbtoken/server_test.go
Labels: ready-for-review

#2638 Migrate E2E to 1ES pool
  .gitignore
  .pipelines/e2e.yml
  .pipelines/templates/template-push-images-to-acr.yml
  .pipelines/vars.yml
  Dockerfile.aro-e2e
  Dockerfile.aro-multistage
  Makefile
  hack/ci-utils/extractaro.sh
  hack/e2e/run-rp-and-e2e.sh
  hack/get-admin-kubeconfig.sh
  pkg/hive/install.go
  pkg/proxy/dialer.go
  test/e2e/setup.go
Labels: next-up, ready-for-review, skippy

#2621 Update dedicated RP deployment docs to include AKS, VPN, and Hive
  docs/deploy-full-rp-service-in-dev.md
  hack/devtools/deploy-shared-env.sh
  pkg/deploy/assets/vpn-development.json
Labels: ready-for-review

#2669 Update the list of AKS denied regions
  test/e2e/aks.go
Labels: ready-for-review
