Repository Azure/ARO-RP, pull requests merged in 2023-06, with the labels that each got.

#2852 [Bugfix] Remove alert to pop up when double clicking a cluster in the cluster list
  pkg/portal/assets/v2/build/asset-manifest.json
  pkg/portal/assets/v2/build/index.html
  pkg/portal/assets/v2/build/static/js/main.6f933290.js
  pkg/portal/assets/v2/build/static/js/main.6f933290.js.LICENSE.txt
  pkg/portal/assets/v2/build/static/js/main.a2b8e019.js
  pkg/portal/assets/v2/build/static/js/main.a2b8e019.js.LICENSE.txt
  portal/v2/src/ClusterList.tsx
Labels: firefly

#2693 Refactor/env vars access
  cmd/aro/const.go
  cmd/aro/dbtoken.go
  cmd/aro/deploy.go
  cmd/aro/gateway.go
  cmd/aro/main.go
  cmd/aro/mirror.go
  cmd/aro/monitor.go
  cmd/aro/portal.go
  cmd/aro/rp.go
  cmd/aro/update_ocp_versions.go
  hack/aead/aead.go
  hack/clean/clean.go
  hack/cluster/cluster.go
  hack/db/db.go
  hack/gendevconfig/gendevconfig.go
  hack/portalauth/portalauth.go
  pkg/database/asyncoperations.go
  pkg/database/billing.go
  pkg/database/clustermanager.go
  pkg/database/database.go
  pkg/database/gateway.go
  pkg/database/monitors.go
  pkg/database/openshiftclusters.go
  pkg/database/openshiftversions.go
  pkg/database/portal.go
  pkg/database/subscriptions.go
  pkg/dbtoken/client.go
  pkg/dbtoken/refresher.go
  pkg/env/dev.go
  pkg/env/env.go
  pkg/env/msiauthorizer.go
  pkg/env/prod.go
  pkg/util/cluster/cluster.go
  pkg/util/keyvault/uri.go
  test/e2e/setup.go
Labels: ready-for-review

#2823 Draft PR for Preflight validation
  pkg/api/preflight.go
  pkg/frontend/frontend.go
  pkg/frontend/middleware/validate_api.go
  pkg/frontend/openshiftcluster_preflightvalidation.go
  pkg/frontend/openshiftcluster_preflightvalidation_test.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/frontend/validate.go
  test/database/check.go
  test/database/openshiftclusters.go
Labels: ready-for-review, next-release

#2927 Update gatekeeper dockerfile to ensure cgo is enabled
  Dockerfile.gatekeeper
Labels: ready-for-review

#2930 Set a default value for checkaccess
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/templates_rp.go
Labels: ready-for-review, next-release

#2920 Updated OutboundType to include comment for Swagger generation - Updated Swagger Readmes
  .sha256sum
  pkg/api/admin/openshiftcluster.go
  pkg/api/v20230401/openshiftcluster.go
  pkg/swagger/generator.go
  python/client/azure/mgmt/redhatopenshift/v2023_04_01/models/_azure_red_hat_open_shift_client_enums.py
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2023-04-01/redhatopenshift.json
  swagger/redhatopenshift/resource-manager/readme.go.md
  swagger/redhatopenshift/resource-manager/readme.md
  swagger/redhatopenshift/resource-manager/readme.python.md
Labels: ready-for-review

#2933 Always log error (if applicable) on failed deployment attempts
  pkg/deploy/deploy.go
Labels: ready-for-review

#2851 Reconcile upstream changes / remove Network SDK
  Makefile
  python/az/aro/azext_aro/__init__.py
  python/az/aro/azext_aro/_dynamic_validators.py
  python/az/aro/azext_aro/_params.py
  python/az/aro/azext_aro/_validators.py
  python/az/aro/azext_aro/aaz/__init__.py
  python/az/aro/azext_aro/aaz/latest/__init__.py
  python/az/aro/azext_aro/aaz/latest/network/__cmd_group.py
  python/az/aro/azext_aro/aaz/latest/network/__init__.py
  python/az/aro/azext_aro/aaz/latest/network/vnet/__cmd_group.py
  python/az/aro/azext_aro/aaz/latest/network/vnet/__init__.py
  python/az/aro/azext_aro/aaz/latest/network/vnet/_show.py
  python/az/aro/azext_aro/aaz/latest/network/vnet/subnet/__cmd_group.py
  python/az/aro/azext_aro/aaz/latest/network/vnet/subnet/__init__.py
  python/az/aro/azext_aro/aaz/latest/network/vnet/subnet/_show.py
  python/az/aro/azext_aro/custom.py
  python/az/aro/azext_aro/tests/latest/unit/test_dynamic_validators.py
  python/az/aro/azext_aro/tests/latest/unit/test_validators.py
Labels: ready-for-review, loki

#2844 Force Resize option in Master Resize GA
  pkg/frontend/admin_openshiftcluster_vmresize.go
  pkg/frontend/admin_openshiftcluster_vmresize_test.go
  pkg/frontend/adminactions/azureactions.go
  pkg/util/mocks/adminactions/adminactions.go
Labels: ready-for-review, next-release, skippy

#2944 Use refreshing actions on validateResources during Update()
  pkg/cluster/adminupdate_test.go
  pkg/cluster/install.go
  pkg/cluster/serviceprincipal.go
Labels: next-release

#2937 Remove AZURE_ARM_CLIENT_SECRET helper
  pkg/env/armhelper.go
Labels: ready-for-review

#2932 [ARO-3194] Vendor dnsmasq into the operator
  go.mod
  pkg/operator/controllers/dnsmasq/cluster_controller.go
  pkg/operator/controllers/dnsmasq/dnsmasq.go
Labels: next-up, ready-for-review, operator, skippy

#2966 Remove non-current Azure SDK dependencies from being considered
  go.mod
  go.sum
Labels: size-small, ready-for-review, dependencies, go, skippy

#2939 Propagate errors of ARO ImageConfig controller to ARO Operator
  pkg/operator/controllers/imageconfig/image_controller.go
  pkg/operator/controllers/imageconfig/image_controller_test.go
Labels: size-small, ready-for-review, skippy

#2978 Increase gateway VMSS disk storage
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/scripts/gatewayVMSS.sh
  pkg/deploy/generator/scripts/rpVMSS.sh
Labels: ready-for-review, next-release

#2997 AutoSized Nodes now reference both masters and workers
  pkg/operator/controllers/autosizednodes/autosizednodes_controller.go
  pkg/operator/controllers/autosizednodes/autosizednodes_controller_test.go
Labels: ready-for-review, next-release
