Repository Azure/ARO-RP, pull requests merged in 2023-02, with the labels that each got.

#2537 While create if cluster exists check provisioning state
  pkg/util/cluster/cluster.go
Labels: ready-for-review, skippy

#2661 Add validation and unrestricted endpoint for kubernetes objects
  pkg/frontend/admin_openshiftcluster_approvecsr.go
  pkg/frontend/admin_openshiftcluster_cordonnode.go
  pkg/frontend/admin_openshiftcluster_drainnode.go
  pkg/frontend/admin_openshiftcluster_kubernetesobjects.go
  pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go
  pkg/frontend/adminactions/kubeactions.go
  pkg/frontend/frontend.go
  pkg/frontend/validate.go
  pkg/frontend/validate_test.go
  pkg/util/dynamichelper/gvrresolver.go
  pkg/util/dynamichelper/gvrresolver_test.go
  pkg/util/mocks/adminactions/adminactions.go
  test/e2e/adminapi_kubernetesobjects.go
Labels: ready-for-review, next-release

#2460 toil: metrics for nonstandard cluster support status
  pkg/monitor/cluster/cluster.go
  pkg/monitor/cluster/clusterflagsandbanner.go
  pkg/monitor/cluster/clusterflagsandbanner_test.go
  pkg/operator/controllers/monitoring/monitoring_controller.go
Labels: size-medium, ready-for-review, skippy

#2653 Update old dbtoken-service documentation
  docs/dbtoken-service.md
  docs/prepare-a-shared-rp-development-environment.md
Labels: ready-for-review

#2681 Added new instance type
  pkg/api/openshiftcluster.go
  pkg/api/validate/vm.go
Labels: ready-for-review, skippy

#2676 Renew MDSD certs on az-aro-update
  pkg/cluster/install.go
Labels: ready-for-review, skippy

#2699 Update the default fluentbit image to 1.9.9
  pkg/util/version/const.go
Labels: next-up, ready-for-review, next-release

#2166 To detect and show the unsupported conditions on the console banner
  go.mod
  go.sum
  pkg/operator/controllers/checkers/internetchecker/unsupportedconditionchecker.go
  pkg/operator/controllers/checkers/internetchecker/unsupportedconditionchecker_test.go
  vendor/github.com/openshift/api/console/v1alpha1/0000_10_consoleplugin.crd.yaml
  vendor/github.com/openshift/api/console/v1alpha1/doc.go
  vendor/github.com/openshift/api/console/v1alpha1/register.go
  vendor/github.com/openshift/api/console/v1alpha1/types.go
  vendor/github.com/openshift/api/console/v1alpha1/types_console_plugin.go
  vendor/github.com/openshift/api/console/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/console/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1/console_client.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1/consoleclidownload.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1/consoleexternalloglink.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1/consolelink.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1/consolenotification.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1/consolequickstart.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1/consoleyamlsample.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1/doc.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1/fake/doc.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1/fake/fake_console_client.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1/fake/fake_consoleclidownload.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1/fake/fake_consoleexternalloglink.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1/fake/fake_consolelink.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1/fake/fake_consolenotification.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1/fake/fake_consolequickstart.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1/fake/fake_consoleyamlsample.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1alpha1/console_client.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1alpha1/consoleplugin.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1alpha1/doc.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1alpha1/fake/doc.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1alpha1/fake/fake_console_client.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1alpha1/fake/fake_consoleplugin.go
  vendor/github.com/openshift/client-go/console/clientset/versioned/typed/console/v1alpha1/generated_expansion.go
  vendor/modules.txt
Labels: ready-for-review, skippy

#2683 Migrate last items to 1ES
  .pipelines/clean-subscription.yml
  .pipelines/mirror-images.yml
  .pipelines/templates/template-clean-subscription.yml
  .pipelines/templates/template-mirror-images.yml
Labels: ready-for-review, skippy

#2466 Fix race conditions in Test functions
  test/util/listener/listener.go
Labels: help wanted, ready-for-review

#2453 Remove adminkubeconfig feature flag
  pkg/api/featureflags.go
  pkg/frontend/openshiftclusterkubeconfigcredentials_post.go
  pkg/frontend/openshiftclusterkubeconfigcredentials_post_test.go
Labels: ready-for-review, next-release

#2720 Update container limits on aro monitor
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/scripts/rpVMSS.sh
Labels: ready-for-review, next-release

#2728 Use VirtualNetworkRule structs and not strings for the CosmoDB VNET rules
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/templates.go
  pkg/deploy/generator/templates_rp.go
Labels: bug, priority-high, ready-for-review, next-release

#2722 Run ensureResourceGroup for ARO delete
  pkg/cluster/delete.go
Labels: ready-for-review, next-release, skippy

#2737 Fix code to make golang-lint happy
  pkg/api/validate/dynamic/serviceprincipal_test.go
  pkg/util/clusterauthorizer/authorizer_test.go
Labels: bug, ready-for-review, next-release

#2730 Support OVNKubernetes in OpenShift 4.11
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/cluster/ipaddresses.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/installer/generateconfig.go
Labels: ready-for-review, next-release

#2733 New document for adding new instance types to RP
  docs/adding-new-instance-types.md
Labels: ready-for-review

#2749 Fixes an issue with RHUI certificate errors during deploy
  pkg/deploy/assets/env-development.json
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/scripts/devCIPool.sh
  pkg/deploy/generator/scripts/devProxyVMSS.sh
  pkg/deploy/generator/scripts/gatewayVMSS.sh
  pkg/deploy/generator/scripts/rpVMSS.sh
Labels: ready-for-review, release-blocker

#2723 policy: deny pod with master toleration taints
  pkg/operator/controllers/guardrails/policies/.gitignore
  pkg/operator/controllers/guardrails/policies/gkconstraints/aro-master-toleration-pod-deny.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-labels/gator-test/no-label-machine-allowed.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-master-toleration-taints/aro-deny-master-toleration-taints.tmpl
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-master-toleration-taints/gator-test/not_allowed_pod_in_non_privledged_ns.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-master-toleration-taints/src.rego
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-master-toleration-taints/src_test.rego
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-master-toleration-taints/suite.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-privileged-namespace/gator-test/ns_disallowed_deploy.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-master-toleration-taints.yaml
Labels: size-medium, skippy

#2734 add extra steps for RHEL machines
  docs/prepare-your-dev-environment.md
Labels: ready-for-review
