Repository Azure/ARO-RP, pull requests merged in 2023-12, with the labels that each got.

#3307 Add libzstd.so.1 to fluentbit container build
  Dockerfile.fluentbit
Labels: bug, ready-for-review, next-release

#3297 MDM Image Bump - ARO-4792
  cmd/aro/mirror.go
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/util/version/const.go
Labels: ready-for-review, next-release, chainsaw

#3314 Enable 4.13.23 as an install target instead of 4.13.16
  pkg/util/version/const.go
Labels: next-release, chainsaw

#3318 Update purge script (hack/clean/clean.go)
  hack/clean/clean.go
Labels: ready-for-review, chainsaw

#3325 `az aro update` CredentialsRequest hotfix
  pkg/cluster/arooperator.go
  pkg/cluster/condition.go
  pkg/cluster/condition_test.go
  pkg/cluster/install.go
  pkg/operator/deploy/deploy.go
  pkg/util/mocks/operator/deploy/deploy.go
  test/e2e/setup.go
  test/e2e/update.go
Labels: ready-for-review, chainsaw

#3252 Use aro-must-gather for CI instead of base client
  .pipelines/e2e.yml
Labels: ready-for-review, chainsaw

#3290 Dynamic validation on CIDR
  pkg/api/error.go
  pkg/api/v20191231preview/openshiftcluster_validatestatic.go
  pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20200430/openshiftcluster_validatestatic.go
  pkg/api/v20200430/openshiftcluster_validatestatic_test.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20220401/openshiftcluster_validatestatic.go
  pkg/api/v20220401/openshiftcluster_validatestatic_test.go
  pkg/api/v20220904/openshiftcluster_validatestatic.go
  pkg/api/v20220904/openshiftcluster_validatestatic_test.go
  pkg/api/v20230401/openshiftcluster_validatestatic.go
  pkg/api/v20230401/openshiftcluster_validatestatic_test.go
  pkg/api/v20230701preview/openshiftcluster_validatestatic.go
  pkg/api/v20230701preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20230904/openshiftcluster_validatestatic.go
  pkg/api/v20230904/openshiftcluster_validatestatic_test.go
Labels: ready-for-review, firefly
