Repository Azure/ARO-RP, pull requests merged in 2023-05, with the labels that each got.

#2867 Fix client generation
  Dockerfile.autorest
  Makefile
  hack/build-client.sh
Labels: firefly

#2878 Auto-generate release note
  .github/generate_release_note.sh
  .github/workflows/release-note.yml
Labels: ready-for-review

#2869 Adding version in log
  pkg/backend/openshiftcluster.go
  pkg/util/log/log.go
Labels: firefly

#2890 Attempt to refresh credentials if we get access exceptions
  pkg/cluster/cluster.go
  pkg/cluster/install.go
  pkg/util/refreshable/refreshable.go
  pkg/util/steps/refreshing.go
Labels: priority-high, next-up, release-blocker, next-release, skippy

#2893 Ad-hoc Hive Image with Red Hat Package Updates at Old Commit
  cmd/aro/mirror.go
Labels: ready-for-review

#2476 Clean up dnsmasq machineconfig when machineconfigpool is deleted
  pkg/operator/controllers/dnsmasq/cluster_controller.go
  pkg/operator/controllers/dnsmasq/cluster_controller_test.go
  pkg/operator/controllers/dnsmasq/machineconfig_controller.go
  pkg/operator/controllers/dnsmasq/machineconfig_controller_test.go
  pkg/operator/controllers/dnsmasq/machineconfigpool_controller.go
  pkg/operator/controllers/dnsmasq/machineconfigpool_controller_test.go
  test/e2e/operator.go
Labels: ready-for-review, loki

#2885 Remove unnecessary error return
  pkg/api/validate/dynamic/dynamic.go
  pkg/api/validate/dynamic/serviceprincipal_test.go
  pkg/api/validate/openshiftcluster_validatedynamic.go
  pkg/operator/controllers/checkers/serviceprincipalchecker/checker.go
  pkg/operator/controllers/checkers/serviceprincipalchecker/checker_test.go
Labels: ready-for-review

#2876 Wrap errors into CloudError
  pkg/api/validate/dynamic/dynamic.go
  pkg/api/validate/dynamic/dynamic_test.go
  pkg/api/validate/openshiftcluster_validatedynamic.go
Labels: ready-for-review

#2825 Acr token rotation
  pkg/cluster/acrtoken.go
  pkg/cluster/adminupdate_test.go
  pkg/cluster/install.go
  pkg/env/core.go
  pkg/env/env.go
  pkg/util/acrtoken/acrtoken.go
  pkg/util/acrtoken/acrtoken_test.go
  pkg/util/azureclient/mgmt/containerregistry/tokens_addons.go
  pkg/util/mocks/azureclient/mgmt/containerregistry/containerregistry.go
  pkg/util/mocks/env/env.go
Labels: next-up, ready-for-review, next-release

#2908 Update timeout on check permissions to >5 min for ARM RA cache
  pkg/api/validate/dynamic/dynamic.go
Labels: bug, next-release

#2888 Worker profiles enrichment refactored tests
  pkg/util/clusterdata/worker_profile_test.go
Labels: ready-for-review, loki

#2863 Test cases for GA SupportedVMSizes
  pkg/frontend/admin_supportedvmsizes_list_test.go
Labels: ready-for-review, skippy

#2891 use importas linter to check import aliases.
  .golangci.yml
  hack/validate-imports/allowed-import-names.yaml
  hack/validate-imports/validate-imports.go
Labels: ready-for-review

#2877 Update the mega linter because of GitHub Action deprecations
  .github/workflows/yamllint.yml
  .gitignore
  .mega-linter.yml
Labels: ready-for-review, skippy

#2873 Guardrails image Dockerfile
  Dockerfile.guardrails
  Makefile
Labels: ready-for-review, skippy

#2854 Rewrite some of the cert/key encoding and decoding
  pkg/bootstraplogging/bootstraplogging.go
  pkg/env/certificateRefresher_test.go
  pkg/operator/deploy/deploy.go
  pkg/portal/kubeconfig/proxy_test.go
  pkg/portal/prometheus/proxy_test.go
  pkg/util/clientauthorizer/subject_name_and_issuer_test.go
  pkg/util/pem/decode.go
  pkg/util/pem/encode.go
  pkg/util/pem/pem_test.go
  pkg/util/tls/marshal.go
Labels: next-up, ready-for-review, go, skippy

#2887 Fix failure in az aro update when missing azure-credentials object
  pkg/cluster/clusterserviceprincipal.go
  pkg/cluster/clusterserviceprincipal_test.go
Labels: next-up, ready-for-review

#2918 minor name corrections for Gatekeeper image - Guardrails
  Dockerfile.gatekeeper
  Makefile
Labels: ready-for-review, skippy

#2904 Add an env variable as a rollout flag for CheckAccess
  pkg/api/validate/dynamic/dynamic.go
  pkg/api/validate/dynamic/dynamic_test.go
  pkg/api/validate/openshiftcluster_validatedynamic.go
  pkg/backend/openshiftcluster_test.go
  pkg/cluster/install_version_test.go
  pkg/deploy/assets/rp-production-parameters.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/config.go
  pkg/deploy/devconfig.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/scripts/rpVMSS.sh
  pkg/deploy/generator/templates_rp.go
  pkg/util/liveconfig/checkaccess.go
  pkg/util/liveconfig/dev.go
  pkg/util/liveconfig/manager.go
  test/util/testliveconfig/liveconfig.go
Labels: ready-for-review, next-release

#2914 Service endpoint removal
  pkg/cluster/adminupdate_test.go
  pkg/cluster/deploybaseresources_additional.go
  pkg/cluster/ensureendpoints.go
  pkg/cluster/ensureendpoints_test.go
  pkg/cluster/install.go
  pkg/operator/controllers/subnets/subnet_controller_test.go
  pkg/operator/controllers/subnets/subnet_serviceendpoint.go
  pkg/util/mocks/subnet/subnet.go
  pkg/util/subnet/subnet.go
Labels: ready-for-review, next-release

#2835 Add changes for BYO NSG
  pkg/api/admin/openshiftcluster.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/featureflags.go
  pkg/api/openshiftcluster.go
  pkg/api/validate/dynamic/dynamic.go
  pkg/api/validate/dynamic/dynamic_test.go
  pkg/cluster/cluster.go
  pkg/cluster/defaults.go
  pkg/cluster/deploybaseresources.go
  pkg/cluster/install.go
  pkg/cluster/validate.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
Labels: ready-for-review, next-release
