Repository Azure/ARO-RP, pull requests merged in 2023-07, with the labels that each got.

#3002 fixes the machine blade not updating bug in Admin Portal
  pkg/portal/assets/v1/build/styles.css
  pkg/portal/assets/v2/build/asset-manifest.json
  pkg/portal/assets/v2/build/index.html
  pkg/portal/assets/v2/build/static/js/main.a2b8e019.js
  pkg/portal/assets/v2/build/static/js/main.a2b8e019.js.LICENSE.txt
  pkg/portal/assets/v2/build/static/js/main.ee7f2cd8.js
  pkg/portal/assets/v2/build/static/js/main.ee7f2cd8.js.LICENSE.txt
  portal/v1/package-lock.json
  portal/v2/src/ClusterDetailListComponents/Machines.tsx
Labels: ready-for-review, firefly

#2967 Installer images use sha256
  cmd/aro/update_ocp_versions.go
  pkg/cluster/install_version_test.go
  pkg/cluster/version.go
  pkg/frontend/frontend.go
  pkg/frontend/openshiftcluster_preflightvalidation_test.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/frontend/validate.go
  pkg/util/cluster/cluster.go
  pkg/util/liveconfig/hive.go
  pkg/util/version/const.go
  pkg/util/version/version.go
  pkg/util/version/version_test.go
Labels: ready-for-review, next-release

#2957 Add field ClusterDeploymentNamespace in ServiceLogs
  pkg/backend/openshiftcluster.go
  pkg/util/log/log.go
Labels: ready-for-review, skippy

#2959 Add API Server Reachability Check
  pkg/monitor/cluster/cluster.go
  pkg/monitor/cluster/healthz.go
Labels: ready-for-review, next-release

#3012 Minor Updates to deploy-development-rp documentation
  docs/deploy-development-rp.md
Labels: ready-for-review

#3003 Fix MDSD memory issue on RP VMs
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/scripts/gatewayVMSS.sh
  pkg/deploy/generator/scripts/rpVMSS.sh
Labels: priority-high, size-small, ready-for-review, next-release, temea

#3028 Update gatekeeper version tag
  Dockerfile.gatekeeper
  Makefile
Labels: size-small, ready-for-review, skippy

#3032 Update guardian suppression rules
  .gdn/.gdnsuppress
  pkg/util/pullsecret/extract_test.go
Labels: ready-for-review

#3033 bump to latest stable
  pkg/util/dynamichelper/discovery/cache/assets_version
  pkg/util/version/const.go
Labels: ready-for-review, next-release

#2996 Add static preflight validation
  pkg/api/preflight.go
  pkg/frontend/openshiftcluster_preflightvalidation.go
  pkg/frontend/openshiftcluster_preflightvalidation_test.go
  pkg/frontend/validate.go
Labels: ready-for-review

#2970 Guardrails policies (M1)
  Makefile
  pkg/operator/controllers/guardrails/guardrails_controller.go
  pkg/operator/controllers/guardrails/guardrails_controller_test.go
  pkg/operator/controllers/guardrails/policies/README.md
  pkg/operator/controllers/guardrails/policies/gkconstraints/aro-machine-config-deny.yaml
  pkg/operator/controllers/guardrails/policies/gkconstraints/aro-master-toleration-pod-deny.yaml
  pkg/operator/controllers/guardrails/policies/gkconstraints/aro-privileged-namespace-deny.yaml
  pkg/operator/controllers/guardrails/policies/gkconstraints/aro-rw-host-mount-deny.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-host-mount/aro-deny-host-mount.tmpl
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-host-mount/gator-test/hostmount_allowed_pod.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-host-mount/gator-test/hostmount_allowed_pv.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-host-mount/gator-test/hostmount_disallowed_pod.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-host-mount/gator-test/hostmount_disallowed_pv.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-host-mount/src.rego
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-host-mount/src_test.rego
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-host-mount/suite.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-labels/src.rego
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-machine-config/aro-deny-machine-config.tmpl
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-machine-config/gator-test/allow_create_custom_machine_config.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-machine-config/gator-test/allow_delete_custom_machine_config.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-machine-config/gator-test/not_allow_create_cluster_machine_config.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-machine-config/gator-test/not_allow_delete_cluster_machine_config.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-machine-config/gator-test/not_allow_update_cluster_machine_config.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-machine-config/src.rego
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-machine-config/src_test.rego
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-machine-config/suite.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-master-toleration-taints/aro-deny-master-toleration-taints.tmpl
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-master-toleration-taints/gator-test/allowed_create_pod_in_privileged_ns.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-master-toleration-taints/gator-test/allowed_delete_pod_in_non_privileged_ns.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-master-toleration-taints/gator-test/not_allowed_create_pod_in_non_privileged_ns.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-master-toleration-taints/gator-test/not_allowed_update_pod_in_non_privileged_ns.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-master-toleration-taints/src.rego
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-master-toleration-taints/src_test.rego
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-master-toleration-taints/suite.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-privileged-namespace/aro-deny-privileged-namespace.tmpl
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-privileged-namespace/gator-test/ns_allowed_deploy.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-privileged-namespace/gator-test/ns_allowed_pod.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-privileged-namespace/gator-test/ns_disallowed_deploy.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-privileged-namespace/gator-test/ns_disallowed_pod.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-privileged-namespace/src.rego
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-privileged-namespace/src_test.rego
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-privileged-namespace/suite.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/library/common.rego
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-host-mount.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-labels.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-machine-config.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-master-toleration-taints.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-privileged-namespace.yaml
  pkg/operator/controllers/guardrails/policies/scripts/generate.sh
  pkg/operator/controllers/guardrails/policies/scripts/test.sh
  pkg/operator/controllers/guardrails/staticresources/gk_audit_controller_deployment.yaml
  pkg/operator/controllers/guardrails/staticresources/gk_controller_manager_deployment.yaml
  pkg/operator/controllers/guardrails/staticresources/gk_namespace.yaml
Labels: ready-for-review, skippy

#3039 Add podman container install docs
  docs/prepare-your-dev-environment.md
Labels: documentation, next-up, ready-for-review, skippy

#3018 update_ocp_versions: Code cleanup
  cmd/aro/update_ocp_versions.go
Labels: good first issue, priority-low, size-small, ready-for-review, loki

#2965 Propagate errors of ARO DNSMasqMachineConfig controller
  pkg/operator/controllers/dnsmasq/machineconfig_controller.go
  pkg/operator/controllers/dnsmasq/machineconfig_controller_test.go
Labels: size-small, ready-for-review, skippy

#2450 Refactor conditions to return error
  pkg/util/steps/condition.go
  pkg/util/steps/condition_test.go
Labels: ready-for-review, skippy

#2951 Propagate errors of ARO DNSMasqCluster controller to ARO Operator
  pkg/operator/controllers/dnsmasq/cluster_controller.go
  pkg/operator/controllers/dnsmasq/cluster_controller_test.go
Labels: size-small, ready-for-review, skippy

#2931 aro-3168: retry on conflict and not found for disabling samples
  pkg/cluster/generate.go
  pkg/cluster/samples.go
  pkg/cluster/samples_test.go
  pkg/util/mocks/samples/samples.go
  pkg/util/mocks/samplesclient/versioned.go
Labels: ready-for-review, chainsaw

#2988 Add gateway log rotatation
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/generator/scripts/gatewayVMSS.sh
Labels: ready-for-review, chainsaw

#2880 Recover etcd master endpoint
  pkg/frontend/admin_openshiftcluster_etcdrecovery.go
  pkg/frontend/admin_openshiftcluster_etcdrecovery_test.go
  pkg/frontend/admin_openshiftcluster_kubernetesobjects.go
  pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go
  pkg/frontend/adminactions/kubeactions.go
  pkg/frontend/fixetcd.go
  pkg/frontend/fixetcd_test.go
  pkg/frontend/frontend.go
  pkg/frontend/scripts.go
  pkg/frontend/scripts/backupandfixetcd.sh
  pkg/util/mocks/adminactions/adminactions.go
Labels: ready-for-review, chainsaw

#2974 Add tests for clusteroperatoraro controller
  pkg/operator/controllers/clusteroperatoraro/clusteroperatoraro_controller_test.go
Labels: ready-for-review, loki

#3015 Move the dynamic validator out of api/
  pkg/api/openshiftcluster.go
  pkg/api/validate/dynamic/generate.go
  pkg/cluster/validate.go
  pkg/operator/controllers/checkers/serviceprincipalchecker/checker.go
  pkg/operator/controllers/checkers/serviceprincipalchecker/checker_test.go
  pkg/util/mocks/dynamic/dynamic.go
  pkg/validate/dynamic/cache_vnet.go
  pkg/validate/dynamic/diskencryptionset.go
  pkg/validate/dynamic/diskencryptionset_test.go
  pkg/validate/dynamic/dynamic.go
  pkg/validate/dynamic/dynamic_test.go
  pkg/validate/dynamic/encryptionathost.go
  pkg/validate/dynamic/encryptionathost_test.go
  pkg/validate/dynamic/generate.go
  pkg/validate/dynamic/serviceprincipal.go
  pkg/validate/dynamic/serviceprincipal_test.go
  pkg/validate/openshiftcluster_validatedynamic.go
Labels: size-small, ready-for-review, go, skippy

#3052 Add API for Microsoft.Compute/galleries
  pkg/util/azureclient/apiversions.go
  pkg/util/azureclient/apiversions_test.go
Labels: ready-for-review, next-release

#3037 Fix e2e must gather
  .pipelines/e2e.yml
  hack/get-admin-kubeconfig.sh
Labels: ready-for-review, chainsaw

#3058 Reconcile Master & Current Release: Revert Preconfigured NSG Changes
  pkg/util/mocks/dynamic/dynamic.go
  pkg/validate/dynamic/dynamic.go
  pkg/validate/dynamic/dynamic_test.go
  pkg/validate/openshiftcluster_validatedynamic.go
Labels: next-up, ready-for-review

#3064 Fix gateway container log file mount
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/generator/scripts/gatewayVMSS.sh
Labels: ready-for-review, chainsaw

#3066 Don't use the uid in containerinstall code
  pkg/containerinstall/install.go
  pkg/containerinstall/install_test.go
  pkg/containerinstall/podman.go
Labels: size-small, next-up, ready-for-review, skippy

#2946 update predeploy to restart old VMSS when service secrets rotated
  pkg/deploy/predeploy.go
  pkg/deploy/predeploy_test.go
  pkg/deploy/upgrade_gateway.go
  pkg/deploy/upgrade_rp.go
  pkg/util/azureclient/mgmt/msi/generate.go
  pkg/util/mocks/azureclient/mgmt/msi/msi.go
Labels: ready-for-review, next-release, chainsaw

#3062 Add nsg to api
  .sha256sum
  pkg/api/openshiftclusterdocument_example.go
  pkg/api/v20230904/openshiftcluster.go
  pkg/api/v20230904/openshiftcluster_convert.go
  pkg/client/services/redhatopenshift/mgmt/2023-09-04/redhatopenshift/enums.go
  pkg/client/services/redhatopenshift/mgmt/2023-09-04/redhatopenshift/models.go
  pkg/swagger/generator.go
  python/client/azure/mgmt/redhatopenshift/v2023_09_04/models/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2023_09_04/models/_azure_red_hat_open_shift_client_enums.py
  python/client/azure/mgmt/redhatopenshift/v2023_09_04/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2023_09_04/models/_models_py3.py
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2023-09-04/examples/OpenShiftClusters_CreateOrUpdate.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2023-09-04/examples/OpenShiftClusters_Get.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2023-09-04/examples/OpenShiftClusters_List.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2023-09-04/examples/OpenShiftClusters_ListByResourceGroup.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2023-09-04/examples/OpenShiftClusters_Update.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2023-09-04/redhatopenshift.json
Labels: ready-for-review

#3020 Preview api lb profile
  .sha256sum
  pkg/api/admin/openshiftcluster.go
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/openshiftcluster.go
  pkg/api/v20230701preview/openshiftcluster.go
  pkg/api/v20230701preview/openshiftcluster_convert.go
  pkg/api/v20230701preview/openshiftcluster_example.go
  pkg/api/v20230701preview/openshiftcluster_validatestatic.go
  pkg/api/v20230701preview/openshiftcluster_validatestatic_test.go
  pkg/client/services/redhatopenshift/mgmt/2023-07-01-preview/redhatopenshift/models.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/swagger/typewalker.go
  python/client/azure/mgmt/redhatopenshift/v2023_07_01_preview/models/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2023_07_01_preview/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2023_07_01_preview/models/_models_py3.py
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2023-07-01-preview/examples/OpenShiftClusters_CreateOrUpdate.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2023-07-01-preview/examples/OpenShiftClusters_Get.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2023-07-01-preview/examples/OpenShiftClusters_List.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2023-07-01-preview/examples/OpenShiftClusters_ListByResourceGroup.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2023-07-01-preview/examples/OpenShiftClusters_Update.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2023-07-01-preview/redhatopenshift.json
Labels: next-up, ready-for-review, next-release, loki

#3071 remove gateway restart during rp predeploy
  pkg/deploy/predeploy.go
  pkg/deploy/predeploy_test.go
Labels: ready-for-review, chainsaw

#3054 Add more information to on conflict for gateway PE linkId
  pkg/cluster/ipaddresses.go
Labels: ready-for-review
