Repository Azure/ARO-RP, pull requests merged in 2023-11, with the labels that each got.

#3245 Add defaults and update k8s dev version
  pkg/deploy/assets/aks-development.json
  python/az/aro/azext_aro/_params.py
Labels: ready-for-review

#3235 Clean up some of the monitor emitting metrics
  pkg/monitor/cluster/arooperatorconditions.go
  pkg/monitor/cluster/arooperatorconditions_test.go
  pkg/monitor/cluster/clusteroperatorconditions.go
  pkg/monitor/cluster/prometheusalerts.go
Labels: size-small, ready-for-review, skippy

#3244 Patch Hive ClusterDeployment rather than Update it
  pkg/hive/manager.go
Labels: ready-for-review

#3226 Fix e2e test for azurefile-csi storage class that uses ARO-managed storage account on OCP 4.11
  test/e2e/cluster.go
Labels: ready-for-review, chainsaw

#3260 Bump Hive Version + Minimal Install
  cmd/aro/mirror.go
  hack/hive-config/hive-config.yaml
  hack/hive-generate-config.sh
  pkg/hive/install.go
Labels: ready-for-review

#3262 Delete OpenShiftVersions via change-feed
  cmd/aro/update_ocp_versions.go
Labels: chainsaw

#3264 Update RP Documentatation with Etcd Recovery URL
  docs/deploy-development-rp.md
Labels: ready-for-review, chainsaw

#3221 Propagate errors of GenevaLogging controller
  pkg/operator/controllers/genevalogging/genevalogging.go
  pkg/operator/controllers/genevalogging/genevalogging_controller.go
  pkg/operator/controllers/genevalogging/genevalogging_test.go
Labels: ready-for-review, loki

#3269 graph: Add HTTP tracing option for MS Graph requests
  go.mod
  pkg/util/graph/adapter.go
Labels: enhancement, ready-for-review, loki

#3265 e2e: Spew ODataError details before panicing
  test/e2e/setup.go
Labels: good first issue, size-small, ready-for-review

#3276 Move genevalogging operator controller files into separate .confs with goembed
  pkg/operator/controllers/genevalogging/const.go
  pkg/operator/controllers/genevalogging/genevalogging_test.go
  pkg/operator/controllers/genevalogging/staticfiles/fluent.conf
  pkg/operator/controllers/genevalogging/staticfiles/parsers.conf
Labels: size-small, go, skippy

#3285 FedRAMP TLS 1.3 Compliance
  hack/fakecluster/fakecluster.go
  pkg/dbtoken/server.go
  pkg/frontend/frontend.go
  pkg/portal/portal.go
  pkg/proxy/proxy.go
  pkg/util/azureclient/applens/applens_client_options.go
Labels: ready-for-review, next-release

#3280 Watch MachineSets for worker subnet changes instead of Machines
  pkg/operator/controllers/storageaccounts/storageaccount_controller.go
  pkg/operator/controllers/storageaccounts/storageaccounts.go
  pkg/operator/controllers/storageaccounts/storageaccounts_test.go
  pkg/operator/controllers/subnets/subnet_controller_test.go
  pkg/operator/controllers/subnets/subnet_nsg.go
  pkg/operator/controllers/subnets/subnet_serviceendpoint.go
  pkg/operator/controllers/subnets/subnets_controller.go
  pkg/util/azureerrors/error.go
  pkg/util/subnet/cluster_subnets.go
  pkg/util/subnet/cluster_subnets_test.go
  test/e2e/operator.go
Labels: ready-for-review, loki

#3274 Update ARO operator Azure auth scheme to use a DefaultAzureCredential
  go.mod
  go.sum
  pkg/cluster/arooperator.go
  pkg/cluster/cluster.go
  pkg/cluster/clusterserviceprincipal.go
  pkg/cluster/clusterserviceprincipal_test.go
  pkg/cluster/condition.go
  pkg/cluster/condition_test.go
  pkg/cluster/install.go
  pkg/operator/controllers/checkers/serviceprincipalchecker/checker.go
  pkg/operator/controllers/checkers/serviceprincipalchecker/checker_test.go
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/staticresources/credentialsrequest.yaml
  pkg/operator/deploy/staticresources/master/deployment.yaml.tmpl
  pkg/util/azureclient/environments.go
  pkg/util/azureclient/mgmt/redhatopenshift/2022-09-04/redhatopenshift/openshiftclusters_addons.go
  pkg/util/clusterauthorizer/authorizer.go
  pkg/util/clusterauthorizer/authorizer_test.go
  pkg/util/kubernetes/deployments.go
  pkg/util/kubernetes/deployments_test.go
  pkg/util/mocks/operator/deploy/deploy.go
  pkg/util/scheme/scheme.go
  test/e2e/update.go
  test/util/serversideapply/serversideapply.go
  vendor/github.com/openshift/cloud-credential-operator/LICENSE
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/aws_types.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/azure_types.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/codec.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/credentialsrequest_types.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/doc.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/gcp_types.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/openstack_types.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/ovirt_types.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/register.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/vsphere_types.go
  vendor/github.com/openshift/cloud-credential-operator/pkg/apis/cloudcredential/v1/zz_generated.deepcopy.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/modules.txt
Labels: ready-for-review, next-release, chainsaw

#3230 Use an enum for cluster maintenance states
  pkg/api/admin/openshiftcluster.go
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/admin/openshiftcluster_validatestatic.go
  pkg/api/admin/openshiftcluster_validatestatic_test.go
  pkg/api/openshiftcluster.go
  pkg/backend/openshiftcluster.go
  pkg/backend/openshiftcluster_test.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/monitor/cluster/cluster.go
  pkg/monitor/cluster/maintenance.go
  pkg/monitor/cluster/maintenance_test.go
Labels: ready-for-review, next-release, go

#3293 Remove version 4.11.26 due to installation issues
  pkg/util/version/const.go
Labels: ready-for-review, next-release

#3295 ARO-4779: Update hive dependency to close vulns
  go.mod
  go.sum
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/SECURITY.md
  vendor/github.com/go-logr/logr/funcr/funcr.go
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/openshift/hive/apis/hive/v1/aws/machinepool.go
  vendor/github.com/openshift/hive/apis/hive/v1/aws/metadata.go
  vendor/github.com/openshift/hive/apis/hive/v1/aws/zz_generated.deepcopy.go
  vendor/github.com/openshift/hive/apis/hive/v1/azure/zz_generated.deepcopy.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterdeprovision_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/gcp/machinepools.go
  vendor/github.com/openshift/hive/apis/hive/v1/gcp/metadata.go
  vendor/github.com/openshift/hive/apis/hive/v1/gcp/zz_generated.deepcopy.go
  vendor/github.com/openshift/hive/apis/hive/v1/machinepool_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/vsphere/machinepools.go
  vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: next-release, loki

#3296 ARO-4779: Mirror new hive image to close vulns
  cmd/aro/mirror.go
Labels: next-release, loki

#3286 Admin action to delete a cluster managed resource
  docs/deploy-development-rp.md
  pkg/frontend/admin_openshiftcluster_delete_managedresource.go
  pkg/frontend/admin_openshiftcluster_delete_managedresource_test.go
  pkg/frontend/adminactions/azureactions.go
  pkg/frontend/adminactions/delete_managedresource.go
  pkg/frontend/adminactions/delete_managedresource_test.go
  pkg/frontend/frontend.go
  pkg/util/azureclient/mgmt/features/resources_addons.go
  pkg/util/loadbalancer/loadbalancer.go
  pkg/util/loadbalancer/loadbalancer_test.go
  pkg/util/mocks/adminactions/adminactions.go
  pkg/util/mocks/azureclient/mgmt/features/features.go
  test/e2e/adminapi_delete_managedresource.go
  test/e2e/update.go
Labels: ready-for-review, next-release, loki

#3232 etcd-renew - Add extra validation and remove IsLessThanMinDuration
  pkg/frontend/admin_openshiftcluster_etcdcertificaterenew.go
  pkg/frontend/admin_openshiftcluster_etcdcertificaterenew_test.go
  pkg/monitor/cluster/certificateexpirationstatuses.go
  pkg/util/cert/cert.go
Labels: ready-for-review, next-release, skippy
