Repository Azure/ARO-RP, pull requests merged in 2023-09, with the labels that each got.

#3132 Exclude some more log namespaces
  pkg/operator/controllers/genevalogging/const.go
Labels: ready-for-review, skippy

#3125 Reduce diffs between our `az aro` extension and the upstream Azure CLI command
  python/az/aro/azext_aro/__init__.py
  python/az/aro/azext_aro/_aad.py
  python/az/aro/azext_aro/_client_factory.py
  python/az/aro/azext_aro/_dynamic_validators.py
  python/az/aro/azext_aro/_params.py
  python/az/aro/azext_aro/_validators.py
  python/az/aro/azext_aro/custom.py
Labels: size-small, ready-for-review, loki

#3141 Use updated k8s.io/utils functions
  go.mod
  go.sum
  pkg/operator/controllers/clusteroperatoraro/clusteroperatoraro_controller_test.go
  pkg/util/conditions/condition.go
  pkg/util/conditions/condition_test.go
  vendor/k8s.io/apimachinery/pkg/util/clock/clock.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/ptr/OWNERS
  vendor/k8s.io/utils/ptr/README.md
  vendor/k8s.io/utils/ptr/ptr.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: ready-for-review

#3144 Fix kube versions in go.mod
  go.mod
  vendor/modules.txt
Labels: ready-for-review

#3145 Fix string to int conversion
  test/database/openshiftclusters.go
Labels: ready-for-review

#3111 Add refresh button for different resources on Admin Portal
  pkg/portal/assets/v2/build/asset-manifest.json
  pkg/portal/assets/v2/build/index.html
  pkg/portal/assets/v2/build/static/js/main.ee7f2cd8.js
  pkg/portal/assets/v2/build/static/js/main.ee7f2cd8.js.LICENSE.txt
  pkg/portal/assets/v2/build/static/js/main.f27c737c.js
  pkg/portal/assets/v2/build/static/js/main.f27c737c.js.LICENSE.txt
  portal/v1/package-lock.json
  portal/v2/src/ClusterDetailListComponents/ClusterOperatorsWrapper.tsx
  portal/v2/src/ClusterDetailListComponents/MachineSetsWrapper.tsx
  portal/v2/src/ClusterDetailListComponents/MachinesWrapper.tsx
  portal/v2/src/ClusterDetailListComponents/NodesWrapper.tsx
  portal/v2/src/ClusterDetailListComponents/OverviewWrapper.tsx
  portal/v2/src/ClusterDetailListComponents/Statistics/StatisticsWrapper.tsx
  test/e2e/admin_portal.go
Labels: ready-for-review, firefly

#3053 Add worker profile status
  .sha256sum
  pkg/api/admin/openshiftcluster.go
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/openshiftcluster.go
  pkg/api/openshiftclusterdocument_example.go
  pkg/api/util/subnet/subnet.go
  pkg/api/util/subnet/subnet_test.go
  pkg/api/v20191231preview/openshiftcluster_convert.go
  pkg/api/v20191231preview/openshiftcluster_example.go
  pkg/api/v20200430/openshiftcluster_convert.go
  pkg/api/v20200430/openshiftcluster_example.go
  pkg/api/v20210901preview/openshiftcluster_convert.go
  pkg/api/v20210901preview/openshiftcluster_example.go
  pkg/api/v20220401/openshiftcluster_convert.go
  pkg/api/v20220401/openshiftcluster_example.go
  pkg/api/v20220904/openshiftcluster_convert.go
  pkg/api/v20220904/openshiftcluster_example.go
  pkg/api/v20230401/openshiftcluster_convert.go
  pkg/api/v20230401/openshiftcluster_example.go
  pkg/api/v20230701preview/openshiftcluster_convert.go
  pkg/api/v20230701preview/openshiftcluster_example.go
  pkg/api/v20230904/openshiftcluster.go
  pkg/api/v20230904/openshiftcluster_convert.go
  pkg/api/v20230904/openshiftcluster_example.go
  pkg/api/v20230904/openshiftcluster_validatestatic.go
  pkg/api/v20230904/openshiftcluster_validatestatic_test.go
  pkg/client/services/redhatopenshift/mgmt/2023-09-04/redhatopenshift/models.go
  pkg/cluster/deploybaseresources.go
  pkg/cluster/deploybaseresources_additional.go
  pkg/cluster/ensureendpoints.go
  pkg/cluster/ipaddresses.go
  pkg/cluster/ipaddresses_test.go
  pkg/cluster/storageaccounts.go
  pkg/cluster/storageclass.go
  pkg/cluster/storageclass_test.go
  pkg/frontend/adminactions/resources_list.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/quota_validation.go
  pkg/frontend/sku_test.go
  pkg/frontend/sku_validation.go
  pkg/swagger/examples.go
  pkg/swagger/generator.go
  pkg/swagger/typewalker.go
  pkg/util/clusterdata/worker_profile.go
  pkg/util/clusterdata/worker_profile_test.go
  pkg/validate/dynamic/diskencryptionset.go
  pkg/validate/dynamic/diskencryptionset_test.go
  pkg/validate/dynamic/encryptionathost.go
  pkg/validate/dynamic/encryptionathost_test.go
  pkg/validate/openshiftcluster_validatedynamic.go
  python/client/azure/mgmt/redhatopenshift/v2023_09_04/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2023_09_04/models/_models_py3.py
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2023-09-04/examples/OpenShiftClusters_Get.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2023-09-04/examples/OpenShiftClusters_List.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2023-09-04/examples/OpenShiftClusters_ListByResourceGroup.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2023-09-04/redhatopenshift.json
Labels: ready-for-review, next-release, go

#3158 update to go 1.18.10
  Dockerfile.aro-e2e
  Dockerfile.aro-multistage
  Dockerfile.ci
  Dockerfile.proxy
  pkg/containerinstall/install_test.go
Labels: next-up, ready-for-review, go

#3160 Remove rhcos publishing doc, can be found in ARO-Installer
  docs/publish-rhcos-image.md
Labels: documentation, size-small, loki

#3051 Added the Actions Icons on Cluster Detail Page
  pkg/portal/assets/v2/build/asset-manifest.json
  pkg/portal/assets/v2/build/index.html
  pkg/portal/assets/v2/build/static/js/main.f1999c11.js
  pkg/portal/assets/v2/build/static/js/main.f1999c11.js.LICENSE.txt
  pkg/portal/assets/v2/build/static/js/main.f27c737c.js
  pkg/portal/assets/v2/build/static/js/main.f27c737c.js.LICENSE.txt
  portal/v2/src/App.tsx
  portal/v2/src/ClusterDetail.tsx
  portal/v2/src/ClusterList.tsx
  portal/v2/src/Kubeconfig.tsx
  portal/v2/src/SSHModal.tsx
  portal/v2/src/ToolIcons.tsx
  test/e2e/admin_portal.go
Labels: ready-for-review, firefly

#3149 Bumping up MUO to v0.1.952
  pkg/operator/controllers/muo/muo_controller_test.go
  pkg/util/version/const.go
  test/e2e/operator.go
Labels: bug, next-release

#3162 skip lb profile reconcile when arch is v1
  pkg/cluster/loadbalancerprofile.go
  pkg/cluster/loadbalancerprofile_test.go
Labels: next-up, next-release, loki

#3057 Fix NSG e2e error
  pkg/util/mocks/dynamic/dynamic.go
  pkg/validate/dynamic/dynamic.go
  pkg/validate/dynamic/dynamic_test.go
  pkg/validate/openshiftcluster_validatedynamic.go
  test/e2e/operator.go
Labels: ready-for-review, next-release

#3154 feature: deny crd modification policy
  pkg/operator/controllers/guardrails/policies/gkconstraints/aro-crd-deny.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-crd/aro-deny-crd.tmpl
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-crd/gator-test/allowed-create-crd.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-crd/gator-test/allowed-create-custom-crd.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-crd/gator-test/allowed-delete-crd.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-crd/gator-test/allowed-delete-custom-crd.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-crd/gator-test/allowed-update-crd.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-crd/gator-test/allowed-update-custom-crd.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-crd/gator-test/not-allowed-create-crd.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-crd/gator-test/not-allowed-delete-crd.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-crd/gator-test/not-allowed-update-crd.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-crd/src.rego
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-crd/src_test.rego
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-crd/suite.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/library/common.rego
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-crd.yaml
Labels: ready-for-review, skippy

#3171 Default to 4.12 for new installations
  pkg/util/version/const.go
Labels: next-release

#2976 create monitor for certificate expirations
  pkg/monitor/cluster/certificateexpirationstatuses.go
  pkg/monitor/cluster/certificateexpirationstatuses_test.go
  pkg/monitor/cluster/cluster.go
Labels: ready-for-review, next-release, chainsaw

#3124 New Monitor to emit ETCD certificates expiration
  pkg/monitor/cluster/certificateexpirationstatuses.go
  pkg/monitor/cluster/certificateexpirationstatuses_test.go
  pkg/monitor/cluster/cluster.go
  pkg/util/cert/cert.go
Labels: ready-for-review, next-release, skippy

#3137 GenevaAction for etcd Certificate Renewal
  pkg/frontend/admin_openshiftcluster_etcdcertificaterenew.go
  pkg/frontend/admin_openshiftcluster_etcdcertificaterenew_test.go
  pkg/frontend/frontend.go
Labels: ready-for-review, next-release, skippy

#3167 Update Dockerfile.ci to use buildarg for registry name
  .github/workflows/ci-go.yml
  Dockerfile.ci
Labels: ready-for-review

#3168 Get to the bottom of the e2e admin portal failure
  .pipelines/e2e.yml
  test/e2e/admin_portal.go
  test/e2e/setup.go
Labels: next-up, ready-for-review, release-blocker, skippy

#3179 Return error if we fail to delete hive resources during deletion
  pkg/cluster/delete.go
Labels: ready-for-review

#3182 Fix bad logic comparison against an already existing gateway record
  pkg/cluster/ipaddresses.go
Labels: bug, ready-for-review, next-release

#3184 Fix WorkerProfilesStatus PUCM Bug
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/v20230904/openshiftcluster_convert.go
  test/e2e/adminapi_cluster_update.go
Labels: bug, next-release

#3187 rotate the openshift-config pull-secret on acr token rotation
  pkg/cluster/acrtoken.go
Labels: bug, help wanted, next-up, ready-for-review, next-release, chainsaw

#3189 Revert "Default to 4.12 for new installations"
  pkg/util/version/const.go
Labels: ready-for-review, next-release

#3190 Revendor go-cosmosdb to fix database.EmitMetrics() json decode error
  go.mod
  go.sum
  pkg/database/cosmosdb/zz_generated_collection.go
  vendor/github.com/jewzaam/go-cosmosdb/pkg/gencosmosdb/bindata.go
  vendor/modules.txt
Labels: bug, ready-for-review

#3191 removed openshift-config as protected namespace as suggested
  pkg/operator/controllers/guardrails/policies/README.md
  pkg/operator/controllers/guardrails/policies/gkconstraints/aro-privileged-namespace-deny.yaml
  pkg/operator/controllers/guardrails/policies/gkconstraints/aro-rw-host-mount-deny.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-host-mount/aro-deny-host-mount.tmpl
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-host-mount/gator-test/hostmount_allowed_pod.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-host-mount/gator-test/hostmount_allowed_pv.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-host-mount/gator-test/hostmount_disallowed_pod.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-host-mount/gator-test/hostmount_disallowed_pv.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-host-mount/src.rego
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-host-mount/src_test.rego
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-host-mount/suite.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-master-toleration-taints/src_test.rego
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-privileged-namespace/gator-test/ns_allowed_deploy.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-privileged-namespace/gator-test/ns_allowed_pod.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-privileged-namespace/gator-test/ns_disallowed_deploy.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-privileged-namespace/gator-test/ns_disallowed_pod.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-privileged-namespace/src.rego
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-privileged-namespace/src_test.rego
  pkg/operator/controllers/guardrails/policies/gktemplates-src/aro-deny-privileged-namespace/suite.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates-src/library/common.rego
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-host-mount.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-machine-config.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-master-toleration-taints.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-privileged-namespace.yaml
Labels: size-small, next-release, skippy
