Repository Azure/ARO-RP, pull requests merged in 2023-03, with the labels that each got.

#2740 clean up of portal
  pkg/portal/cluster_test.go
  pkg/portal/http_test.go
  pkg/portal/kubeconfig/kubeconfig.go
  pkg/portal/kubeconfig/kubeconfig_test.go
  pkg/portal/kubeconfig/proxy.go
  pkg/portal/kubeconfig/proxy_test.go
  pkg/portal/portal.go
  pkg/portal/prometheus/prometheus.go
  pkg/portal/prometheus/proxy.go
  pkg/portal/prometheus/proxy_test.go
  pkg/portal/regions_test.go
  pkg/portal/ssh/proxy.go
  pkg/portal/ssh/proxy_test.go
  pkg/portal/ssh/ssh.go
  pkg/portal/ssh/ssh_test.go
Labels: ready-for-review

#2520 Add a Fluentbit image build using Mariner containers
  Dockerfile.fluentbit
  Makefile
  cmd/aro/mirror.go
Labels: next-up, ready-for-review, next-release, skippy

#2766 Fix Purge MSFT CI Subscription
  .pipelines/templates/template-clean-subscription.yml
Labels: priority-high, ready-for-review

#2756 Fix failure to parse token errors as Cloud Errors - ARO-1577
  pkg/api/validate/dynamic/serviceprincipal.go
  pkg/api/validate/dynamic/serviceprincipal_test.go
  pkg/util/clusterauthorizer/authorizer.go
  pkg/util/clusterauthorizer/authorizer_test.go
  pkg/util/instancemetadata/prod.go
  pkg/util/instancemetadata/prod_test.go
Labels: ready-for-review

#2202 Returning the error if error is captured instead of nil
  pkg/util/aad/aad.go
  pkg/util/aad/aad_test.go
  pkg/util/mocks/refreshable/refreshable.go
  pkg/util/refreshable/refreshable.go
Labels: ready-for-review

#2744 Add new clouderror for inUseSubnet
  pkg/api/error.go
  pkg/cluster/delete.go
Labels: ready-for-review

#2709 Add checkaccess Client
  pkg/api/featureflags.go
  pkg/util/azureclient/applens/applens_client_test.go
  pkg/util/azureclient/applens/applens_error_test.go
  pkg/util/azureclient/authz/remotepdp/client.go
  pkg/util/azureclient/authz/remotepdp/client_test.go
  pkg/util/azureclient/authz/remotepdp/const.go
  pkg/util/azureclient/authz/remotepdp/types.go
  pkg/util/azureclient/environments.go
  test/util/http/mock.go
  test/util/http/mock_test.go
Labels: ready-for-review

#2754 CosmoDB firewall rules required for the transient-VM-deploy in all regions
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/templates.go
  pkg/deploy/generator/templates_rp.go
Labels: ready-for-review

#2608 operator feature: check ingress certificate and cluster domain
  pkg/operator/controllers/checkers/ingresscertificatechecker/checker.go
  pkg/operator/controllers/checkers/ingresscertificatechecker/checker_test.go
  pkg/operator/controllers/checkers/ingresscertificatechecker/controller.go
  pkg/operator/controllers/checkers/ingresscertificatechecker/controller_test.go
  pkg/util/dns/dns.go
  pkg/util/net/net.go
  pkg/util/net/net_test.go
Labels: ready-for-review

#2783 refactor: move IsManagedDomain function to dns package
  pkg/operator/controllers/checkers/ingresscertificatechecker/checker.go
  pkg/util/dns/manageddomains.go
  pkg/util/dns/manageddomains_test.go
  pkg/util/net/net.go
Labels: ready-for-review

#2770 Frontend validation invalid parameter
  pkg/api/validate/dynamic/dynamic.go
  pkg/api/validate/openshiftcluster_validatedynamic.go
  pkg/frontend/frontend.go
  pkg/frontend/generate.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/frontend/sku_test.go
  pkg/frontend/sku_validation.go
  pkg/util/mocks/dynamic/dynamic.go
  pkg/util/mocks/frontend/frontend.go
Labels: ready-for-review

#2517 Az aro validate cmd
  python/az/aro/azext_aro/_dynamic_validators.py
  python/az/aro/azext_aro/_help.py
  python/az/aro/azext_aro/commands.py
  python/az/aro/azext_aro/custom.py
  python/az/aro/azext_aro/tests/latest/unit/test_dynamic_validators.py
Labels: ready-for-review

#2795 Increase cosmosdb default throughput to 1000
  pkg/deploy/assets/databases-development.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_rp.go
Labels: ready-for-review, next-release

#2797 remove --enable-soft-delete option
  docs/disk-encryption-set.md
Labels: documentation, size-small

#2791 Replace SPChecker with IngressCertificateChecker
  pkg/operator/controllers/checkers/ingresscertificatechecker/controller.go
Labels: size-small, ready-for-review, skippy

#2802 replaced standard library with chi in dbtoken
  pkg/dbtoken/server.go
  pkg/dbtoken/server_test.go
Labels: next-release

#2801 replaces the standard library mux with chi in the gateway
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/generator/resources_gateway.go
  pkg/gateway/gateway.go
  pkg/gateway/http.go
Labels: next-release

#2798 GenevaAction to list Supported VM Sizes
  docs/deploy-development-rp.md
  pkg/api/validate/vm.go
  pkg/frontend/admin_supportvmsizes_list.go
  pkg/frontend/frontend.go
Labels: ready-for-review, skippy

#2812 Add the registry arg for the fluentbit dockerfile
  Dockerfile.fluentbit
Labels: next-up, ready-for-review, next-release, skippy

#2814 Change mariner to pull from MCR
  Dockerfile.fluentbit
  Makefile
  cmd/aro/mirror.go
Labels: next-up, ready-for-review, next-release, skippy

#2743 Reconcile differences between frontend & backend default version behavior
  pkg/cluster/version.go
Labels: next-release
