Repository Azure/ARO-RP, pull requests merged in 2023-10, with the labels that each got.

#3196 Convert the pucm pending boolean in the AdminAPI
  pkg/api/admin/openshiftcluster_convert.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
Labels: bug, next-release

#3197 Set maintenace task to "" after PUCM pending operation
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
Labels: bug, next-release

#3090 Prevent memory leaks with DialContext usage and new k8s client creation
  pkg/util/restconfig/restconfig.go
Labels: ready-for-review

#3200 workerProfilesStatus static validate
  pkg/api/v20230904/openshiftcluster_validatestatic.go
  pkg/api/v20230904/openshiftcluster_validatestatic_test.go
Labels: bug, next-release

#3115 Update documentation for testing the ARO operator
  docs/operators.md
  docs/prepare-your-dev-environment.md
Labels: documentation, good first issue, size-small, loki

#3202 api: Add Default field to OpenShiftVersionProperties
  pkg/api/openshiftversion.go
Labels: size-small, ready-for-review, loki

#3208 api: Add MissingFields to OpenShiftVersionProperties
  pkg/api/openshiftversion.go
Labels: size-small, ready-for-review, loki

#3211 Network acl fix for storageaccounts on Create or AdminUpdate
  pkg/cluster/deploybaseresources.go
  pkg/cluster/deploybaseresources_additional.go
  pkg/cluster/deploybaseresources_test.go
  pkg/cluster/storageaccounts.go
  pkg/operator/controllers/storageaccounts/storageaccount_controller.go
  pkg/operator/controllers/storageaccounts/storageaccounts.go
  pkg/operator/controllers/storageaccounts/storageaccounts_test.go
  test/e2e/cluster.go
  test/e2e/setup.go
  test/util/project/project.go
Labels: bug, next-release

#3212 Add eventually timeout when we use contexts
  test/e2e/adminapi_cluster_getlogs.go
  test/e2e/adminapi_cluster_update.go
  test/e2e/adminapi_kubernetesobjects.go
  test/e2e/adminapi_redeployvm.go
  test/e2e/cluster.go
  test/e2e/operator.go
  test/e2e/setup.go
Labels: ready-for-review

#3214 Remove ready-for-review when rebase is required
  .github/workflows/maintenance.yml
Labels: ready-for-review

#2471 Revert workaround for mdsd bug
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/scripts/gatewayVMSS.sh
  pkg/deploy/generator/scripts/rpVMSS.sh
Labels: next-release, chainsaw

#3093 fix graph error handling
  python/az/aro/azext_aro/custom.py
Labels: ready-for-review

#3183 Add e2e tests for multiple ips per loadbalancer
  pkg/util/azureclient/mgmt/redhatopenshift/2023-07-01-preview/redhatopenshift/openshiftclusters.go
  pkg/util/azureclient/mgmt/redhatopenshift/2023-07-01-preview/redhatopenshift/openshiftclusters_addons.go
  pkg/util/azureclient/mgmt/redhatopenshift/2023-07-01-preview/redhatopenshift/operations.go
  pkg/util/azureclient/mgmt/redhatopenshift/2023-07-01-preview/redhatopenshift/operations_addons.go
  test/e2e/setup.go
  test/e2e/update.go
Labels: loki

#3216 Enable Double (infrastructure) Encryption on ARO-provisioned storage accounts
  pkg/cluster/deploybaseresources_additional.go
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production-global.json
  pkg/deploy/assets/rp-production.json
  pkg/util/azureclient/apiversions.go
Labels: ready-for-review, loki

#3217 Match AKS development version with production
  pkg/deploy/assets/aks-development.json
Labels: ready-for-review

#3177 Propagate errors of ARO MachineHealthCheckController to ARO Operator
  pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller.go
  pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller_test.go
Labels: ready-for-review, loki

#3220 Additional Waiting for API Server to become ready
  pkg/cluster/install.go
Labels: ready-for-review

#3204 BUG: Fix golang client PUT for GA
  pkg/api/admin/openshiftcluster.go
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/openshiftcluster.go
  pkg/api/register.go
  pkg/api/util/immutable/immutable.go
  pkg/api/v20191231preview/openshiftcluster_convert.go
  pkg/api/v20200430/openshiftcluster_convert.go
  pkg/api/v20210901preview/openshiftcluster_convert.go
  pkg/api/v20220401/openshiftcluster_convert.go
  pkg/api/v20220904/openshiftcluster_convert.go
  pkg/api/v20230401/openshiftcluster_convert.go
  pkg/api/v20230701preview/openshiftcluster.go
  pkg/api/v20230701preview/openshiftcluster_convert.go
  pkg/api/v20230701preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20230904/openshiftcluster.go
  pkg/api/v20230904/openshiftcluster_convert.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/swagger/typewalker.go
  test/e2e/update.go
Labels: bug, ready-for-review, next-release, loki

#3223 Fix panic on addressPrefix vs addressPrefixes on subnet
  pkg/util/subnet/subnet.go
  pkg/util/subnet/subnet_test.go
Labels: bug, ready-for-review, next-release

#3231 Return actionable service principal errors to the user
  pkg/util/steps/refreshing.go
  pkg/validate/openshiftcluster_validatedynamic.go
Labels: bug, ready-for-review, next-release, chainsaw

#3236 fix docs: puslish aro operator to quay
  docs/operators.md
Labels: documentation

#3233 Update MDM, MDSD, Fluentbit images
  cmd/aro/mirror.go
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/util/version/const.go
Labels: ready-for-review, next-release

#3237 Default installation target to 4.12
  pkg/util/version/const.go
Labels: ready-for-review, next-release

#3241 Fix CheckAccess unmarshal bug
  pkg/util/azureclient/authz/remotepdp/client.go
  pkg/util/azureclient/authz/remotepdp/types.go
Labels: ready-for-review, next-release

#3249 Skip failing pki test for now
  pkg/util/pki/pki_test.go
Labels: priority-high, next-up, ready-for-review, next-release, skippy

#3240 Only mirror images from 4.11+
  cmd/aro/mirror.go
Labels: ready-for-review

#3243 Hive Minimal Install Annotation on ClusterDeployment
  pkg/hive/install.go
Labels: ready-for-review, next-release

#3257 bug: Keep cli-domain-from-installer-image until we use minimal hive version
  pkg/hive/install.go
Labels: bug, ready-for-review, next-release
