Repository Azure/ARO-RP, pull requests merged in 2024-11, with the labels that each got.

#3936 Deploy fix - GET devops MSI using properly scoped Azure client
  pkg/deploy/deploy.go
  pkg/deploy/deploy_rp.go
Labels: ready-for-review, release-blocker, chainsaw

#3930 disallow duplicate operator identity resource IDs
  pkg/api/v20240812preview/openshiftcluster_validatestatic.go
  pkg/api/v20240812preview/openshiftcluster_validatestatic_test.go
Labels: chainsaw

#3938 Fix test flake in preview API for MIWI
  pkg/api/v20240812preview/openshiftcluster_validatestatic.go
  pkg/api/v20240812preview/openshiftcluster_validatestatic_test.go
Labels: bug, next-up, flake, LGTM, skippy

#3819 Add run-rp docs
  docs/deploy-development-rp.md
  docs/prepare-your-dev-environment.md
Labels: documentation, size-small, ready-for-review, loki

#3804 Updated Useful Links section
  README.md
Labels: size-small, ready-for-review

#3561 Disable cosmosdb local auth
  pkg/deploy/assets/rp-development.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_rp.go
Labels: next-up, ready-for-review, next-release, firefly

#3943 Add missing env var to containerized RP startup command
  docker-compose.yml
Labels: ready-for-review, chainsaw

#3944 MIWI Cosmos DB key uniqueness fix
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/frontend/validate.go
Labels: ready-for-review, chainsaw

#3935 Support Update requirements for Workload Identity clusters
  pkg/api/v20240812preview/openshiftcluster_convert.go
  pkg/cluster/install.go
  pkg/cluster/workloadidentityresources.go
  pkg/cluster/workloadidentityresources_test.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/operator/deploy/deploy.go
  python/az/aro/azext_aro/custom.py
Labels: loki, chainsaw

#3932 confirm UsesWorkloadIdentity shared utility function is used everywhere in ARO-RP
  pkg/cluster/delete.go
Labels: ready-for-review, chainsaw

#3950 MIWI API converter fixes
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/v20240812preview/openshiftcluster_convert.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
Labels: ready-for-review, chainsaw

#3949 Pass backendErr to emitMetrics
  pkg/backend/openshiftcluster.go
Labels: bug, chainsaw

#3946 ARO-12034 Fix CheckAccessV2 usage for MIWI dynamic validation
  pkg/cluster/install.go
  pkg/cluster/validate.go
  pkg/util/azureclient/azuresdk/armmsi/user_assigned_identities.go
  pkg/util/mocks/azureclient/azuresdk/armmsi/user_assigned_identities.go
  pkg/util/mocks/dynamic/dynamic.go
  pkg/validate/dynamic/diskencryptionset_test.go
  pkg/validate/dynamic/dynamic.go
  pkg/validate/dynamic/dynamic_test.go
  pkg/validate/dynamic/platformworkloadidentityprofile.go
  pkg/validate/dynamic/platformworkloadidentityprofile_test.go
  pkg/validate/openshiftcluster_validatedynamic.go
Labels: ready-for-review, chainsaw

#3963 Do not try to set UpgradeableTo annotation in-cluster if it is empty
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/deploy_test.go
Labels: loki, chainsaw

#3962 Ensure MSI readonly fields are set to '' in ExternalNoReadOnly converters
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/v20240812preview/openshiftcluster_convert.go
Labels: loki, chainsaw

#3964 Fix AKS connectivity
  pkg/util/azureclient/azuresdk/armcontainerservice/managedcluster_addons.go
  pkg/util/liveconfig/hive.go
  pkg/util/liveconfig/hive_test.go
Labels: ready-for-review, chainsaw

#3972 Repopulate MSI tenant ID during update
  pkg/cluster/clustermsi.go
  pkg/cluster/install.go
Labels: chainsaw

#3856 RP E2E Test Execution
  .pipelines/ci.yml
  .pipelines/templates/deploy-hive-operator.yml
  .pipelines/templates/template-az-cli-login.yml
  Dockerfile.aro-e2e
  Dockerfile.ci-rp
  Makefile
  docker-compose.yml
  docs/prepare-your-dev-environment.md
  env.example
  hack/e2e/utils.sh
  hack/hive/hive-dev-install.sh
  test/e2e/hive.go
  test/e2e/setup.go
Labels: ready-for-review, loki

#3968 [ARO-12458] Remove excess JWT dependency and update the one we do have
  go.mod
  go.sum
  pkg/portal/middleware/aad_test.go
  pkg/util/instancemetadata/prod.go
  pkg/validate/dynamic/serviceprincipal.go
  pkg/validate/openshiftcluster_validatedynamic.go
  vendor/github.com/form3tech-oss/jwt-go/.gitignore
  vendor/github.com/form3tech-oss/jwt-go/.travis.yml
  vendor/github.com/form3tech-oss/jwt-go/LICENSE
  vendor/github.com/form3tech-oss/jwt-go/MIGRATION_GUIDE.md
  vendor/github.com/form3tech-oss/jwt-go/README.md
  vendor/github.com/form3tech-oss/jwt-go/VERSION_HISTORY.md
  vendor/github.com/form3tech-oss/jwt-go/claims.go
  vendor/github.com/form3tech-oss/jwt-go/doc.go
  vendor/github.com/form3tech-oss/jwt-go/ecdsa.go
  vendor/github.com/form3tech-oss/jwt-go/ecdsa_utils.go
  vendor/github.com/form3tech-oss/jwt-go/errors.go
  vendor/github.com/form3tech-oss/jwt-go/hmac.go
  vendor/github.com/form3tech-oss/jwt-go/map_claims.go
  vendor/github.com/form3tech-oss/jwt-go/none.go
  vendor/github.com/form3tech-oss/jwt-go/parser.go
  vendor/github.com/form3tech-oss/jwt-go/rsa.go
  vendor/github.com/form3tech-oss/jwt-go/rsa_pss.go
  vendor/github.com/form3tech-oss/jwt-go/rsa_utils.go
  vendor/github.com/form3tech-oss/jwt-go/signing_method.go
  vendor/github.com/form3tech-oss/jwt-go/token.go
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: size-small, ready-for-review, dependencies, go, skippy
