Repository Azure/ARO-RP, pull requests merged in 2024-05, with the labels that each got.

#3524 use checkAccessv2 for all permission validations and deprecate listPermissions for validations
  pkg/deploy/assets/rbac-development.json
  pkg/util/azureclient/mgmt/authorization/generate.go
  pkg/util/azureclient/mgmt/authorization/permissions.go
  pkg/util/azureclient/mgmt/authorization/permissions_addons.go
  pkg/util/mocks/azureclient/mgmt/authorization/authorization.go
  pkg/util/permissions/permissions.go
  pkg/util/permissions/permissions_test.go
  pkg/validate/dynamic/diskencryptionset_test.go
  pkg/validate/dynamic/dynamic.go
  pkg/validate/dynamic/dynamic_test.go
  pkg/validate/openshiftcluster_validatedynamic.go
Labels: ready-for-review, chainsaw

#3538 Bug fix - clear ReadOnly fields on PUT or PATCH for 2023-11-22 and 2024-08-12-preview APIs
  pkg/api/v20231122/openshiftcluster_convert.go
  pkg/api/v20240812preview/openshiftcluster_convert.go
  pkg/frontend/openshiftcluster_putorpatch.go
Labels: bug, next-release, loki

#3557 Do not perform explicit CSP roleassignment deletion in prod e2e
  pkg/util/cluster/cluster.go
Labels: next-release

#3553 Update MARINER_VERSION to 20240425
  Makefile
Labels: chainsaw

#3554 Modified the content to set up the dev env : ARO-7278
  Makefile
  docs/deploy-development-rp.md
  docs/prepare-your-dev-environment.md
  env.example
Labels: documentation, size-small, loki

#3559 Added option to only give ipv4 as output.
  docs/deploy-full-rp-service-in-dev.md
Labels: ready-for-review

#3548 update go version to 1.20.12
  .github/workflows/ci-go.yml
  .pipelines/ci.yml
  .pipelines/onebranch/pipeline.buildrp.official.yml
  .pipelines/onebranch/pipeline.buildrp.pullrequest.yml
  pkg/containerinstall/install_test.go
Labels: ready-for-review, go, skippy

#3532 upgrade to go1.20.12
  Dockerfile.aro-e2e
  Dockerfile.aro-multistage
  Dockerfile.gatekeeper
  Dockerfile.proxy
Labels: size-small, ready-for-review, go, skippy

#3449 Fix adminUpdate steps
  pkg/cluster/adminupdate_test.go
  pkg/cluster/install.go
  pkg/util/generics/helpers.go
Labels: enhancement, priority-low, size-small, ready-for-review

#3558 `make ci` support for golang (RP) components
  Dockerfile.ci-rp
  Dockerfile.ci-rp.dockerignore
  Makefile
  docs/prepare-your-dev-environment.md
Labels: size-small, ready-for-review, go, loki

#3570 VPN client cert fix
  hack/devtools/deploy-shared-env.sh
Labels: ready-for-review, chainsaw

#3568 Add track2 API Client to Cluster struct (loadbalancer and interfaces)
  pkg/cluster/cluster.go
  pkg/env/dev.go
  pkg/env/env.go
  pkg/env/prod.go
  pkg/util/azureclient/azuresdk/armnetwork/generate.go
  pkg/util/azureclient/azuresdk/armnetwork/interfaces.go
  pkg/util/azureclient/azuresdk/armnetwork/interfaces_addons.go
  pkg/util/azureclient/azuresdk/armnetwork/loadbalancers.go
  pkg/util/azureclient/azuresdk/armnetwork/loadbalancers_addons.go
  pkg/util/mocks/azureclient/azuresdk/armnetwork/armnetwork.go
Labels: ready-for-review

#3563 ARO-6425 v20240812preview validation
  pkg/api/v20240812preview/openshiftcluster_convert.go
  pkg/api/v20240812preview/openshiftcluster_validatestatic.go
  pkg/api/v20240812preview/openshiftcluster_validatestatic_test.go
  pkg/util/arm/resources.go
  pkg/util/arm/resources_test.go
  pkg/util/stringutils/stringutils.go
Labels: ready-for-review, chainsaw

#3582 Add Cosmos DB container and pkg/database client for PlatformWorkloadIdentityRoleSets
  pkg/database/cosmosdb/generate.go
  pkg/database/cosmosdb/zz_generated_platformworkloadidentityrolesetdocument.go
  pkg/database/cosmosdb/zz_generated_platformworkloadidentityrolesetdocument_fake.go
  pkg/database/database.go
  pkg/database/platformworkloadidentityrolesets.go
  pkg/deploy/assets/databases-development.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_rp.go
Labels: chainsaw

#3576 Integrate JS asset build into Golang Dockerfile to ensure consistent builds and deployment process"
  Dockerfile.ci-portal
  Dockerfile.ci-rp
  Dockerfile.ci-rp.dockerignore
  Makefile
Labels: size-small, ready-for-review, loki

#3562 Migrate dev-proxy-vmss to Azure Linux and enable rolling OS update
  Dockerfile.proxy
  pkg/deploy/assets/env-development.json
  pkg/deploy/generator/resources_dev.go
  pkg/deploy/generator/scripts/devProxyVMSS.sh
  pkg/deploy/generator/templates_dev.go
  pkg/proxy/proxy.go
Labels: ready-for-review

#3591 [BUGFIX] This is to fix the cluster installation failure when preconfigured NSGs used
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/v20230904/openshiftcluster_convert.go
  pkg/api/v20231122/openshiftcluster_convert.go
  pkg/api/v20240812preview/openshiftcluster_convert.go
Labels: ready-for-review, firefly
