Repository Azure/ARO-RP, pull requests merged in 2024-09, with the labels that each got.

#3806 Fix make ci-clean and runlocal-rp
  Makefile
Labels: size-small, ready-for-review, loki

#3809 Fix slow tests in /pkg/backend
  pkg/backend/backend.go
  pkg/backend/openshiftcluster.go
  pkg/backend/openshiftcluster_test.go
Labels: size-small, ready-for-review, loki

#3810 Fix slow tests in /pkg/frontend
  pkg/frontend/admin_openshiftcluster_etcdcertificaterenew_test.go
  pkg/frontend/changefeed_test.go
Labels: size-small, ready-for-review, loki

#3811 Fix slow tests in /pkg/cluster
  pkg/cluster/deploybaseresources_test.go
  pkg/env/env.go
  pkg/env/prod.go
  pkg/util/mocks/env/env.go
  pkg/util/oidcbuilder/jwks.go
  pkg/util/oidcbuilder/jwks_test.go
  pkg/util/oidcbuilder/oidcbuilder.go
  pkg/util/oidcbuilder/oidcbuilder_test.go
Labels: size-medium, ready-for-review, loki

#3791 Remove Generate and Lint from containerized build process
  Dockerfile.ci-rp
  Dockerfile.ci-rp.dockerignore
Labels: size-small, ready-for-review, loki

#3816 Separate Makefile targets for local vs containerized
  .pipelines/ci.yml
  Makefile
  docs/admin-portal.md
Labels: size-large, ready-for-review, loki

#3787 Docker file change replace as with AS
  Dockerfile.ci-rp
Labels: size-small, ready-for-review

#3473 Only perform machineconfig reconciliation during OpenShift upgrades
  cmd/aro/operator.go
  pkg/cluster/arooperator.go
  pkg/cluster/install.go
  pkg/operator/controllers/base/aro_controller.go
  pkg/operator/controllers/dnsmasq/cluster_controller.go
  pkg/operator/controllers/dnsmasq/cluster_controller_test.go
  pkg/operator/controllers/dnsmasq/machineconfig_controller.go
  pkg/operator/controllers/dnsmasq/machineconfig_controller_test.go
  pkg/operator/controllers/dnsmasq/machineconfigpool_controller.go
  pkg/operator/controllers/dnsmasq/machineconfigpool_controller_test.go
  pkg/operator/deploy/deploy.go
  pkg/operator/flags.go
  pkg/util/mocks/operator/deploy/deploy.go
  pkg/util/version/clusterversion.go
  test/e2e/operator.go
  test/util/clienthelper/hookclient.go
Labels: ready-for-review, next-release, skippy

#3818 ARO-10003: Add managed flag to etchosts controller
  pkg/operator/controllers/etchosts/cluster_controller.go
  pkg/operator/controllers/etchosts/cluster_controller_test.go
  pkg/operator/controllers/etchosts/machineconfig_controller.go
  pkg/operator/controllers/etchosts/machineconfig_controller_test.go
  pkg/operator/flags.go
  test/e2e/operator.go
Labels: next-release, loki

#3802 MI/WI - Generate secrets for platform identities
  pkg/api/admin/platformworkloadidentityroleset.go
  pkg/api/admin/platformworkloadidentityroleset_convert.go
  pkg/api/platformworkloadidentityroleset.go
  pkg/cluster/workloadidentityresources.go
  pkg/cluster/workloadidentityresources_test.go
Labels: ready-for-review, loki, chainsaw

#3837 ARO-9990: Update etchosts controller to use ForceReconcilation flag
  pkg/operator/controllers/etchosts/cluster_controller.go
  pkg/operator/controllers/etchosts/cluster_controller_test.go
  pkg/operator/controllers/etchosts/machineconfig_controller.go
  pkg/operator/controllers/etchosts/machineconfig_controller_test.go
  pkg/operator/flags.go
  test/e2e/operator.go
Labels: ready-for-review, next-release, loki

#3845 [SFI] Fix CVE-2024-41110
  go.mod
  go.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/backend/backend.go
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/client/client.go
  vendor/github.com/docker/docker/client/container_create.go
  vendor/github.com/docker/docker/client/container_exec.go
  vendor/github.com/docker/docker/client/container_restart.go
  vendor/github.com/docker/docker/client/container_stop.go
  vendor/github.com/docker/docker/client/container_wait.go
  vendor/github.com/docker/docker/client/errors.go
  vendor/github.com/docker/docker/client/image_list.go
  vendor/github.com/docker/docker/client/network_create.go
  vendor/github.com/docker/docker/client/ping.go
  vendor/github.com/docker/docker/client/request.go
  vendor/github.com/docker/docker/client/service_create.go
  vendor/github.com/docker/docker/client/service_update.go
  vendor/github.com/docker/docker/client/volume_remove.go
  vendor/github.com/docker/docker/pkg/streamformatter/streamformatter.go
  vendor/modules.txt
Labels: ready-for-review

#3846 Remove loki/pipeline-swarm branch from pipeline
  .pipelines/ci.yml
Labels: size-small, loki

#3841 ARO-4518 pass custom manifests(MIWI) to hive cluster deployment as secret
  pkg/cluster/install.go
  pkg/cluster/install_test.go
  pkg/hive/install.go
  pkg/hive/manager.go
  pkg/hive/resources.go
  pkg/hive/resources_test.go
  pkg/util/mocks/hive/hive.go
Labels: ready-for-review, chainsaw

#3840 Remove dnf cronjob
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/scripts/gatewayVMSS.sh
  pkg/deploy/generator/scripts/rpVMSS.sh
  pkg/deploy/generator/scripts/util-common.sh
  pkg/deploy/generator/scripts/util-packages.sh
  pkg/deploy/generator/scripts/util-system.sh
Labels: enhancement, ready-for-review, chainsaw

#3822 Fix make aro build in onebranch
  .pipelines/onebranch/templates/template-buildrp-buildaro.yml
Labels: size-small, ready-for-review, release-blocker, next-release, skippy

#3850 Fix cleaning the gratis subscription
  .pipelines/clean-subscription.yml
  .pipelines/templates/template-clean-subscription.yml
Labels: bug, size-small, next-up, ready-for-review, next-release, skippy

#3799 Shubhadapaithankar/aro-9323-cirp-mvp
  .pipelines/ci.yml
  .pipelines/templates/template-acr-push.yml
  Dockerfile.ci-rp
  Makefile
Labels: ready-for-review, loki

#3852 Removed non-containerized stuff from the CI pipeline.
  .pipelines/ci.yml
Labels: size-small, ready-for-review, loki

#3865 Remove podman network causing outbound latency
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/scripts/gatewayVMSS.sh
  pkg/deploy/generator/scripts/rpVMSS.sh
  pkg/deploy/generator/scripts/util-services.sh
  pkg/deploy/generator/scripts/util-system.sh
Labels: bug, next-up, ready-for-review, release-blocker, next-release

#3864 Cluster MSI follow-up
  pkg/cluster/clustermsi.go
  pkg/cluster/clustermsi_test.go
  pkg/util/azureclient/azuresdk/armmsi/generate.go
  pkg/util/azureclient/azuresdk/azsecrets/generate.go
  pkg/util/mocks/azureclient/azuresdk/armmsi/armmsi.go
  pkg/util/mocks/azureclient/azuresdk/azsecrets/azsecrets.go
Labels: ready-for-review, chainsaw
