Repository Azure/ARO-RP, pull requests merged in 2024-12, with the labels that each got.

#3977 MIWI bug fix - deny assignment
  pkg/cluster/deploybaseresources_additional.go
  pkg/cluster/deploybaseresources_additional_test.go
Labels: ready-for-review, chainsaw

#3982 Add FPSP to MIWI deny assignment ExcludePrincipals
  pkg/cluster/deploybaseresources_additional.go
  pkg/cluster/deploybaseresources_additional_test.go
Labels: ready-for-review, chainsaw

#3987 Fix image syncing
  cmd/aro/mirror.go
  pkg/cluster/deploybaseresources_additional_test.go
Labels: bug, priority-high, size-small, next-up, ready-for-review, release-blocker, go, skippy

#3978 Split out some env vars into their own section in the Compose file
  .pipelines/ci.yml
  docker-compose.yml
  hack/e2e/run-rp-and-e2e.sh
Labels: skippy

#3951 Don't scan generated code for CodeQL
  .github/codeql/codeql-config-go.yml
  .github/codeql/codeql-config-javascript.yml
  .github/codeql/codeql-config-python.yml
  .github/workflows/codeql-analysis.yml
Labels: ready-for-review

#3984 Removing Gateway and StorageAccount domain attributes
  pkg/deploy/config.go
  pkg/deploy/devconfig.go
Labels: ready-for-review

#3974 Dynamic image tagging using PR-specific variables in Azure DevOps pip…
  .pipelines/ci.yml
  .pipelines/templates/template-acr-push.yml
Labels: ready-for-review, loki

#3947 ARO-3258: propagate errors of ARO PullSecret controller to ARO operator
  pkg/operator/controllers/pullsecret/pullsecret_controller.go
  pkg/operator/controllers/pullsecret/pullsecret_controller_test.go
Labels: chainsaw

#4003 fix typo in curl snippet
  docs/deploy-development-rp.md
Labels: ready-for-review, chainsaw

#4009 Ensure E2E clusters are deleted
  hack/e2e/run-rp-and-e2e.sh
Labels: ready-for-review, chainsaw

#3966 MIWI cluster Dynamic Validation update for strict 1:1 matching for provided Platform Workload Identity to expected OCP Operators
  pkg/api/v20240812preview/openshiftcluster_validatestatic.go
  pkg/api/v20240812preview/openshiftcluster_validatestatic_test.go
  pkg/cluster/cluster.go
  pkg/cluster/delete.go
  pkg/cluster/delete_test.go
  pkg/cluster/deploybaseresources.go
  pkg/cluster/deploybaseresources_additional.go
  pkg/cluster/deploybaseresources_test.go
  pkg/cluster/workloadidentityresources.go
  pkg/cluster/workloadidentityresources_test.go
  pkg/util/platformworkloadidentity/platformworkloadidentityrolesbyversion.go
  pkg/util/platformworkloadidentity/platformworkloadidentityrolesbyversion_test.go
  pkg/validate/dynamic/platformworkloadidentityprofile.go
  pkg/validate/dynamic/platformworkloadidentityprofile_test.go
Labels: ready-for-review, chainsaw

#4027 Quit checking ClusterDeployment status conditions during cluster installation
  pkg/cluster/install.go
Labels: chainsaw

#4016 pass fp cred to the dynamic validator for miwi flow
  pkg/validate/openshiftcluster_validatedynamic.go
Labels: size-small, ready-for-review, next-release, chainsaw

#3997 improve federated cred naming
  pkg/cluster/workloadidentityresources_test.go
  pkg/util/platformworkloadidentity/federatedcredentials.go
  pkg/util/platformworkloadidentity/federatedcredentials_test.go
  pkg/validate/dynamic/platformworkloadidentityprofile_test.go
Labels: ready-for-review, chainsaw
