Repository Azure/ARO-RP, pull requests merged in 2024-07, with the labels that each got.

#3611 Add validation for default CIDR range
  pkg/api/error.go
  pkg/api/openshiftcluster.go
  pkg/api/v20191231preview/openshiftcluster_validatestatic.go
  pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20200430/openshiftcluster_validatestatic.go
  pkg/api/v20200430/openshiftcluster_validatestatic_test.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20220401/openshiftcluster_validatestatic.go
  pkg/api/v20220401/openshiftcluster_validatestatic_test.go
  pkg/api/v20220904/openshiftcluster_validatestatic.go
  pkg/api/v20220904/openshiftcluster_validatestatic_test.go
  pkg/api/v20230401/openshiftcluster_validatestatic.go
  pkg/api/v20230401/openshiftcluster_validatestatic_test.go
  pkg/api/v20230701preview/openshiftcluster_validatestatic.go
  pkg/api/v20230701preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20230904/openshiftcluster_validatestatic.go
  pkg/api/v20230904/openshiftcluster_validatestatic_test.go
  pkg/api/v20231122/openshiftcluster_validatestatic.go
  pkg/api/v20231122/openshiftcluster_validatestatic_test.go
  pkg/api/v20240812preview/openshiftcluster_validatestatic.go
  pkg/api/v20240812preview/openshiftcluster_validatestatic_test.go
Labels: priority-medium, ready-for-review, firefly

#3530 [ARO-7181] Upgrade the ARO Operator, then update the Cluster object
  pkg/api/admin/openshiftcluster.go
  pkg/api/openshiftcluster.go
  pkg/cluster/adminupdate_test.go
  pkg/cluster/arooperator.go
  pkg/cluster/arooperator_test.go
  pkg/cluster/install.go
  pkg/operator/deploy/deploy.go
  pkg/util/mocks/operator/deploy/deploy.go
Labels: bug, operator, go, skippy

#3664 Update hive-generate-config.sh to accept differing versions
  docs/hive.md
  hack/hive-generate-config.sh
  hack/util.sh
Labels: documentation, enhancement, ready-for-review, dependencies, chainsaw

#3662 Bump Hive Image to commit b1ac27b248 - ARO-5063
  cmd/aro/mirror.go
  go.mod
  go.sum
  hack/hive-generate-config.sh
  vendor/k8s.io/klog/v2/klog.go
  vendor/modules.txt
Labels: dependencies, chainsaw

#3292 ARO Operator - Reduce unnecessary reconciles by limiting watched resources/changes
  pkg/operator/controllers/autosizednodes/autosizednodes_controller.go
  pkg/operator/controllers/banner/banner_controller.go
  pkg/operator/controllers/checkers/clusterdnschecker/controller.go
  pkg/operator/controllers/checkers/ingresscertificatechecker/controller.go
  pkg/operator/controllers/checkers/internetchecker/controller.go
  pkg/operator/controllers/checkers/serviceprincipalchecker/controller.go
  pkg/operator/controllers/cloudproviderconfig/cloudproviderconfig_controller.go
  pkg/operator/controllers/clusteroperatoraro/clusteroperatoraro_controller.go
  pkg/operator/controllers/dnsmasq/cluster_controller.go
  pkg/operator/controllers/genevalogging/genevalogging_controller.go
  pkg/operator/controllers/guardrails/guardrails_controller.go
  pkg/operator/controllers/ingress/ingress_controller.go
  pkg/operator/controllers/machinehealthcheck/machinehealthcheck_controller.go
  pkg/operator/controllers/machineset/machineset_controller.go
  pkg/operator/controllers/monitoring/monitoring_controller.go
  pkg/operator/controllers/muo/muo_controller.go
  pkg/operator/controllers/pullsecret/pullsecret_controller.go
  pkg/operator/controllers/rbac/rbac_controller.go
  pkg/operator/controllers/routefix/routefix_controller.go
  pkg/operator/controllers/storageaccounts/storageaccount_controller.go
  pkg/operator/controllers/subnets/subnets_controller.go
  pkg/operator/controllers/workaround/workaround_controller.go
  pkg/operator/predicates/predicates.go
Labels: hold, ready-for-review, loki

#3454 Move to maintained yaml lib
  go.mod
  hack/gendevconfig/gendevconfig.go
  hack/genhiveconfig/genhiveconfig.go
  hack/validate-imports/validate-imports.go
  pkg/cluster/clusterserviceprincipal.go
  pkg/cluster/clusterserviceprincipal_test.go
  pkg/cluster/kubeconfig.go
  pkg/cluster/kubeconfig_test.go
  pkg/deploy/config.go
  pkg/operator/controllers/alertwebhook/alertwebhook_controller.go
  pkg/operator/controllers/monitoring/monitoring_controller.go
  pkg/operator/controllers/muo/template_test.go
  pkg/portal/kubeconfig/proxy.go
  pkg/util/dynamichelper/unstructuredobj.go
  test/e2e/operator.go
Labels: size-small, ready-for-review, go, skippy

#3646 Containerize `./hack/tunnel`
  Dockerfile.ci-tunnel
  Makefile
Labels: ready-for-review, loki

#3617 New cmd to populate PlatformWorkloadIdentityRoleSets in dev and prod
  cmd/aro/const.go
  cmd/aro/main.go
  cmd/aro/update_role_sets.go
  pkg/env/core.go
  pkg/util/cluster/cluster.go
  pkg/util/rolesets/const.go
Labels: next-release, chainsaw

#3629 [ARO-5368] Try and log the VM info + console log on failure
  cmd/aro/rp.go
  pkg/cluster/failurediagnostics/diagnostics.go
  pkg/cluster/failurediagnostics/virtualmachines.go
  pkg/cluster/failurediagnostics/virtualmachines_test.go
  pkg/cluster/gatherlogs.go
  pkg/cluster/graph/manager_test.go
  pkg/cluster/install_test.go
  pkg/frontend/admin_hive_clusterdeployment_get_test.go
  pkg/frontend/admin_openshiftcluster_approvecsr_test.go
  pkg/frontend/admin_openshiftcluster_cordonnode_test.go
  pkg/frontend/admin_openshiftcluster_delete_managedresource_test.go
  pkg/frontend/admin_openshiftcluster_drainnode_test.go
  pkg/frontend/admin_openshiftcluster_etcdcertificaterenew_test.go
  pkg/frontend/admin_openshiftcluster_etcdrecovery_test.go
  pkg/frontend/admin_openshiftcluster_kubernetesobjects_test.go
  pkg/frontend/admin_openshiftcluster_kubernetespods_logs_test.go
  pkg/frontend/admin_openshiftcluster_list_test.go
  pkg/frontend/admin_openshiftcluster_redeployvm_test.go
  pkg/frontend/admin_openshiftcluster_resources_list_test.go
  pkg/frontend/admin_openshiftcluster_serialconsole.go
  pkg/frontend/admin_openshiftcluster_startvm_test.go
  pkg/frontend/admin_openshiftcluster_stopvm_test.go
  pkg/frontend/admin_openshiftcluster_vmresize_test.go
  pkg/frontend/admin_openshiftcluster_vmsizelist_test.go
  pkg/frontend/admin_openshiftversion_list_test.go
  pkg/frontend/admin_openshiftversion_put_test.go
  pkg/frontend/admin_platformworkloadidentityroleset_list_test.go
  pkg/frontend/admin_platformworkloadidentityroleset_put_test.go
  pkg/frontend/adminactions/applens.go
  pkg/frontend/adminactions/azureactions.go
  pkg/frontend/adminactions/generate.go
  pkg/frontend/adminactions/vmserialconsole.go
  pkg/frontend/adminactions/vmserialconsole_test.go
  pkg/frontend/asyncoperationresult_get_test.go
  pkg/frontend/asyncoperationsstatus_get_test.go
  pkg/frontend/clustermanager_delete_test.go
  pkg/frontend/clustermanager_get_test.go
  pkg/frontend/clustermanager_putorpatch_test.go
  pkg/frontend/fixetcd_test.go
  pkg/frontend/frontend.go
  pkg/frontend/openshiftcluster_applensdetectors.go
  pkg/frontend/openshiftcluster_applensdetectors_test.go
  pkg/frontend/openshiftcluster_delete_test.go
  pkg/frontend/openshiftcluster_get_test.go
  pkg/frontend/openshiftcluster_list_test.go
  pkg/frontend/openshiftcluster_preflightvalidation_test.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/frontend/openshiftclustercredentials_post_test.go
  pkg/frontend/openshiftclusterkubeconfigcredentials_post_test.go
  pkg/frontend/openshiftversions_list_test.go
  pkg/frontend/platformworkloadidentityrolesets_list_test.go
  pkg/frontend/security_test.go
  pkg/frontend/subscriptions_put_test.go
  pkg/util/azureclient/mgmt/compute/virtualmachines_addons.go
  pkg/util/mocks/adminactions/adminactions.go
  pkg/util/mocks/azureclient/mgmt/compute/compute.go
  pkg/util/mocks/storage/storage.go
  pkg/util/storage/generate.go
  pkg/util/storage/manager.go
  test/e2e/adminapi_serialconsole.go
Labels: enhancement, size-medium, go, skippy

#3544 Add doc on rotating full RP env VPN certs
  docs/deploy-full-rp-service-in-dev.md
Labels: documentation, chainsaw

#3680 Update controllergen commands to work with 0.9.0
  go.mod
  go.sum
  pkg/operator/deploy/staticresources/aro.openshift.io_clusters.yaml
  pkg/operator/deploy/staticresources/preview.aro.openshift.io_previewfeatures.yaml
  pkg/operator/deploy/staticresources/worker/role.yaml
  pkg/operator/generate.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-tools/pkg/crd/conv.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/known_types.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/crd.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/topology.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/validation.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/schema.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/spec.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/genall.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/loader/loader.go
  vendor/sigs.k8s.io/controller-tools/pkg/loader/refs.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/parse.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/zip.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/version/version.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/zz_generated.markerhelp.go
Labels: size-small, ready-for-review, dependencies, go, skippy

#3695 Bug fix - Add nil pointer check for LoadBalancerProfile in cluster metrics
  pkg/backend/metrics.go
  pkg/backend/metrics_test.go
Labels: bug, ready-for-review, release-blocker, next-release, chainsaw

#3642 [ARO-9169] Remove disused clustermanager frontend code
  pkg/frontend/clustermanager_delete.go
  pkg/frontend/clustermanager_delete_test.go
  pkg/frontend/clustermanager_get.go
  pkg/frontend/clustermanager_get_test.go
  pkg/frontend/clustermanager_putorpatch.go
  pkg/frontend/clustermanager_putorpatch_test.go
  pkg/frontend/clustermanager_type.go
  pkg/frontend/clustermanager_type_test.go
  pkg/frontend/frontend.go
Labels: size-small, ready-for-review, go, skippy

#3648 Clean up some duplicated code in cmd/
  cmd/aro/const.go
  cmd/aro/gateway.go
  cmd/aro/main.go
  cmd/aro/monitor.go
  cmd/aro/portal.go
  cmd/aro/rp.go
  cmd/aro/update_ocp_versions.go
  cmd/aro/update_role_sets.go
  pkg/database/fromenv.go
  pkg/env/core.go
  pkg/env/helpers.go
  pkg/env/msiauthorizer.go
  pkg/util/encryption/azure.go
  pkg/util/mocks/env/core.go
  pkg/util/mocks/env/env.go
Labels: size-small, go, skippy

#3687 Hotfix: compute API version used in ARM templates
  pkg/deploy/assets/cluster-development-predeploy.json
  pkg/deploy/assets/env-development.json
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_cluster.go
  pkg/deploy/generator/resources_dev.go
  pkg/util/azureclient/apiversions.go
Labels: ready-for-review, release-blocker, next-release, chainsaw

#3686 Preflight update and tests
  pkg/api/preflight.go
  pkg/api/subscriptiondocument_example.go
  pkg/frontend/openshiftcluster_preflightvalidation.go
  pkg/frontend/openshiftcluster_preflightvalidation_test.go
Labels: ready-for-review

#3500 Refactor/remove private dns zone
  pkg/cluster/delete.go
  pkg/cluster/removeprivatednszone.go
  pkg/cluster/removeprivatednszone_test.go
  pkg/util/mocks/net/net.go
  pkg/util/net/generate.go
  pkg/util/net/net.go
  pkg/util/net/net_test.go
  pkg/util/ready/ready.go
  pkg/util/ready/ready_test.go
  pkg/util/version/clusterversion.go
Labels: good first issue, size-medium, go

#3503 log outbound correlation data
  pkg/api/correlation.go
  pkg/cluster/cluster.go
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/scripts/rpVMSS.sh
  pkg/frontend/middleware/log.go
  pkg/frontend/middleware/middleware.go
  pkg/frontend/openshiftcluster_delete.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/util/azureclient/applens/applens_client_options.go
  pkg/util/azureclient/authz/remotepdp/client.go
  pkg/util/azureclient/azuresdk/armstorage/accounts.go
  pkg/util/azureclient/decorators.go
  pkg/util/azureclient/keyvault/base.go
  pkg/util/azureclient/mgmt/authorization/denyassignment.go
  pkg/util/azureclient/mgmt/authorization/roleassignments.go
  pkg/util/azureclient/mgmt/authorization/roledefinitions.go
  pkg/util/azureclient/mgmt/compute/diskencryptionsets.go
  pkg/util/azureclient/mgmt/compute/disks.go
  pkg/util/azureclient/mgmt/compute/resourceskus.go
  pkg/util/azureclient/mgmt/compute/usage.go
  pkg/util/azureclient/mgmt/compute/virtualmachines.go
  pkg/util/azureclient/mgmt/compute/virtualmachinescalesetvms.go
  pkg/util/azureclient/mgmt/compute/virtualmachinesscalesets.go
  pkg/util/azureclient/mgmt/containerregistry/registries.go
  pkg/util/azureclient/mgmt/containerregistry/tokens.go
  pkg/util/azureclient/mgmt/containerservice/managedclusters.go
  pkg/util/azureclient/mgmt/dns/recordsets.go
  pkg/util/azureclient/mgmt/dns/zones.go
  pkg/util/azureclient/mgmt/features/deployments.go
  pkg/util/azureclient/mgmt/features/providers.go
  pkg/util/azureclient/mgmt/features/resourcegroups.go
  pkg/util/azureclient/mgmt/features/resources.go
  pkg/util/azureclient/mgmt/msi/userassignedidentities.go
  pkg/util/azureclient/mgmt/network/flowlogs.go
  pkg/util/azureclient/mgmt/network/interfaces.go
  pkg/util/azureclient/mgmt/network/loadbalancers.go
  pkg/util/azureclient/mgmt/network/privateendpoints.go
  pkg/util/azureclient/mgmt/network/privatelinkservices.go
  pkg/util/azureclient/mgmt/network/publicipaddresses.go
  pkg/util/azureclient/mgmt/network/routetable.go
  pkg/util/azureclient/mgmt/network/securitygroups.go
  pkg/util/azureclient/mgmt/network/subnets.go
  pkg/util/azureclient/mgmt/network/usage.go
  pkg/util/azureclient/mgmt/network/virtualnetworkpeerings.go
  pkg/util/azureclient/mgmt/network/virtualnetworks.go
  pkg/util/azureclient/mgmt/privatedns/privatezones.go
  pkg/util/azureclient/mgmt/privatedns/virtualnetworklinks.go
  pkg/util/azureclient/mgmt/storage/accounts.go
  pkg/util/azureclient/roundtripper.go
  pkg/util/azureclient/roundtripper_test.go
  pkg/util/log/log.go
Labels: go

#3710 Always do group expansion for CheckAccess subjects
  pkg/util/azureclient/authz/remotepdp/const.go
  pkg/util/azureclient/authz/remotepdp/types.go
  pkg/validate/dynamic/dynamic.go
Labels: next-up, ready-for-review, next-release

#3715 Clean up some lint errors found on golangci-lint 1.59.1
  pkg/api/openshiftcluster.go
  pkg/portal/cluster/nodes.go
  pkg/util/azureclient/applens/applens_client.go
Labels: size-small, ready-for-review, go, skippy

#3674 Fixed context issue
  go.mod
  go.sum
  pkg/database/cosmosdb/zz_generated_authorizer.go
  pkg/database/cosmosdb/zz_generated_cosmosdb.go
  pkg/database/database.go
  vendor/github.com/jewzaam/go-cosmosdb/pkg/gencosmosdb/bindata.go
  vendor/modules.txt
Labels: bug, next-up, ready-for-review, release-blocker, next-release, go, firefly

#3624 WI/MI CLI Phase 1 - Base API functionality
  python/az/aro/azext_aro/__init__.py
  python/az/aro/azext_aro/_aad.py
  python/az/aro/azext_aro/_actions.py
  python/az/aro/azext_aro/_client_factory.py
  python/az/aro/azext_aro/_dynamic_validators.py
  python/az/aro/azext_aro/_params.py
  python/az/aro/azext_aro/_rbac.py
  python/az/aro/azext_aro/_validators.py
  python/az/aro/azext_aro/azext_metadata.json
  python/az/aro/azext_aro/commands.py
  python/az/aro/azext_aro/custom.py
  python/az/aro/azext_aro/tests/latest/unit/test_validators.py
  python/az/aro/setup.py
Labels: ready-for-review, loki, chainsaw

#3696 Deploy shared dev key vault for mock MSI certificates
  docs/deploy-full-rp-service-in-dev.md
  docs/prepare-a-shared-rp-development-environment.md
  hack/devtools/deploy-shared-env.sh
  pkg/deploy/assets/env-development.json
  pkg/deploy/assets/rp-development-miwi.json
  pkg/deploy/generator/const.go
  pkg/deploy/generator/generators.go
  pkg/deploy/generator/resources_dev.go
  pkg/deploy/generator/resources_miwi_dev.go
  pkg/deploy/generator/templates_miwi_dev.go
  pkg/util/cluster/cluster.go
  pkg/util/rbac/rbac.go
Labels: ready-for-review, chainsaw

#3683 shared utility function to check if a cluster is workload identity
  pkg/cluster/delete.go
  pkg/cluster/deploybaseresources.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/operator/deploy/deploy.go
  pkg/util/wimi/iswimi.go
  pkg/util/wimi/iswimi_test.go
Labels: chainsaw

#3643 ARO-6756 Remove usecheckaccess feature and environment variables
  pkg/api/featureflags.go
  pkg/backend/openshiftcluster_test.go
  pkg/cluster/install_version_test.go
  pkg/deploy/assets/rp-production-parameters.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/config.go
  pkg/deploy/devconfig.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/scripts/rpVMSS.sh
  pkg/deploy/generator/templates_rp.go
  pkg/util/liveconfig/checkaccess.go
  pkg/util/liveconfig/dev.go
  pkg/util/liveconfig/manager.go
  pkg/validate/openshiftcluster_validatedynamic.go
  test/util/testliveconfig/liveconfig.go
Labels: ready-for-review, chainsaw

#3691 CIF - ServerError: ZonalAllocationFailed
  hack/hive-config/hive-additional-install-log-regexes.yaml
  pkg/hive/failure/handler.go
  pkg/hive/failure/reasons.go
  pkg/hive/failure/reasons_test.go
Labels: ready-for-review, go, firefly

#3652 [ARO-4562] Migrate DNS to track2 SDK replace dns in cluster.
  pkg/cluster/cluster.go
  pkg/util/dns/dns.go
  pkg/util/dns/dns_test.go
Labels: ready-for-review

#3718 Update MDSD, MDM, Fluentbit base images
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/util/version/const.go
Labels: ready-for-review, dependencies, next-release, chainsaw

#3622 Use latest "in-progress" ARO API for local/E2E cluster creation
  pkg/util/cluster/aroclient.go
  pkg/util/cluster/cluster.go
Labels: ready-for-review, loki

#3721 move iswimi function to openshiftcluster.go
  pkg/api/openshiftcluster.go
  pkg/api/openshiftcluster_test.go
  pkg/cluster/delete.go
  pkg/cluster/deploybaseresources.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/operator/deploy/deploy.go
  pkg/util/wimi/iswimi.go
  pkg/util/wimi/iswimi_test.go
Labels: ready-for-review, chainsaw

#3733 Do not modify user's Azure CLI config in make pyenv target
  Makefile
Labels: ready-for-review

#3731 Increase RP and VMSS disk size from 256GB to 1024GB
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
Labels: ready-for-review, release-blocker, next-release, chainsaw

#3746 Ensure identity headers are persisted in requests to create MIWI clusters
  pkg/api/v20240812preview/openshiftcluster_convert.go
  pkg/frontend/middleware/msi.go
  pkg/frontend/middleware/msi_test.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
Labels: chainsaw
