Repository Azure/ARO-RP, pull requests merged in 2024-06, with the labels that each got.

#3604 Making 4.13.40 as default version for local dev
  pkg/util/version/const.go
Labels: ready-for-review

#3597 Add explicit `ARG ARO_VERSION` to RP build stage in ci-rp
  Dockerfile.ci-rp
  Makefile
Labels: ready-for-review, loki

#3575 Allow customers to annotate CloudCredential resource on update
  .sha256sum
  pkg/api/admin/openshiftcluster.go
  pkg/api/openshiftcluster.go
  pkg/api/v20240812preview/openshiftcluster.go
  pkg/api/v20240812preview/openshiftcluster_convert.go
  pkg/api/v20240812preview/openshiftcluster_validatestatic.go
  pkg/api/v20240812preview/openshiftcluster_validatestatic_test.go
  pkg/client/services/redhatopenshift/mgmt/2024-08-12-preview/redhatopenshift/models.go
  pkg/cluster/arooperator.go
  pkg/cluster/install.go
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/deploy_test.go
  pkg/util/mocks/operator/deploy/deploy.go
  python/client/azure/mgmt/redhatopenshift/v2024_08_12_preview/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2024_08_12_preview/models/_models_py3.py
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2024-08-12-preview/redhatopenshift.json
Labels: ready-for-review, chainsaw

#3514 Add identityURL to internal apis for CMSI usage
  pkg/api/openshiftcluster.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
Labels: size-small, ready-for-review, chainsaw

#3590 Retry failed ARM template deployments during cluster installation when FPSP is missing roleassignments
  pkg/util/arm/deploy.go
  pkg/util/azureerrors/error.go
  pkg/util/azureerrors/error_test.go
  pkg/util/steps/refreshing.go
Labels: bug, ready-for-review, loki

#3609 Revender hive to commit d7ead609f495785360aeea7c318f28fe82f9bcbf
  cmd/aro/mirror.go
  go.mod
  go.sum
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/funcr/funcr.go
  vendor/modules.txt
Labels: ready-for-review, dependencies, next-release, chainsaw

#3583 Use single ARO API/client version in pkg/util/cluster
  pkg/util/cluster/cluster.go
Labels: ready-for-review, loki

#3579 update SDK to track2 in UpdateAPIIPEarly
  pkg/cluster/cluster.go
  pkg/cluster/ipaddresses.go
  pkg/cluster/ipaddresses_test.go
  pkg/util/azureclient/azuresdk/armnetwork/generate.go
  pkg/util/azureclient/azuresdk/armnetwork/interfaces.go
  pkg/util/azureclient/azuresdk/armnetwork/loadbalancers.go
  pkg/util/azureclient/azuresdk/armnetwork/publicipaddresses.go
  pkg/util/azureclient/azuresdk/armnetwork/publicipaddresses_addons.go
  pkg/util/azureclient/azuresdk/common/options.go
  pkg/util/mocks/azureclient/azuresdk/armnetwork/armnetwork.go
Labels: ready-for-review

#3490 Minimal Python container to build `az aro` extension
  Dockerfile.ci-azext-aro
  Makefile
Labels: loki

#3603 Making Gateway and RP Managed Boot Diagnostics
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
Labels: ready-for-review

#3620 Split Makefile PHONY target
  Makefile
Labels: loki

#3633 EnableAutomaticOSUpgrade for dev-proxy-vmss and remove the no longer needed SA params
  pkg/deploy/assets/env-development.json
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_dev.go
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
Labels: ready-for-review, next-release

#3630 reduce the amount of package names in the logs
  pkg/cluster/adminupdate_test.go
  pkg/cluster/install_test.go
  pkg/util/steps/condition.go
  pkg/util/steps/condition_test.go
  pkg/util/steps/runner.go
  pkg/util/steps/runner_test.go
Labels: enhancement, ready-for-review, skippy

#3639 ARO-8423: fix client generation issue with new Identity field for MIWI
  .sha256sum
  pkg/client/services/redhatopenshift/mgmt/2024-08-12-preview/redhatopenshift/models.go
  pkg/swagger/swagger.go
  python/client/azure/mgmt/redhatopenshift/v2024_08_12_preview/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2024_08_12_preview/models/_models_py3.py
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2024-08-12-preview/redhatopenshift.json
Labels: ready-for-review, chainsaw

#3613 Adding logging statements for pullsecret controller
  pkg/operator/controllers/pullsecret/pullsecret_controller.go
  pkg/operator/controllers/pullsecret/pullsecret_controller_test.go
Labels: ready-for-review, chainsaw

#3625 [ARO-4562] Migrate DNS to track2 SDK, arm dns client creation.
  go.mod
  go.sum
  pkg/util/azureclient/azuresdk/armdns/generate.go
  pkg/util/azureclient/azuresdk/armdns/recordsets.go
  pkg/util/azureclient/azuresdk/armdns/zones.go
  pkg/util/mocks/azureclient/azuresdk/armdns/armdns.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/LICENSE.txt
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/README.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/autorest.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/build.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/client_factory.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/models.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/models_serde.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/options.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/recordsets_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/resourcereference_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/response_types.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/dns/armdns/zones_client.go
  vendor/modules.txt
Labels: ready-for-review
