Repository Azure/ARO-RP, pull requests merged in 2024-08, with the labels that each got.

#3701 Add panic recovery within endLease
  pkg/backend/openshiftcluster.go
Labels: bug, ready-for-review, chainsaw

#3751 Correct mdsd image sha to distroless checksum
  pkg/util/version/const.go
Labels: ready-for-review, dependencies, chainsaw

#3759 Minor document changes
  docs/deploy-development-rp.md
  docs/hive.md
Labels: documentation, size-small

#3766 Sync fluentbit image with correct checksum seen in arosvc registry
  pkg/util/version/const.go
Labels: release-blocker, dependencies, next-release, chainsaw

#3593 Make runlocal-rp with Container Image
  Makefile
  docs/deploy-development-rp.md
  env.example
  hack/setup_resources.sh
  pkg/env/dev.go
Labels: size-small, loki

#3653 Exclude platform identities from permissions denial
  pkg/cluster/denyassignment.go
  pkg/cluster/denyassignment_test.go
  pkg/cluster/deploybaseresources_additional.go
  pkg/cluster/deploybaseresources_additional_test.go
Labels: chainsaw

#3745 Containerized portal as it runs in prod, locally
  Makefile
  cmd/aro/portal.go
  docs/admin-portal.md
Labels: size-small, ready-for-review, loki

#3782 Allow prerelease OCP versions and version strings with metadata during cluster installation
  pkg/api/validate/format_regexps.go
  pkg/cluster/disableupdates.go
  pkg/cluster/disableupdates_test.go
  pkg/frontend/validate.go
  pkg/frontend/validate_test.go
Labels: ready-for-review, loki

#3741 Update VMSS to Mariner with FIPS enabled
  pkg/deploy/assets/env-development.json
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_dev.go
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/scripts.go
  pkg/deploy/generator/scripts/devProxyVMSS.sh
  pkg/deploy/generator/scripts/gatewayVMSS.sh
  pkg/deploy/generator/scripts/rpVMSS.sh
  pkg/deploy/generator/scripts/util-common.sh
  pkg/deploy/generator/scripts/util-packages.sh
  pkg/deploy/generator/scripts/util-services.sh
  pkg/deploy/generator/scripts/util-system.sh
  pkg/deploy/generator/scripts/util.sh
Labels: release-blocker, next-release, chainsaw

#3796 Fixed to correctly reference the local image tag
  Makefile
Labels: ready-for-review, loki

#3781 ARO-9570: Add a controller to the ARO operator to lay down etchosts
  cmd/aro/operator.go
  pkg/operator/controllers/etchosts/cluster_controller.go
  pkg/operator/controllers/etchosts/etchosts.go
  pkg/operator/controllers/etchosts/etchosts_test.go
  pkg/operator/controllers/etchosts/machineconfig_controller.go
  pkg/operator/flags.go
Labels: next-release, loki
