Repository Azure/ARO-RP, pull requests merged in 2024-02, with the labels that each got.

#3363 Use another method of FIPS validation (fips-detect)
  .pipelines/ci.yml
  Dockerfile.aro-e2e
  Dockerfile.aro-multistage
  Makefile
  hack/fips/validate-fips.sh
Labels: ready-for-review, go, skippy

#3372 Do not exit NSG monitor when unable to get subnet
  pkg/monitor/azure/nsg/nsg.go
Labels: ready-for-review, flake, loki

#3335 Added FP Check for validation
  pkg/backend/openshiftcluster.go
  pkg/validate/openshiftcluster_validatedynamic.go
Labels: ready-for-review, next-release

#2992 HiveNamespace to use docID/clusterID for new Installs
  pkg/cluster/adminupdate_test.go
  pkg/cluster/hive.go
  pkg/cluster/hive_test.go
  pkg/hive/manager.go
  pkg/hive/manager_test.go
  pkg/util/mocks/hive/hive.go
  test/e2e/hive_manager.go
Labels: ready-for-review, skippy

#3170 Allow metricalerts, actiongroups, and activitylogalerts for monitoring in the denyassignment
  pkg/cluster/deploybaseresources_additional.go
Labels: size-small, ready-for-review, skippy

#3366 Wrap K8s client in E2E with retry logic
  test/e2e/adminapi_cluster_getlogs.go
  test/e2e/adminapi_csr.go
  test/e2e/adminapi_delete_managedresource.go
  test/e2e/adminapi_drainnode.go
  test/e2e/adminapi_kubernetesobjects.go
  test/e2e/adminapi_redeployvm.go
  test/e2e/cluster.go
  test/e2e/disk_encryption.go
  test/e2e/dns.go
  test/e2e/helpers.go
  test/e2e/operator.go
  test/e2e/update.go
  test/util/project/project.go
Labels: priority-high, ready-for-review

#3400 Mirror hive revender images
  cmd/aro/mirror.go
Labels: ready-for-review, release-blocker, next-release, chainsaw

#3408 Fix Go 1.20 change around proxy and default user agents
  pkg/portal/kubeconfig/proxy_test.go
  pkg/portal/prometheus/proxy_test.go
Labels: ready-for-review, skippy

#3407 Update Hive dev install
  hack/hive-dev-install.sh
  hack/hive-generate-config.sh
Labels: size-small, ready-for-review

#3406 add archv1 check to multiple ip static validation
  pkg/api/v20230701preview/openshiftcluster_validatestatic.go
  pkg/api/v20230701preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20231122/openshiftcluster_validatestatic.go
  pkg/api/v20231122/openshiftcluster_validatestatic_test.go
Labels: ready-for-review, release-blocker, next-release, loki

#3401 Don't add security context on <4.11 as OpenShift restricted SCCs do not tolerate it
  pkg/cluster/cluster.go
  pkg/cluster/install.go
  pkg/operator/controllers/genevalogging/genevalogging.go
  pkg/operator/controllers/genevalogging/genevalogging_test.go
  pkg/operator/controllers/muo/config/config.go
  pkg/operator/controllers/muo/muo_controller.go
  pkg/operator/controllers/muo/muo_controller_test.go
  pkg/operator/controllers/muo/staticresources/deployment.yaml.tmpl
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/deploy_test.go
  pkg/operator/deploy/staticresources/master/deployment.yaml.tmpl
  pkg/operator/deploy/staticresources/worker/deployment.yaml.tmpl
  pkg/operator/helpers.go
  pkg/operator/helpers_test.go
  pkg/util/version/clusterversion.go
  pkg/util/version/clusterversion_test.go
Labels: next-release

#3395 Update `az aro` permissions validation to mirror RP frontend validation
  python/az/aro/azext_aro/_dynamic_validators.py
  python/az/aro/azext_aro/tests/latest/unit/test_dynamic_validators.py
Labels: loki

#3343 Make NSG Monitor run every 10 minutes
  pkg/monitor/azure/nsg/nsg.go
  pkg/monitor/azure/nsg/nsg_test.go
  pkg/monitor/worker.go
Labels: ready-for-review, next-release

#3415 Revert pkg/util/cluster creation to use 20230904 API
  pkg/util/azureclient/mgmt/redhatopenshift/2023-09-04/redhatopenshift/openshiftclusters.go
  pkg/util/azureclient/mgmt/redhatopenshift/2023-09-04/redhatopenshift/openshiftclusters_addons.go
  pkg/util/azureclient/mgmt/redhatopenshift/2023-09-04/redhatopenshift/operations.go
  pkg/util/azureclient/mgmt/redhatopenshift/2023-09-04/redhatopenshift/operations_addons.go
  pkg/util/cluster/cluster.go
Labels: priority-high, ready-for-review, release-blocker, next-release

#3403 Fix failures provisioning a cluster in dev due to NSG attaching
  pkg/cluster/deploybaseresources.go
  pkg/cluster/deploybaseresources_test.go
  pkg/cluster/install.go
  pkg/util/steps/refreshing.go
Labels: size-small, ready-for-review, go, skippy

#3413 Clean up some of the CI/linting/generate
  .github/workflows/ci-go.yml
  .github/workflows/golint.yml
  .yaml-lint.yml
  Dockerfile.ci
  Makefile
  hack/ci-utils/build.sh
  hack/ci-utils/differenceChecker/main.go
  pkg/operator/controllers/workaround/generate.go
  pkg/operator/deploy/staticresources/worker/role.yaml
  pkg/operator/generate.go
  pkg/util/azureclient/applens/applens_client_test.go
  pkg/util/pki/pki.go
  test/util/http/server/server_mock_test.go
Labels: ready-for-review, skippy

#3396 Adding segregation of resultType for CloudError
  pkg/backend/openshiftcluster.go
  pkg/backend/openshiftcluster_test.go
  pkg/frontend/frontend.go
  pkg/frontend/frontend_test.go
Labels: ready-for-review, next-release, go, firefly

#3418 Do not run Azure Host Servicing test in non-development environments
  test/e2e/dns.go
Labels: ready-for-review, release-blocker, next-release

#3414 Fix shared_cluster.sh
  hack/shared-cluster.sh
Labels: bug, priority-low, size-small, ready-for-review

#3420 Back port v2023-11-22 Azure REST specs
  .sha256sum
  pkg/api/openshiftcluster.go
  pkg/api/v20231122/openshiftcluster.go
  pkg/api/v20231122/openshiftcluster_example.go
  pkg/api/v20231122/openshiftcluster_validatestatic.go
  pkg/client/services/redhatopenshift/mgmt/2023-11-22/redhatopenshift/enums.go
  pkg/client/services/redhatopenshift/mgmt/2023-11-22/redhatopenshift/models.go
  pkg/swagger/generator.go
  python/client/azure/mgmt/redhatopenshift/v2023_11_22/models/_azure_red_hat_open_shift_client_enums.py
  python/client/azure/mgmt/redhatopenshift/v2023_11_22/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2023_11_22/models/_models_py3.py
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2023-11-22/examples/OpenShiftClusters_Get.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2023-11-22/examples/OpenShiftClusters_List.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2023-11-22/examples/OpenShiftClusters_ListByResourceGroup.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2023-11-22/redhatopenshift.json
Labels: ready-for-review, loki

#3404 Create oic storage account in dev
  docs/deploy-full-rp-service-in-dev.md
  docs/prepare-a-shared-rp-development-environment.md
  hack/devtools/deploy-shared-env.sh
  pkg/deploy/assets/rp-oic.json
  pkg/deploy/generator/const.go
  pkg/deploy/generator/generators.go
  pkg/deploy/generator/resouces_oic.go
  pkg/deploy/generator/templates_oic.go
  pkg/util/rbac/rbac.go
Labels: ready-for-review, chainsaw
