Repository Azure/ARO-RP, pull requests merged in 2024-01, with the labels that each got.

#3319 added exempted user to guardrails
  cmd/aro/operator.go
  pkg/operator/controllers/guardrails/guardrails_config.go
  pkg/operator/controllers/guardrails/guardrails_controller.go
  pkg/operator/controllers/guardrails/guardrails_controller_test.go
  pkg/operator/controllers/guardrails/policies/gktemplates-src/library/common.rego
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-delete-pull-secret.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-machine-config.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-master-toleration-taints.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-privileged-namespace.yaml
Labels: size-small, ready-for-review, next-release, skippy

#3341 Remove aro build tag as it's not needed for the ARO-RP
  .github/workflows/ci-go.yml
  .github/workflows/codeql-analysis.yml
  Makefile
Labels: ready-for-review

#3284 Fixing cert metric emitting condition param
  pkg/monitor/cluster/certificateexpirationstatuses.go
  pkg/monitor/cluster/certificateexpirationstatuses_test.go
Labels: ready-for-review, next-release

#3294 Add maintenance state for customer action needed
  pkg/api/admin/openshiftcluster.go
  pkg/api/admin/openshiftcluster_validatestatic.go
  pkg/api/admin/openshiftcluster_validatestatic_test.go
  pkg/api/openshiftcluster.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/monitor/cluster/maintenance.go
  pkg/monitor/cluster/maintenance_test.go
Labels: ready-for-review, next-release

#3349 Add Go 1.20 images (and ose-tools-rhel8 for 4.14)
  cmd/aro/mirror.go
Labels: ready-for-review, skippy

#3324 Improve NSG monitoring by retrieving subnet only once
  pkg/monitor/azure/nsg/nsg.go
  pkg/monitor/azure/nsg/nsg_test.go
Labels: ready-for-review, next-release

#3254 Make env know what the service component its running is
  cmd/aro/dbtoken.go
  cmd/aro/deploy.go
  cmd/aro/gateway.go
  cmd/aro/monitor.go
  cmd/aro/portal.go
  cmd/aro/rp.go
  cmd/aro/update_ocp_versions.go
  hack/aead/aead.go
  hack/cluster/cluster.go
  hack/db/db.go
  hack/gendevconfig/gendevconfig.go
  hack/portalauth/portalauth.go
  pkg/cluster/cluster.go
  pkg/env/core.go
  pkg/env/dev.go
  pkg/env/env.go
  pkg/env/msiauthorizer.go
  pkg/env/prod.go
  pkg/util/mocks/env/core.go
  pkg/util/mocks/env/env.go
Labels: ready-for-review, go, skippy

#3094 Move default openshift version
  cmd/aro/const.go
  cmd/aro/dbtoken.go
  cmd/aro/gateway.go
  cmd/aro/main.go
  cmd/aro/monitor.go
  cmd/aro/portal.go
  cmd/aro/rp.go
  cmd/aro/update_ocp_versions.go
  pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20200430/openshiftcluster_validatestatic_test.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20230904/openshiftcluster_validatestatic_test.go
  pkg/frontend/admin_openshiftversion_put.go
  pkg/frontend/admin_openshiftversion_put_test.go
  pkg/frontend/changefeed.go
  pkg/frontend/frontend.go
  pkg/frontend/openshiftcluster_preflightvalidation_test.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
  pkg/frontend/openshiftversions_list.go
  pkg/frontend/openshiftversions_list_test.go
  pkg/frontend/validate.go
  pkg/monitor/cluster/clusterversions.go
  pkg/monitor/cluster/clusterversions_test.go
  pkg/util/dynamichelper/discovery/cache_fallback_discovery_client_test.go
  pkg/util/version/const.go
  test/e2e/setup.go
Labels: loki

#3367 Add permissions stanza to yamllint GH action
  .github/workflows/yamllint.yml
Labels: ready-for-review

#3358 Refactoring per comments in #3324
  pkg/monitor/azure/nsg/nsg.go
  pkg/monitor/azure/nsg/nsg_test.go
Labels: ready-for-review

#3364 Move Dockerfile build paths outside of GOPATH
  Dockerfile.aro-e2e
  Dockerfile.aro-multistage
  Dockerfile.ci
  Dockerfile.proxy
Labels: size-small, ready-for-review, skippy

#3371 Return error on certificateexpirationstatus monitor when IngressController is invalid rather than panic
  pkg/monitor/cluster/certificateexpirationstatuses.go
  pkg/monitor/cluster/certificateexpirationstatuses_test.go
Labels: bug, priority-high, ready-for-review, next-release, loki

#3336 Hopefully fix E2E flake related to deletion of a test Service
  test/e2e/adminapi_delete_managedresource.go
Labels: ready-for-review, chainsaw

#3334 Add E2E test for host servicing
  test/e2e/dns.go
  test/e2e/setup.go
Labels: ready-for-review, chainsaw
