Repository Azure/ARO-RP, pull requests merged in 2024-10, with the labels that each got.

#3874 Remove pipeline chaining from our E2E pipeline
  .pipelines/ci.yml
  .pipelines/e2e.yml
Labels: size-small, next-up, ready-for-review, skippy, github_actions

#3875 Don't run long-running regression tests on PRs
  .pipelines/e2e.yml
  Makefile
  test/e2e/adminapi_redeployvm.go
  test/e2e/dns.go
  test/e2e/setup.go
Labels: size-small, ready-for-review, skippy, github_actions

#3844 CLI Phase 1 - add UpgradeableTo field to update functionality
  python/az/aro/azext_aro/_params.py
  python/az/aro/azext_aro/_validators.py
  python/az/aro/azext_aro/custom.py
  python/az/aro/azext_aro/tests/latest/unit/test_validators.py
Labels: chainsaw

#3860 Populate ClientID and ObjectID of cluster and platform workload identities
  pkg/cluster/cluster.go
  pkg/cluster/clustermsi.go
  pkg/cluster/clustermsi_test.go
  pkg/cluster/install.go
  pkg/cluster/platformworkloadidentities.go
  pkg/cluster/platformworkloadidentities_test.go
  pkg/util/azureclient/azuresdk/armmsi/generate.go
  pkg/util/azureclient/azuresdk/armmsi/user_assigned_identities.go
  pkg/util/mocks/azureclient/azuresdk/armmsi/armmsi.go
Labels: loki, chainsaw

#3877 MIWI - Provide boundServiceAccountSigningKey secret to Hive Install
  pkg/hive/install.go
  pkg/hive/resources.go
  pkg/hive/resources_test.go
Labels: loki, chainsaw

#3881 Hotfix - MSI RP endpoint env var
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production-parameters.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/scripts/util-services.sh
  pkg/deploy/generator/templates_rp.go
Labels: ready-for-review, release-blocker, next-release, chainsaw

#3886 MacOS `make generate` fix - regenerate certain mocks using source mode instead of reflect mode
  pkg/cluster/generate.go
  pkg/frontend/adminactions/generate.go
  pkg/frontend/generate.go
  pkg/util/mocks/adminactions/adminactions.go
  pkg/util/mocks/adminactions/applens.go
  pkg/util/mocks/adminactions/azureactions.go
  pkg/util/mocks/adminactions/kubeactions.go
  pkg/util/mocks/cluster/cluster.go
  pkg/util/mocks/frontend/adminreplies.go
  pkg/util/mocks/frontend/frontend.go
  pkg/util/mocks/frontend/providers_validation.go
  pkg/util/mocks/frontend/quota_validation.go
  pkg/util/mocks/frontend/sku_validation.go
Labels: ready-for-review, chainsaw

#3870 disallow refresh_cluster_credentials with platowrm_workload_identities
  python/az/aro/azext_aro/_validators.py
  python/az/aro/azext_aro/tests/latest/unit/test_validators.py
Labels: ready-for-review, chainsaw

#3896 Fix bug in hive-dev-install.sh
  hack/hive/hive-dev-install.sh
Labels: bug, chainsaw

#3882 Migrate VPN and rp service to Docker Compose
  .pipelines/ci.yml
  .pipelines/templates/template-acr-push.yml
  Dockerfile.vpn
  Dockerfile.vpn.dockerignore
  Makefile
  docker-compose.yml
  env.example
Labels: size-small, loki

#3899 Quickfix - restore inadvertently overwritten mocks
  pkg/util/azureclient/azuresdk/armmsi/generate.go
  pkg/util/mocks/azureclient/azuresdk/armmsi/federated_identity_credentials.go
  pkg/util/mocks/azureclient/azuresdk/armmsi/user_assigned_identities.go
Labels: ready-for-review, chainsaw

#3901 Update localdev platformworkloadidentityrolesets
  hack/devtools/local_dev_env.sh
Labels: loki, chainsaw

#3900 Quickfix - codify solution to another `make generate` issue on MacOS
  Makefile
Labels: ready-for-review, chainsaw

#3712 adding DDS family sku support
  pkg/api/admin/openshiftcluster.go
  pkg/api/openshiftcluster.go
  pkg/api/validate/vm.go
Labels: hold

#3847 Generate Federated Identity Credentials for MIWI Cluster
  hack/devtools/local_dev_env.sh
  pkg/cluster/delete.go
  pkg/cluster/delete_test.go
  pkg/cluster/deploybaseresources.go
  pkg/cluster/deploybaseresources_additional.go
  pkg/cluster/deploybaseresources_test.go
  pkg/cluster/install.go
  pkg/cluster/workloadidentityresources.go
  pkg/cluster/workloadidentityresources_test.go
  test/util/azure/msi/armmsi.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server/server.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/msi/armmsi/fake/federatedidentitycredentials_server.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/msi/armmsi/fake/internal.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/msi/armmsi/fake/operations_server.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/msi/armmsi/fake/server_factory.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/msi/armmsi/fake/systemassignedidentities_server.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/msi/armmsi/fake/time_rfc3339.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/msi/armmsi/fake/userassignedidentities_server.go
  vendor/modules.txt
Labels: go, chainsaw

#3903 Correct convention for OIDC issuer urls
  pkg/cluster/delete.go
  pkg/cluster/deploybaseresources.go
  pkg/cluster/deploybaseresources_test.go
  pkg/env/env.go
  pkg/util/oidcbuilder/oidcbuilder.go
Labels: ready-for-review, chainsaw

#3914 Tolerate failures to delete federated credentials during deletion
  pkg/cluster/delete.go
Labels: bug, chainsaw

#3907 Set correlation ID on outbound Azure requests
  pkg/util/azureclient/roundtripper.go
  pkg/util/azureclient/roundtripper_test.go
Labels: next-up, next-release, chainsaw

#3851 Adding role assignment for the devops managed identity
  pkg/deploy/assets/rp-development.json
  pkg/deploy/assets/rp-production-parameters.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/config.go
  pkg/deploy/config_test.go
  pkg/deploy/deploy_rp.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/templates_rp.go
Labels: bug, next-up, ready-for-review, release-blocker, next-release, firefly

#3924 ARO-11546 update AZURE_FEDERATED_TOKEN_FILE value to have /token at end
  pkg/operator/deploy/deploy.go
  pkg/operator/deploy/deploy_test.go
  pkg/operator/deploy/staticresources/master/deployment.yaml.tmpl
Labels: ready-for-review, chainsaw

#3911 [ARO-1885] Implement OperatorFlagsMergeStrategy
  pkg/api/admin/openshiftcluster.go
  pkg/api/admin/operatorflags.go
  pkg/api/admin/operatorflags_test.go
  pkg/frontend/openshiftcluster_putorpatch.go
  pkg/frontend/openshiftcluster_putorpatch_test.go
Labels: enhancement, ready-for-review, go, skippy

#3921 [ARO-11578] Don't log serial console logs on adminUpdate/Update failures, and cap the amount we log
  pkg/cluster/failurediagnostics/virtualmachines.go
  pkg/cluster/failurediagnostics/virtualmachines_test.go
  pkg/cluster/gatherlogs.go
  pkg/cluster/install.go
  pkg/cluster/install_test.go
Labels: bug, size-small, next-up, ready-for-review, next-release, go, skippy

#3867 add an update step to replace digicert with onecert
  pkg/cluster/adminupdate_test.go
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/cluster/correct_cert_issuer.go
  pkg/cluster/correct_cert_issuer_test.go
  pkg/cluster/install.go
  pkg/util/azureclient/keyvault/base.go
  pkg/util/keyvault/keyvault.go
  pkg/util/mocks/azureclient/keyvault/keyvault.go
  pkg/util/mocks/keyvault/keyvault.go
Labels: ready-for-review, next-release

#3928 ARO-9716 during miwi cluster install remove azure file csi storage class
  pkg/cluster/install.go
  pkg/cluster/storageclass.go
  pkg/cluster/storageclass_test.go
Labels: ready-for-review, chainsaw

#3931 Update cosmosdb auth used by update_role_sets.go
  cmd/aro/update_role_sets.go
Labels: ready-for-review, chainsaw
