Repository Azure/ARO-RP, pull requests merged in 2024-04, with the labels that each got.

#3465 Remove portal v1
  .gdn/.gdnsuppress
  Makefile
  docs/admin-portal.md
  pkg/portal/assets/assets.go
  pkg/portal/assets/v1/build/index.html
  pkg/portal/assets/v1/build/main.js
  pkg/portal/assets/v1/build/main.js.LICENSE.txt
  pkg/portal/assets/v1/build/styles.css
  pkg/portal/assets/v2/build/asset-manifest.json
  pkg/portal/assets/v2/build/index.html
  pkg/portal/assets/v2/build/static/js/main.09fbc574.js
  pkg/portal/assets/v2/build/static/js/main.09fbc574.js.LICENSE.txt
  pkg/portal/assets/v2/build/static/js/main.662aea13.js
  pkg/portal/assets/v2/build/static/js/main.662aea13.js.LICENSE.txt
  pkg/portal/portal.go
  pkg/portal/security_test.go
  portal/v1/package-lock.json
  portal/v1/package.json
  portal/v1/src/index.html
  portal/v1/src/index.js
  portal/v1/src/select/select.css
  portal/v1/webpack.common.js
  portal/v1/webpack.dev.js
  portal/v1/webpack.prod.js
  portal/v2/src/App.tsx
Labels: ready-for-review, next-release, skippy

#3478 Add new initial fields to v20240812preview
  .sha256sum
  pkg/api/admin/openshiftcluster.go
  pkg/api/admin/openshiftcluster_convert.go
  pkg/api/openshiftcluster.go
  pkg/api/v20240812preview/openshiftcluster.go
  pkg/api/v20240812preview/openshiftcluster_convert.go
  pkg/api/v20240812preview/openshiftcluster_example.go
  pkg/client/services/redhatopenshift/mgmt/2024-08-12-preview/redhatopenshift/models.go
  python/client/azure/mgmt/redhatopenshift/v2024_08_12_preview/models/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2024_08_12_preview/models/_models.py
  python/client/azure/mgmt/redhatopenshift/v2024_08_12_preview/models/_models_py3.py
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2024-08-12-preview/examples/OpenShiftClusters_CreateOrUpdate.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2024-08-12-preview/examples/OpenShiftClusters_Get.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2024-08-12-preview/examples/OpenShiftClusters_List.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2024-08-12-preview/examples/OpenShiftClusters_ListByResourceGroup.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2024-08-12-preview/examples/OpenShiftClusters_Update.json
  swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/preview/2024-08-12-preview/redhatopenshift.json
Labels: ready-for-review, chainsaw

#3504 Remove SkipLinuxAzSecPack from RP and Gateway VMSS
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
Labels: ready-for-review, release-blocker, next-release

#3487 Ensure Fluentbit/MDSD spec operatorflags assume default version when set to empty string
  pkg/operator/controllers/genevalogging/genevalogging.go
  pkg/operator/controllers/genevalogging/genevalogging_test.go
Labels: next-release

#3495 Sync go-toolset 1.20.12
  cmd/aro/mirror.go
Labels: size-small, ready-for-review, skippy

#3522 MIWI preview API - Add PlatformWorkloadIdentityRoleSet proxy resource type
  pkg/api/admin/platformworkloadidentityroleset.go
  pkg/api/admin/platformworkloadidentityroleset_convert.go
  pkg/api/admin/platformworkloadidentityroleset_validatestatic.go
  pkg/api/platformworkloadidentityroleset.go
  pkg/api/platformworkloadidentityrolesetdocument.go
  pkg/api/platformworkloadidentityrolesetdocument_example.go
  pkg/api/v20240812preview/platformworkloadidentityroleset.go
  pkg/api/v20240812preview/platformworkloadidentityroleset_convert.go
  pkg/api/v20240812preview/platformworkloadidentityroleset_example.go
Labels: ready-for-review, chainsaw

#3536 extended maximum wait time before yum update
  pkg/deploy/assets/env-development.json
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/scripts/devProxyVMSS.sh
  pkg/deploy/generator/scripts/gatewayVMSS.sh
  pkg/deploy/generator/scripts/rpVMSS.sh
Labels: next-release

#3519 Change the upgrademode of VMSS to rolling
  pkg/deploy/assets/env-development.json
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_dev.go
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
Labels: ready-for-review

#3520 Setting TLS1.2 as min for cosmoDB
  pkg/deploy/assets/databases-development.json
  pkg/deploy/assets/rp-development.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_rp.go
  pkg/util/arm/marshal.go
  pkg/util/azureclient/apiversions.go
Labels: priority-high, ready-for-review, firefly
