Repository Azure/ARO-RP, pull requests merged in 2025-08, with the labels that each got.

#4332 [ARO-20197] Move e2e hive check to use liveconfig instead
  test/e2e/setup.go
Labels: bug, priority-high, next-up, ready-for-review, next-release, skippy, e2e

#4337 Remove cblecker from codeowners
  .github/CODEOWNERS
Labels: ready-for-review

#4336 [ARO-20277] Don't use the user pullsecret to pull the Installer container
  pkg/hive/resources.go
  pkg/hive/resources_test.go
  pkg/util/pullsecret/pullsecret.go
Labels: size-small, ready-for-review, go, skippy

#4334 [ARO-20197-2] Run the cluster metrics steps in parallel
  cmd/aro/mimoactuator.go
  cmd/aro/monitor.go
  cmd/aro/portal.go
  pkg/cluster/gatherlogs.go
  pkg/cluster/gatherlogs_test.go
  pkg/env/prod.go
  pkg/frontend/admin_hive_clusterdeployment_get.go
  pkg/frontend/admin_hive_syncset_resources.go
  pkg/hive/manager.go
  pkg/hive/manager_test.go
  pkg/monitor/cluster/arooperatorheartbeat.go
  pkg/monitor/cluster/arooperatorheartbeat_test.go
  pkg/monitor/cluster/cache.go
  pkg/monitor/cluster/certificateexpirationstatuses.go
  pkg/monitor/cluster/certificateexpirationstatuses_test.go
  pkg/monitor/cluster/cluster.go
  pkg/monitor/cluster/cluster_test.go
  pkg/monitor/cluster/clusterauthenticationtype.go
  pkg/monitor/cluster/clusterauthenticationtype_test.go
  pkg/monitor/cluster/clusteroperatorconditions.go
  pkg/monitor/cluster/clusteroperatorconditions_test.go
  pkg/monitor/cluster/clusteroperatorversions.go
  pkg/monitor/cluster/clusteroperatorversions_test.go
  pkg/monitor/cluster/clusterversionconditions.go
  pkg/monitor/cluster/clusterversionconditions_test.go
  pkg/monitor/cluster/clusterversions.go
  pkg/monitor/cluster/clusterversions_test.go
  pkg/monitor/cluster/healthz.go
  pkg/monitor/cluster/hiveregistrationstatus_panics_test.go
  pkg/monitor/cluster/machineconfigpool.go
  pkg/monitor/cluster/machineconfigpool_test.go
  pkg/monitor/cluster/machineconfigpoolconditions.go
  pkg/monitor/cluster/machineconfigpoolconditions_test.go
  pkg/monitor/cluster/nodeconditions.go
  pkg/monitor/cluster/nodeconditions_test.go
  pkg/monitor/cluster/summary.go
  pkg/monitor/cluster/summary_test.go
  pkg/monitor/emitter/emitter.go
  pkg/monitor/hive/clustersync.go
  pkg/monitor/hive/clustersync_test.go
  pkg/monitor/hive/hive.go
  pkg/monitor/hive/hiveregistrationstatus.go
  pkg/monitor/hive/hiveregistrationstatus_test.go
  pkg/monitor/monitor.go
  pkg/monitor/worker.go
  pkg/portal/portal.go
  pkg/proxy/dialer.go
  pkg/util/mocks/hive/hive.go
  pkg/util/steps/runner.go
  test/e2e/monitor.go
  test/util/clienthelper/hookclient.go
Labels: size-medium, ready-for-review, go, skippy

#4335 ARO-20202 - get rid of deprecated mgmt network cilent in deploybaseresources.go and deploybaseresources_additional.go
  pkg/cluster/deploybaseresources.go
  pkg/cluster/deploybaseresources_additional.go
  pkg/cluster/deploybaseresources_test.go
Labels: size-medium, ready-for-review, go

#4357 Bug fix - MIWI cluster deletion blocker
  pkg/cluster/delete.go
  pkg/cluster/delete_test.go
Labels: ready-for-review, chainsaw
