Repository Azure/ARO-RP, pull requests merged in 2025-06, with the labels that each got.

#4224 Bumping up fluentbit image
  pkg/util/version/const.go
Labels: ready-for-review, firefly

#4235 Wait for cluster deletion before retrying Create in e2e setup
  test/e2e/setup.go
Labels: ready-for-review, loki

#4253 Add top pods and nodes admin endpoints to local RP doc
  docs/deploy-development-rp.md
Labels: ready-for-review, loki

#4256 Set the identity and description to "Unkonw" when empty
  pkg/util/log/audit/otel_audit.go
Labels: ready-for-review

#4263 Mirror Go 1.24 builder images
  cmd/aro/mirror.go
Labels: chainsaw

#4265 update validate_enable_managed_identity function to no longer check the --version argument
  python/az/aro/azext_aro/_validators.py
  python/az/aro/azext_aro/tests/latest/unit/test_validators.py
Labels: ready-for-review, chainsaw

#4289 ARO-9309: Geneva Action to Renew MDSD Certificate
  pkg/frontend/admin_mimo_manifest_create.go
  pkg/frontend/admin_mimo_manifest_create_mdsdcertificaterenew.go
  pkg/frontend/admin_mimo_manifest_create_mdsdcertificaterenew_test.go
  pkg/frontend/frontend.go
Labels: ready-for-review, go, skippy

#4228 [ARO-17460] Support zonal IPs in cluster creation
  pkg/api/openshiftcluster.go
  pkg/cluster/cluster.go
  pkg/cluster/deploybaseresources_additional.go
  pkg/cluster/deploybaseresources_additional_test.go
  pkg/cluster/deploybaseresources_test.go
  pkg/cluster/install.go
  pkg/cluster/ipaddresses_test.go
  pkg/cluster/validate.go
  pkg/cluster/validate_test.go
  pkg/env/env.go
  pkg/env/zz_generated_feature_enumer.go
  pkg/util/azurezones/azurezones.go
  pkg/util/azurezones/azurezones_test.go
Labels: enhancement, size-medium, go, skippy
