Repository Azure/ARO-RP, pull requests merged in 2025-01, with the labels that each got.

#4036 Ensure necessary env vars are set for temp E2E DB deletion
  .pipelines/ci.yml
Labels: chainsaw

#4018 Hive Update af54e2fbd9
  cmd/aro/mirror.go
  go.mod
  hack/hive/hive-generate-config.sh
  vendor/modules.txt
Labels: ready-for-review, release-blocker, dependencies, go, chainsaw

#4035 Use built-in marshaler for all track2 SDK structs
  pkg/frontend/adminactions/resources_list_test.go
  pkg/util/arm/marshal.go
  pkg/util/arm/marshal_test.go
  test/util/json/json.go
Labels: priority-high, next-release, loki

#4021 Add PlatformWorkloadIdentityRoleSetsList to operations list for v2024-08-12-preview
  pkg/api/operation.go
  pkg/api/v20240812preview/register.go
Labels: chainsaw

#4040 Updating MDM, MDSD, Fluentbit Images
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/util/version/const.go
Labels: release-blocker, next-release

#4037 Fix MIWI Cluster update flow to add new openshift operator identity
  pkg/cluster/cluster.go
  pkg/cluster/install.go
  pkg/cluster/platformworkloadidentities.go
  pkg/cluster/platformworkloadidentities_test.go
  pkg/cluster/validate.go
  pkg/cluster/workloadidentityresources.go
  pkg/cluster/workloadidentityresources_test.go
  pkg/util/mocks/dynamic/dynamic.go
  pkg/validate/dynamic/dynamic.go
  pkg/validate/dynamic/platformworkloadidentityprofile.go
  pkg/validate/dynamic/platformworkloadidentityprofile_test.go
  pkg/validate/openshiftcluster_validatedynamic.go
Labels: bug, ready-for-review, chainsaw

#4046 Fix MIWI admin update
  pkg/api/admin/openshiftcluster.go
  pkg/cluster/adminupdate_test.go
  pkg/cluster/install.go
Labels: next-release, chainsaw

#3934 Log MIWI/SP install type to AsyncQoS; also log successful cluster deletions
  pkg/backend/openshiftcluster.go
  pkg/backend/openshiftcluster_test.go
Labels: next-release, chainsaw

#4062 Add unit test case for admin PATCH-ing a workload identity cluster
  pkg/frontend/openshiftcluster_putorpatch_test.go
Labels: ready-for-review, chainsaw

#4063 Ensure admin updates persist platform workload identity IDs
  pkg/cluster/adminupdate_test.go
  pkg/cluster/install.go
Labels: chainsaw

#4075 Use cluster doc ID as cluster MSI KV secret name
  pkg/cluster/clustermsi.go
  pkg/cluster/clustermsi_test.go
  pkg/cluster/delete.go
  pkg/cluster/delete_test.go
Labels: ready-for-review, chainsaw
