Repository Azure/ARO-RP, pull requests merged in 2025-09, with the labels that each got.

#4304 [ARO-20049] Update deps for July 25
  .bingo/Variables.mk
  .bingo/golangci-lint.mod
  .bingo/golangci-lint.sum
  .bingo/mockgen.mod
  .bingo/mockgen.sum
  .bingo/variables.env
  go.mod
  go.sum
  pkg/portal/security_test.go
  pkg/util/clusterdata/clusterdata.go
  pkg/util/mocks/subnet/subnet.go
Labels: size-medium, ready-for-review, go, skippy

#4356 Reorder the cluster retry logic to preserve the final failed cluster
  pkg/util/cluster/cluster.go
Labels: chainsaw

#4364 Bump golangci-lint to v2.2.1 in github actions
  .github/workflows/ci-go.yml
Labels: chainsaw

#4362 Fix creation of UDR clusters
  pkg/api/openshiftcluster.go
  pkg/cluster/deploybaseresources_additional.go
  pkg/cluster/deploybaseresources_additional_test.go
  pkg/cluster/deploybaseresources_test.go
  pkg/cluster/validate.go
  pkg/cluster/validate_test.go
  pkg/util/pointerutils/pointerutils.go
Labels: priority-high, next-up, ready-for-review, next-release, go

#4352 [ARO-20197] Reduce memory usage in subscriptions cache as well as correct logging and metrics being unqueryable
  cmd/aro/deploy.go
  cmd/aro/gateway.go
  cmd/aro/mimoactuator.go
  cmd/aro/mirror.go
  cmd/aro/monitor.go
  cmd/aro/portal.go
  cmd/aro/rp.go
  cmd/aro/update_ocp_versions.go
  cmd/aro/update_role_sets.go
  hack/aead/aead.go
  hack/clean/clean.go
  hack/db/db.go
  hack/gendevconfig/gendevconfig.go
  hack/portalauth/portalauth.go
  hack/role/role.go
  pkg/database/fromenv.go
  pkg/deploy/deploy.go
  pkg/env/core.go
  pkg/env/dev.go
  pkg/env/env.go
  pkg/env/msiauthorizer.go
  pkg/env/prod.go
  pkg/metrics/statsd/statsd.go
  pkg/metrics/statsd/statsd_test.go
  pkg/mirror/acrauth.go
  pkg/monitor/azure/nsg/nsg.go
  pkg/monitor/azure/nsg/nsg_test.go
  pkg/monitor/cluster/arooperatorheartbeat.go
  pkg/monitor/cluster/arooperatorheartbeat_test.go
  pkg/monitor/cluster/cluster.go
  pkg/monitor/cluster/cluster_test.go
  pkg/monitor/cluster/clusterauthenticationtype_test.go
  pkg/monitor/cluster/clusterversions.go
  pkg/monitor/cluster/clusterversions_test.go
  pkg/monitor/cluster/clusterwideproxystatus_test.go
  pkg/monitor/cluster/errors.go
  pkg/monitor/cluster/healthz.go
  pkg/monitor/cluster/managednamespaces.go
  pkg/monitor/cluster/replicasetstatuses.go
  pkg/monitor/hive/hive.go
  pkg/monitor/monitor.go
  pkg/monitor/monitoring/interface.go
  pkg/monitor/worker.go
  pkg/util/mocks/env/core.go
  pkg/util/mocks/env/env.go
  pkg/util/version/version.go
  test/e2e/monitor.go
  test/e2e/setup.go
  test/util/error/error.go
Labels: size-medium, next-up, go, skippy

#4363 Align identity struct tags in admin API with public APIs
  pkg/api/admin/openshiftcluster.go
Labels: ready-for-review, chainsaw

#4378 [ARO-21066] Regenerate autorest clients to match old Python v5 client API
  .golangci.yml
  hack/apiclients/build-dev-api-clients.sh
  pkg/client/services/redhatopenshift/mgmt/2024-08-12-preview/redhatopenshift/client.go
  pkg/client/services/redhatopenshift/mgmt/2024-08-12-preview/redhatopenshift/models.go
  pkg/client/services/redhatopenshift/mgmt/2024-08-12-preview/redhatopenshift/openshiftclusters.go
  pkg/client/services/redhatopenshift/mgmt/2024-08-12-preview/redhatopenshift/openshiftversions.go
  pkg/client/services/redhatopenshift/mgmt/2024-08-12-preview/redhatopenshift/operations.go
  pkg/client/services/redhatopenshift/mgmt/2024-08-12-preview/redhatopenshift/platformworkloadidentityroleset.go
  pkg/client/services/redhatopenshift/mgmt/2024-08-12-preview/redhatopenshift/platformworkloadidentityrolesets.go
  pkg/client/services/redhatopenshift/mgmt/2025-07-25/redhatopenshift/client.go
  pkg/client/services/redhatopenshift/mgmt/2025-07-25/redhatopenshift/models.go
  pkg/client/services/redhatopenshift/mgmt/2025-07-25/redhatopenshift/openshiftclusters.go
  pkg/client/services/redhatopenshift/mgmt/2025-07-25/redhatopenshift/openshiftversions.go
  pkg/client/services/redhatopenshift/mgmt/2025-07-25/redhatopenshift/operations.go
  pkg/client/services/redhatopenshift/mgmt/2025-07-25/redhatopenshift/platformworkloadidentityroleset.go
  pkg/client/services/redhatopenshift/mgmt/2025-07-25/redhatopenshift/platformworkloadidentityrolesets.go
  python/client/azure/mgmt/redhatopenshift/v2024_08_12_preview/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2024_08_12_preview/_azure_red_hat_open_shift_client.py
  python/client/azure/mgmt/redhatopenshift/v2024_08_12_preview/models/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2024_08_12_preview/models/_azure_red_hat_open_shift_client_enums.py
  python/client/azure/mgmt/redhatopenshift/v2024_08_12_preview/models/_models_py3.py
  python/client/azure/mgmt/redhatopenshift/v2024_08_12_preview/operations/_operations.py
  python/client/azure/mgmt/redhatopenshift/v2025_07_25/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2025_07_25/_azure_red_hat_open_shift_client.py
  python/client/azure/mgmt/redhatopenshift/v2025_07_25/models/__init__.py
  python/client/azure/mgmt/redhatopenshift/v2025_07_25/models/_azure_red_hat_open_shift_client_enums.py
  python/client/azure/mgmt/redhatopenshift/v2025_07_25/models/_models_py3.py
  python/client/azure/mgmt/redhatopenshift/v2025_07_25/operations/_operations.py
Labels: bug, priority-high, size-small, next-up, ready-for-review, next-release, go, skippy

#4322 Adding new tokenContributerRoles for staging to avoid conflicts
  pkg/deploy/assets/rp-production-global-subscription.json
  pkg/deploy/assets/rp-production-global.json
  pkg/deploy/assets/rp-production-parameters.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/config.go
  pkg/deploy/devconfig.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/templates_rp.go
  pkg/deploy/predeploy.go
  pkg/util/rbac/rbac.go
Labels: ready-for-review

#4350 [ARO-20727] Use the list kubeadmin API instead of bootlegging it from the console
  pkg/util/azureclient/mgmt/redhatopenshift/2024-08-12-preview/redhatopenshift/openshiftclusters.go
  pkg/util/azureclient/mgmt/redhatopenshift/2025-07-25/redhatopenshift/openshiftclusters.go
  test/e2e/setup.go
  test/util/kubeadminkubeconfig/kubeconfig.go
  test/util/kubeadminkubeconfig/kubetoken.go
  test/util/kubeadminkubeconfig/kubetoken_test.go
Labels: size-small, ready-for-review, skippy, e2e

#4393 [ARO-21181] Fix panics taking down the Monitor
  pkg/monitor/azure/nsg/nsg.go
  pkg/monitor/cluster/cluster.go
  pkg/monitor/cluster/cluster_test.go
  pkg/monitor/cluster/errors.go
  pkg/monitor/dimension/const.go
  pkg/monitor/hive/errors.go
  pkg/monitor/hive/hive.go
  pkg/monitor/hive/hive_test.go
  pkg/monitor/monitoring/errors.go
  pkg/monitor/monitoring/interface.go
  pkg/monitor/worker.go
  pkg/monitor/worker_test.go
  pkg/util/stringutils/stringutils.go
  pkg/util/stringutils/stringutils_test.go
Labels: priority-high, size-medium, ready-for-review, go, skippy
