Repository Azure/ARO-RP, pull requests merged in 2025-02, with the labels that each got.

#4078 MIWI bug fix: parse KV error correctly
  pkg/cluster/clustermsi.go
  pkg/cluster/clustermsi_test.go
Labels: ready-for-review, chainsaw

#4082 [ARO-15038] Allow through openshift.io/ annotations on service accounts
  pkg/util/clienthelper/clienthelper.go
  pkg/util/clienthelper/clienthelper_test.go
  pkg/util/dynamichelper/dynamichelper.go
  pkg/util/dynamichelper/dynamichelper_test.go
Labels: bug, priority-high, size-small, next-up, ready-for-review, operator, next-release, go, skippy

#4099 ARO-13921 Add cluster subnets' network security groups to List Cluster Azure Resources output if cluster uses preconfiguredNSG
  pkg/frontend/adminactions/azureactions.go
  pkg/frontend/adminactions/resources_list.go
  pkg/frontend/adminactions/resources_list_test.go
Labels: good first issue, go

#4096 [ARO-15124] Merge the implementations of dynamichelper and clienthelper's Merge function
  pkg/util/clienthelper/clienthelper.go
  pkg/util/clienthelper/clienthelper_test.go
  pkg/util/dynamichelper/dynamichelper.go
  pkg/util/dynamichelper/dynamichelper_test.go
Labels: priority-low, size-small, ready-for-review, go, skippy

#4107 Correct log message format to pass golangci-lint
  pkg/monitor/cluster/clusterwideproxystatus.go
Labels: bug, chainsaw

#4106 Update Hive API and Image to 5d3f4d77dc
  cmd/aro/mirror.go
  go.mod
  hack/hive/hive-generate-config.sh
  vendor/modules.txt
Labels: dependencies, chainsaw

#4104 Dev environment doc updates
  docs/deploy-development-rp.md
  docs/prepare-your-dev-environment.md
Labels: documentation, ready-for-review

#4119 Create a target to start aro monitor
  Makefile
  docs/unit-testing-for-monitoring-metrics.md
Labels: skippy

#4102 Improve over-reconciliation of Hive Deployments
  pkg/util/clienthelper/clienthelper.go
  pkg/util/clienthelper/clienthelper_test.go
Labels: size-small, ready-for-review, go, skippy
