Repository Azure/ARO-RP, pull requests merged in 2025-04, with the labels that each got.

#4175 [ARO-16076] Bump version of MUO
  cmd/aro/mirror.go
Labels: size-small, next-up, ready-for-review, next-release, skippy

#4178 [ARO-16076] Remove OCM connection in MUO, update MUO
  pkg/operator/controllers/muo/config/config.go
  pkg/operator/controllers/muo/muo_controller.go
  pkg/operator/controllers/muo/muo_controller_test.go
  pkg/operator/controllers/muo/staticresources/cluster_role.yaml
  pkg/operator/controllers/muo/staticresources/config.yaml
  pkg/operator/controllers/muo/staticresources/custom_resource_definition.yaml
  pkg/operator/controllers/muo/staticresources/muo_alerts.yaml
  pkg/operator/controllers/muo/template_test.go
  pkg/operator/controllers/muo/test_files/connected.yaml
  pkg/util/version/const.go
Labels: next-up, ready-for-review, skippy

#4135 dnsmasq.conf: remove strict-order and add dns-forward-max
  pkg/operator/controllers/dnsmasq/scripts/dnsmasq.conf.gotmpl
  pkg/operator/controllers/etchosts/etchosts.go
  pkg/operator/controllers/etchosts/etchosts_test.go
Labels: chainsaw

#4173 [ARO-15117] MIWI e2e - remove disk-csi missing permissions workaround
  pkg/util/cluster/cluster.go
Labels: ready-for-review, chainsaw

#4181 Re-structured, expanded and cleaned prepare-your-dev-environment doc
  docs/prepare-your-dev-environment.md
Labels: ready-for-review, firefly

#4161 return actionable error when invalid identity is passed
  pkg/api/error.go
  pkg/cluster/platformworkloadidentities.go
  pkg/util/azureerrors/error.go
Labels: next-release, chainsaw

#4189 Update Hive APIs to 87bff5947f, Hive Operator to Image 87bff5947f
  cmd/aro/mirror.go
  go.mod
  hack/hive/hive-generate-config.sh
Labels: dependencies, chainsaw

#4184 ARO-16202 retry bootstrap steps if an authentication error is returned
  pkg/cluster/install.go
Labels: next-release, chainsaw

#4204 Fix E2E - remove HiveClusterDeploymentReady from cluster updates
  pkg/cluster/adminupdate_test.go
  pkg/cluster/install.go
Labels: ready-for-review, chainsaw

#4207 [ARO-16955] Move encryption at host validation to frontend skuvalidation
  pkg/env/env.go
  pkg/env/prod.go
  pkg/frontend/sku_test.go
  pkg/frontend/sku_validation.go
  pkg/util/computeskus/computeskus.go
  pkg/util/computeskus/computeskus_test.go
  pkg/util/mocks/dynamic/dynamic.go
  pkg/util/mocks/env/env.go
  pkg/validate/dynamic/dynamic.go
  pkg/validate/dynamic/encryptionathost.go
  pkg/validate/dynamic/encryptionathost_test.go
  pkg/validate/openshiftcluster_validatedynamic.go
Labels: size-medium, ready-for-review, go, skippy

#4212 [ARO-16989] Update Admin Portal v2 deps
  pkg/portal/assets/v2/build/asset-manifest.json
  pkg/portal/assets/v2/build/index.html
  pkg/portal/assets/v2/build/static/js/520.51e128d7.chunk.js
  pkg/portal/assets/v2/build/static/js/520.51e128d7.chunk.js.map
  pkg/portal/assets/v2/build/static/js/520.5db92cdf.chunk.js
  pkg/portal/assets/v2/build/static/js/520.5db92cdf.chunk.js.map
  pkg/portal/assets/v2/build/static/js/main.75ad0f11.js
  pkg/portal/assets/v2/build/static/js/main.75ad0f11.js.LICENSE.txt
  pkg/portal/assets/v2/build/static/js/main.f4c9ee83.js
  pkg/portal/assets/v2/build/static/js/main.f4c9ee83.js.LICENSE.txt
  portal/v2/package-lock.json
  portal/v2/package.json
  portal/v2/src/App.tsx
  portal/v2/src/ClusterDetail.tsx
  portal/v2/src/ClusterDetailList.tsx
  portal/v2/src/ClusterList.tsx
  portal/v2/src/index.tsx
  test/e2e/admin_portal.go
Labels: javascript, skippy

#4211 [ARO-9171] Remove clustermanager code from pkg/database and pkg/api
  pkg/api/clustermanager.go
  pkg/api/clustermanagerdocument.go
  pkg/api/clustermanagerdocument_example.go
  pkg/database/clustermanager.go
  pkg/database/cosmosdb/generate.go
  pkg/database/cosmosdb/zz_generated_clustermanagerconfigurationdocument.go
  pkg/database/cosmosdb/zz_generated_clustermanagerconfigurationdocument_fake.go
  pkg/database/database.go
  pkg/deploy/assets/databases-development.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_rp.go
  pkg/frontend/shared_test.go
  test/database/clustermanager.go
  test/database/fixtures.go
  test/database/inmemory.go
Labels: ready-for-review, go, skippy
