Repository Azure/ARO-RP, pull requests merged in 2025-07, with the labels that each got.

#4303 [ARO-19249] Regenerate + update Kiota graph SDK
  go.mod
  go.sum
  pkg/util/graph/graphsdk/applications/application_item_request_builder.go
  pkg/util/graph/graphsdk/applications/applications_request_builder.go
  pkg/util/graph/graphsdk/applications/get_expand_query_parameter_type.go
  pkg/util/graph/graphsdk/applications/get_orderby_query_parameter_type.go
  pkg/util/graph/graphsdk/applications/get_select_query_parameter_type.go
  pkg/util/graph/graphsdk/applications/item/get_expand_query_parameter_type.go
  pkg/util/graph/graphsdk/applications/item/get_select_query_parameter_type.go
  pkg/util/graph/graphsdk/applications/item_add_password_post_request_body.go
  pkg/util/graph/graphsdk/applications/item_add_password_request_builder.go
  pkg/util/graph/graphsdk/graph_base_service_client.go
  pkg/util/graph/graphsdk/kiota-lock.json
  pkg/util/graph/graphsdk/models/application.go
  pkg/util/graph/graphsdk/models/application_collection_response.go
  pkg/util/graph/graphsdk/models/base_collection_pagination_count_response.go
  pkg/util/graph/graphsdk/models/directory_object.go
  pkg/util/graph/graphsdk/models/entity.go
  pkg/util/graph/graphsdk/models/odataerrors/error_details.go
  pkg/util/graph/graphsdk/models/odataerrors/inner_error.go
  pkg/util/graph/graphsdk/models/odataerrors/main_error.go
  pkg/util/graph/graphsdk/models/odataerrors/o_data_error.go
  pkg/util/graph/graphsdk/models/password_credential.go
  pkg/util/graph/graphsdk/models/service_principal.go
  pkg/util/graph/graphsdk/models/service_principal_collection_response.go
  pkg/util/graph/graphsdk/serviceprincipals/get_expand_query_parameter_type.go
  pkg/util/graph/graphsdk/serviceprincipals/get_orderby_query_parameter_type.go
  pkg/util/graph/graphsdk/serviceprincipals/get_select_query_parameter_type.go
  pkg/util/graph/graphsdk/serviceprincipals/item/get_expand_query_parameter_type.go
  pkg/util/graph/graphsdk/serviceprincipals/item/get_select_query_parameter_type.go
  pkg/util/graph/graphsdk/serviceprincipals/service_principal_item_request_builder.go
  pkg/util/graph/graphsdk/serviceprincipals/service_principals_request_builder.go
Labels: size-small, ready-for-review, skippy

#4305 turn on guardrails by default
  pkg/operator/flags.go
Labels: size-small, ready-for-review, next-release, skippy

#4295 portal: ssh: specificy various algorithms on the command-line
  pkg/portal/ssh/proxy_test.go
  pkg/portal/ssh/ssh.go
  pkg/portal/ssh/ssh_test.go
Labels: ready-for-review, chainsaw

#4316 [ARO-20029] Fix az aro dev client on newer autorest/az CLI
  python/az/aro/azext_aro/_client_factory.py
Labels: bug, next-up, next-release, skippy

#4236 Fix bounds error validating network profile when IngressProfiles is empty
  pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20200430/openshiftcluster_validatestatic_test.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20220401/openshiftcluster_validatestatic_test.go
  pkg/api/v20220904/openshiftcluster_validatestatic_test.go
  pkg/api/v20230401/openshiftcluster_validatestatic.go
  pkg/api/v20230401/openshiftcluster_validatestatic_test.go
  pkg/api/v20230701preview/openshiftcluster_validatestatic.go
  pkg/api/v20230701preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20230904/openshiftcluster_validatestatic.go
  pkg/api/v20230904/openshiftcluster_validatestatic_test.go
  pkg/api/v20231122/openshiftcluster_validatestatic.go
  pkg/api/v20231122/openshiftcluster_validatestatic_test.go
  pkg/api/v20240812preview/openshiftcluster_validatestatic.go
  pkg/api/v20240812preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20250725/openshiftcluster_validatestatic.go
  pkg/api/v20250725/openshiftcluster_validatestatic_test.go
Labels: chainsaw

#4320 [ARO-20038] Fix zone checking and creation code
  pkg/api/openshiftcluster.go
  pkg/cluster/validate.go
  pkg/cluster/validate_test.go
  pkg/util/azurezones/azurezones.go
  pkg/util/azurezones/azurezones_test.go
Labels: bug, priority-high, size-small, next-up, next-release, go, skippy
