Repository Azure/ARO-RP, pull requests merged in 2025-03, with the labels that each got.

#4127 Reapply changes from #3704 into clienthelper as well
  pkg/util/clienthelper/clienthelper.go
  pkg/util/clienthelper/clienthelper_test.go
Labels: bug, priority-high, size-small, next-up, next-release, skippy

#4091 [ARO-9308] Add MDSD Certificate rotation tasks to MIMO
  pkg/cluster/arooperator.go
  pkg/cluster/mdsd.go
  pkg/mimo/const.go
  pkg/mimo/steps/cluster/mdsd.go
  pkg/mimo/steps/cluster/mdsd_test.go
  pkg/mimo/tasks/mdsd.go
  pkg/mimo/tasks/taskrunner.go
  pkg/operator/deploy/deploy.go
  pkg/util/mocks/operator/deploy/deploy.go
Labels: enhancement, size-small, ready-for-review, go, skippy

#4132 Revert changes to restore immutability of PreconfiguredNSG
  pkg/api/admin/openshiftcluster.go
Labels: ready-for-review, loki

#4130 Update local development to deploy OpenShift 4.16 by default
  .pipelines/vars.yml
  pkg/containerinstall/install.go
  pkg/util/cluster/cluster.go
  pkg/util/version/const.go
Labels: priority-high, size-small, next-up, ready-for-review, go, skippy

#4116 CWP - Optional checks with clusterDomain
  pkg/monitor/cluster/clusterwideproxystatus.go
  pkg/monitor/cluster/clusterwideproxystatus_test.go
Labels: size-small, next-release, go, firefly

#4142 Add OtelAuditQueueSize in dev configuration
  pkg/deploy/devconfig.go
Labels: ready-for-review

#4157 Add explicit Resource Manager Endpoint for USGovernmentCloud
  pkg/util/clientauthorizer/arm.go
  pkg/util/clientauthorizer/arm_test.go
Labels: bug, priority-high, next-release

#4146 [ARO-15514] feat: move subnet validation logic to subnet level
  pkg/api/error.go
  pkg/validate/dynamic/dynamic.go
  pkg/validate/dynamic/dynamic_test.go
Labels: release-blocker, next-release

#4126 remove some namespaces from privileged_ns for guardrails
  pkg/operator/controllers/guardrails/policies/gktemplates-src/library/common.rego
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-delete-pull-secret.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-machine-config.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-master-toleration-taints.yaml
  pkg/operator/controllers/guardrails/policies/gktemplates/aro-deny-privileged-namespace.yaml
Labels: size-small, ready-for-review, skippy

#4152 Update Image Gallery to Non HOBO 1P for VMSS instances
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/generator/resources_gateway.go
  pkg/deploy/generator/resources_rp.go
Labels: release-blocker, next-release, chainsaw

#4148 Update Default VM Sizes to Dsv5 for Cluster Creation
  pkg/util/cluster/cluster.go
Labels: ready-for-review, loki

#4070 Implementation of MISE middleware
  docs/deploy-full-rp-service-in-dev.md
  pkg/deploy/assets/gateway-production.json
  pkg/deploy/assets/rp-production-parameters.json
  pkg/deploy/assets/rp-production.json
  pkg/deploy/config.go
  pkg/deploy/devconfig.go
  pkg/deploy/generator/resources_rp.go
  pkg/deploy/generator/scripts/gatewayVMSS.sh
  pkg/deploy/generator/scripts/rpVMSS.sh
  pkg/deploy/generator/scripts/util-common.sh
  pkg/deploy/generator/scripts/util-services.sh
  pkg/deploy/generator/templates_rp.go
  pkg/env/env.go
  pkg/env/prod.go
  pkg/env/zz_generated_feature_enumer.go
  pkg/frontend/frontend.go
  pkg/frontend/middleware/authenticated.go
  pkg/frontend/middleware/authenticated_test.go
  pkg/frontend/ready_get.go
  pkg/frontend/security_test.go
  pkg/frontend/shared_test.go
  pkg/util/miseadapter/authorizer.go
  pkg/util/miseadapter/authorizer_fake.go
  pkg/util/miseadapter/miseadapter.go
  pkg/util/miseadapter/miseadapter_test.go
  pkg/util/mocks/env/env.go
  pkg/util/version/const.go
Labels: priority-high, go, firefly

#4165 [ARO-3865] Remove dependence on pkg/util/uuid in pkg/api
  .golangci.yml
  pkg/api/admin/openshiftcluster_validatestatic_test.go
  pkg/api/correlation.go
  pkg/api/util/uuid/uuid.go
  pkg/api/v20191231preview/openshiftcluster_validatestatic.go
  pkg/api/v20191231preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20200430/openshiftcluster_validatestatic.go
  pkg/api/v20200430/openshiftcluster_validatestatic_test.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic.go
  pkg/api/v20210901preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20220401/openshiftcluster_validatestatic.go
  pkg/api/v20220401/openshiftcluster_validatestatic_test.go
  pkg/api/v20220904/openshiftcluster_validatestatic.go
  pkg/api/v20220904/openshiftcluster_validatestatic_test.go
  pkg/api/v20230401/openshiftcluster_validatestatic.go
  pkg/api/v20230401/openshiftcluster_validatestatic_test.go
  pkg/api/v20230701preview/openshiftcluster_validatestatic.go
  pkg/api/v20230701preview/openshiftcluster_validatestatic_test.go
  pkg/api/v20230904/openshiftcluster_validatestatic.go
  pkg/api/v20230904/openshiftcluster_validatestatic_test.go
  pkg/api/v20231122/openshiftcluster_validatestatic.go
  pkg/api/v20231122/openshiftcluster_validatestatic_test.go
  pkg/api/v20240812preview/openshiftcluster_validatestatic.go
  pkg/api/v20240812preview/openshiftcluster_validatestatic_test.go
  pkg/util/uuid/fake/fake_uuid.go
  pkg/util/uuid/uuid.go
Labels: size-small, ready-for-review, go, skippy

#4171 fix: GHA prune-tags
  .github/workflows/prune-tags.yml
Labels: chainsaw
